import type { AppLocale } from "./types";
const en = {
  "Opening Hey Hermes": "Opening Hey Hermes",
  "Checking for a secure saved session.": "Checking for a secure saved session.",
  "Your private assistant, ready when you are.": "Your private assistant, ready when you are.",
  "Account access": "Account access",
  "Sign in": "Sign in",
  "Create account": "Create account",
  "Password": "Password",
  "Access code (if you have not set a password)": "Access code (if you have not set a password)",
  "Create your account securely with Google or Apple.": "Create your account securely with Google or Apple.",
  "Account creation is not available in this build.": "Account creation is not available in this build.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.",
  "Continue setup securely": "Continue setup securely",
  "Close secure credential entry": "Close secure credential entry",
  "Back to sign in": "Back to sign in",
  "Private access": "Private access",
  "Access code": "Access code",
  "Only if you received one": "Only if you received one",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "New accounts use a password. Existing invite-code accounts can still sign in with their access code.",
  "Redeem invite": "Redeem invite",
  "Invite code": "Invite code",
  "At least 12 characters": "At least 12 characters",
  "Confirm password": "Confirm password",
  "Repeat password": "Repeat password",
  "Create my account": "Create my account",
  "A private home for your personal Hermes assistant.": "A private home for your personal Hermes assistant.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.",
  "Sensitive details encrypted": "Sensitive details encrypted",
  "Your machine in Europe": "Your machine in Europe",
  "No ads, no data sale": "No ads, no data sale",
  "Private workspace": "Private workspace",
  "Terms": "Terms",
  "Loading Hey Hermes...": "Loading Hey Hermes...",
  "or continue with": "or continue with",
  "Choose a sign-up method": "Choose a sign-up method",
  "Continue with Google": "Continue with Google",
  "Sign up with Google": "Sign up with Google",
  "Retry now": "Retry now"
,
"FinanceHermes authorization": "FinanceHermes authorization",
"Review the requested access for your Hey Hermes account.": "Review the requested access for your Hey Hermes account.",
"Loading authorization details...": "Loading authorization details...",
"Connect FinanceHermes": "Connect FinanceHermes",
"FinanceHermes will receive:": "FinanceHermes will receive:",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "This connects your existing Hey Hermes account and workspace. It does not create another account.",
"Enable FinanceHermes access for this account and continue.": "Enable FinanceHermes access for this account and continue.",
"Continue": "Continue"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "Could not reach the local Hey Hermes test server. Start the local server, then try again.",
"Could not reach Hey Hermes. Check your connection, then try again.": "Could not reach Hey Hermes. Check your connection, then try again.",
"Your saved sign-in has ended. Please sign in again.": "Your saved sign-in has ended. Please sign in again.",
"Signing in...": "Signing in...",
"Login failed.": "Login failed.",
"Account session changed.": "Account session changed.",
"No voice note audio was saved.": "No voice note audio was saved.",
"Voice recording could not be completed.": "Voice recording could not be completed."
,
"App Store purchases are not configured in this build.": "App Store purchases are not configured in this build.",
"App Store plans are unavailable.": "App Store plans are unavailable.",
"The signed-in Hey account changed before subscription confirmation.": "The signed-in Hey account changed before subscription confirmation.",
"Personal is active for this Hey account.": "Personal is active for this Hey account.",
"The App Store purchase finished. Access will appear after server confirmation.": "The App Store purchase finished. Access will appear after server confirmation.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "The App Store purchase finished, but server confirmation is still pending. Do not purchase again.",
"Purchase status could not be confirmed.": "Purchase status could not be confirmed.",
"Your App Store purchase is restored for this Hey account.": "Your App Store purchase is restored for this Hey account.",
"Restore finished. The server found no active App Store access for this Hey account.": "Restore finished. The server found no active App Store access for this Hey account.",
"Restore finished, but server confirmation is temporarily unavailable.": "Restore finished, but server confirmation is temporarily unavailable.",
"App Store purchases could not be restored.": "App Store purchases could not be restored.",
"Could not restore the saved session.": "Could not restore the saved session."
,
"The first-conversation state could not be loaded.": "The first-conversation state could not be loaded.",
"The guided setup state could not be loaded.": "The guided setup state could not be loaded.",
"Google did not return a valid Hey Hermes identity.": "Google did not return a valid Hey Hermes identity.",
"This Google sign-in attempt expired. Start again.": "This Google sign-in attempt expired. Start again.",
"Google sign-in failed.": "Google sign-in failed.",
"The Apple credential is revoked or unavailable.": "The Apple credential is revoked or unavailable.",
"Apple did not return a valid Hey Hermes identity.": "Apple did not return a valid Hey Hermes identity.",
"Apple sign-in failed.": "Apple sign-in failed.",
"Could not load Hey Hermes.": "Could not load Hey Hermes.",
"The existing account access status could not be refreshed.": "The existing account access status could not be refreshed.",
"Finance authorization could not be resumed.": "Finance authorization could not be resumed.",
"Finance authorization did not return a redirect.": "Finance authorization did not return a redirect.",
"Finance authorization could not be completed.": "Finance authorization could not be completed.",
"Invite could not be redeemed.": "Invite could not be redeemed."
,
"Social sign-in": "Social sign-in",
"or": "or",
"Opening Apple…": "Opening Apple…",
"Link Apple": "Link Apple",
"Continue with Apple": "Continue with Apple",
"Sign-in could not be completed.": "Sign-in could not be completed.",
"Sign in with Apple is unavailable.": "Sign in with Apple is unavailable.",
"The sign-in provider could not be opened.": "The sign-in provider could not be opened."
};
const catalog: Record<AppLocale, typeof en> = { en,
"de": {
  "Opening Hey Hermes": "Hey Hermes wird geöffnet",
  "Checking for a secure saved session.": "Gespeicherte sichere Sitzung wird geprüft.",
  "Your private assistant, ready when you are.": "Dein privater Assistent, bereit, wenn du es bist.",
  "Account access": "Account-Zugang",
  "Sign in": "Anmelden",
  "Create account": "Account erstellen",
  "Password": "Passwort",
  "Access code (if you have not set a password)": "Zugangscode (falls du noch kein Passwort gesetzt hast)",
  "Create your account securely with Google or Apple.": "Erstelle deinen Account sicher mit Google oder Apple.",
  "Account creation is not available in this build.": "In dieser Version können keine Accounts erstellt werden.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "Verbindungsdaten sind verschlüsselt. Chat-Inhalte bleiben privat in diesem Workspace und werden von Hey Hermes verarbeitet.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "Lokale Tests verwenden standardmäßig http://localhost:4100. In den Expo-Einstellungen kann diese Version auf einen anderen Server zeigen.",
  "Continue setup securely": "Einrichtung sicher fortsetzen",
  "Close secure credential entry": "Sichere Zugangsdaten-Eingabe schließen",
  "Back to sign in": "Zurück zur Anmeldung",
  "Private access": "Privater Zugang",
  "Access code": "Zugangscode",
  "Only if you received one": "Nur falls du einen erhalten hast",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "Neue Accounts verwenden ein Passwort. Bestehende Accounts mit Einladungscode können sich weiterhin mit ihrem Zugangscode anmelden.",
  "Redeem invite": "Einladung einlösen",
  "Invite code": "Einladungscode",
  "At least 12 characters": "Mindestens 12 Zeichen",
  "Confirm password": "Passwort bestätigen",
  "Repeat password": "Passwort wiederholen",
  "Create my account": "Meinen Account erstellen",
  "A private home for your personal Hermes assistant.": "Ein privates Zuhause für deinen persönlichen Hermes-Assistenten.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermes ist dein persönlicher KI-Helfer zum Chatten, Planen, Merken und Arbeiten mit Notizen. Er kann nützliche Seiten, Werkzeuge und verbundene Apps für dich bereitstellen. Dein privater Bereich ist durch Anmeldung geschützt, von anderen Nutzern getrennt und verwendet verschlüsselte Verbindungsdaten.",
  "Sensitive details encrypted": "Sensible Daten verschlüsselt",
  "Your machine in Europe": "Dein Rechner in Europa",
  "No ads, no data sale": "Keine Werbung, kein Datenverkauf",
  "Private workspace": "Privater Workspace",
  "Terms": "Nutzungsbedingungen",
  "Loading Hey Hermes...": "Hey Hermes wird geladen…",
  "or continue with": "oder fortfahren mit",
  "Choose a sign-up method": "Anmeldemethode wählen",
  "Continue with Google": "Mit Google fortfahren",
  "Sign up with Google": "Mit Google registrieren",
  "Retry now": "Jetzt erneut versuchen"
,
"FinanceHermes authorization": "FinanceHermes-Freigabe",
"Review the requested access for your Hey Hermes account.": "Prüfe den angefragten Zugriff auf deinen Hey-Hermes-Account.",
"Loading authorization details...": "Freigabedetails werden geladen …",
"Connect FinanceHermes": "FinanceHermes verbinden",
"FinanceHermes will receive:": "FinanceHermes erhält:",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "Dies verbindet deinen bestehenden Hey-Hermes-Account und Workspace. Es wird kein weiterer Account erstellt.",
"Enable FinanceHermes access for this account and continue.": "Aktiviere den FinanceHermes-Zugriff für diesen Account und fahre fort.",
"Continue": "Weiter"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "Der lokale Hey-Hermes-Testserver ist nicht erreichbar. Starte den lokalen Server und versuche es erneut.",
"Could not reach Hey Hermes. Check your connection, then try again.": "Hey Hermes ist nicht erreichbar. Prüfe deine Verbindung und versuche es erneut.",
"Your saved sign-in has ended. Please sign in again.": "Deine gespeicherte Anmeldung ist abgelaufen. Bitte melde dich erneut an.",
"Signing in...": "Anmeldung läuft …",
"Login failed.": "Anmeldung fehlgeschlagen.",
"Account session changed.": "Die Account-Sitzung hat sich geändert.",
"No voice note audio was saved.": "Für die Sprachnotiz wurde keine Audiodatei gespeichert.",
"Voice recording could not be completed.": "Die Sprachaufnahme konnte nicht abgeschlossen werden."
,
"App Store purchases are not configured in this build.": "App-Store-Käufe sind in diesem Build nicht eingerichtet.",
"App Store plans are unavailable.": "App-Store-Abos sind nicht verfügbar.",
"The signed-in Hey account changed before subscription confirmation.": "Der angemeldete Hey-Account hat sich vor der Abo-Bestätigung geändert.",
"Personal is active for this Hey account.": "Personal ist für diesen Hey-Account aktiv.",
"The App Store purchase finished. Access will appear after server confirmation.": "Der App-Store-Kauf ist abgeschlossen. Der Zugang erscheint nach der Serverbestätigung.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "Der App-Store-Kauf ist abgeschlossen, die Serverbestätigung steht aber noch aus. Bitte nicht erneut kaufen.",
"Purchase status could not be confirmed.": "Der Kaufstatus konnte nicht bestätigt werden.",
"Your App Store purchase is restored for this Hey account.": "Dein App-Store-Kauf wurde für diesen Hey-Account wiederhergestellt.",
"Restore finished. The server found no active App Store access for this Hey account.": "Wiederherstellung abgeschlossen. Der Server hat keinen aktiven App-Store-Zugang für diesen Hey-Account gefunden.",
"Restore finished, but server confirmation is temporarily unavailable.": "Wiederherstellung abgeschlossen, die Serverbestätigung ist vorübergehend nicht verfügbar.",
"App Store purchases could not be restored.": "App-Store-Käufe konnten nicht wiederhergestellt werden.",
"Could not restore the saved session.": "Die gespeicherte Sitzung konnte nicht wiederhergestellt werden."
,
"The first-conversation state could not be loaded.": "Der Status der ersten Unterhaltung konnte nicht geladen werden.",
"The guided setup state could not be loaded.": "Der Status der geführten Einrichtung konnte nicht geladen werden.",
"Google did not return a valid Hey Hermes identity.": "Google hat keine gültige Hey-Hermes-Identität zurückgegeben.",
"This Google sign-in attempt expired. Start again.": "Dieser Google-Anmeldeversuch ist abgelaufen. Starte erneut.",
"Google sign-in failed.": "Die Anmeldung mit Google ist fehlgeschlagen.",
"The Apple credential is revoked or unavailable.": "Die Apple-Anmeldeberechtigung wurde widerrufen oder ist nicht verfügbar.",
"Apple did not return a valid Hey Hermes identity.": "Apple hat keine gültige Hey-Hermes-Identität zurückgegeben.",
"Apple sign-in failed.": "Die Anmeldung mit Apple ist fehlgeschlagen.",
"Could not load Hey Hermes.": "Hey Hermes konnte nicht geladen werden.",
"The existing account access status could not be refreshed.": "Der bestehende Account-Zugriffsstatus konnte nicht aktualisiert werden.",
"Finance authorization could not be resumed.": "Die Finance-Freigabe konnte nicht fortgesetzt werden.",
"Finance authorization did not return a redirect.": "Die Finance-Freigabe hat keine Weiterleitung zurückgegeben.",
"Finance authorization could not be completed.": "Die Finance-Freigabe konnte nicht abgeschlossen werden.",
"Invite could not be redeemed.": "Die Einladung konnte nicht eingelöst werden."
,
"Social sign-in": "Anmeldung mit externem Konto",
"or": "oder",
"Opening Apple…": "Apple wird geöffnet…",
"Link Apple": "Apple verknüpfen",
"Continue with Apple": "Mit Apple fortfahren",
"Sign-in could not be completed.": "Die Anmeldung konnte nicht abgeschlossen werden.",
"Sign in with Apple is unavailable.": "Mit Apple anmelden ist nicht verfügbar.",
"The sign-in provider could not be opened.": "Der Anmeldedienst konnte nicht geöffnet werden."
},
"fr": {
  "Opening Hey Hermes": "Ouverture de Hey Hermes",
  "Checking for a secure saved session.": "Vérification d’une session sécurisée enregistrée.",
  "Your private assistant, ready when you are.": "Votre assistant privé, prêt quand vous l’êtes.",
  "Account access": "Accès au compte",
  "Sign in": "Se connecter",
  "Create account": "Créer un compte",
  "Password": "Mot de passe",
  "Access code (if you have not set a password)": "Code d’accès (si vous n’avez pas défini de mot de passe)",
  "Create your account securely with Google or Apple.": "Créez votre compte en toute sécurité avec Google ou Apple.",
  "Account creation is not available in this build.": "La création de compte n’est pas disponible dans cette version.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "Les données de connexion sont chiffrées. Le contenu du chat reste privé dans cet espace et est traité par Hey Hermes.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "Les tests locaux utilisent par défaut http://localhost:4100. Les réglages Expo peuvent diriger cette version vers un autre serveur.",
  "Continue setup securely": "Poursuivre la configuration en toute sécurité",
  "Close secure credential entry": "Fermer la saisie sécurisée des identifiants",
  "Back to sign in": "Retour à la connexion",
  "Private access": "Accès privé",
  "Access code": "Code d’accès",
  "Only if you received one": "Uniquement si vous en avez reçu un",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "Les nouveaux comptes utilisent un mot de passe. Les comptes existants créés par invitation peuvent toujours utiliser leur code d’accès.",
  "Redeem invite": "Utiliser une invitation",
  "Invite code": "Code d’invitation",
  "At least 12 characters": "Au moins 12 caractères",
  "Confirm password": "Confirmer le mot de passe",
  "Repeat password": "Répéter le mot de passe",
  "Create my account": "Créer mon compte",
  "A private home for your personal Hermes assistant.": "Un espace privé pour votre assistant Hermes personnel.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermes vous offre un assistant IA personnel pour discuter, planifier, retenir l’essentiel, travailler avec vos notes et créer des pages, outils et applications connectées utiles. Votre espace privé est protégé par une connexion, séparé des autres utilisateurs et doté de données de connexion chiffrées.",
  "Sensitive details encrypted": "Données sensibles chiffrées",
  "Your machine in Europe": "Votre machine en Europe",
  "No ads, no data sale": "Sans publicité ni vente de données",
  "Private workspace": "Espace de travail privé",
  "Terms": "Conditions d’utilisation",
  "Loading Hey Hermes...": "Chargement de Hey Hermes…",
  "or continue with": "ou continuer avec",
  "Choose a sign-up method": "Choisir une méthode d’inscription",
  "Continue with Google": "Continuer avec Google",
  "Sign up with Google": "S’inscrire avec Google",
  "Retry now": "Réessayer maintenant"
,
"FinanceHermes authorization": "Autorisation FinanceHermes",
"Review the requested access for your Hey Hermes account.": "Vérifiez l’accès demandé à votre compte Hey Hermes.",
"Loading authorization details...": "Chargement des détails de l’autorisation…",
"Connect FinanceHermes": "Connecter FinanceHermes",
"FinanceHermes will receive:": "FinanceHermes recevra :",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "Cette action connecte votre compte et votre espace Hey Hermes existants. Elle ne crée pas de compte supplémentaire.",
"Enable FinanceHermes access for this account and continue.": "Activez l’accès à FinanceHermes pour ce compte et continuez.",
"Continue": "Continuer"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "Impossible de joindre le serveur de test local Hey Hermes. Démarrez-le, puis réessayez.",
"Could not reach Hey Hermes. Check your connection, then try again.": "Impossible de joindre Hey Hermes. Vérifiez votre connexion, puis réessayez.",
"Your saved sign-in has ended. Please sign in again.": "Votre connexion enregistrée a expiré. Veuillez vous reconnecter.",
"Signing in...": "Connexion en cours…",
"Login failed.": "Échec de la connexion.",
"Account session changed.": "La session du compte a changé.",
"No voice note audio was saved.": "Aucun fichier audio n’a été enregistré pour la note vocale.",
"Voice recording could not be completed.": "L’enregistrement vocal n’a pas pu être terminé."
,
"App Store purchases are not configured in this build.": "Les achats App Store ne sont pas configurés dans cette version.",
"App Store plans are unavailable.": "Les abonnements App Store sont indisponibles.",
"The signed-in Hey account changed before subscription confirmation.": "Le compte Hey connecté a changé avant la confirmation de l’abonnement.",
"Personal is active for this Hey account.": "Personal est actif pour ce compte Hey.",
"The App Store purchase finished. Access will appear after server confirmation.": "L’achat App Store est terminé. L’accès apparaîtra après confirmation du serveur.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "L’achat App Store est terminé, mais la confirmation du serveur est encore en attente. N’achetez pas à nouveau.",
"Purchase status could not be confirmed.": "L’état de l’achat n’a pas pu être confirmé.",
"Your App Store purchase is restored for this Hey account.": "Votre achat App Store est restauré pour ce compte Hey.",
"Restore finished. The server found no active App Store access for this Hey account.": "Restauration terminée. Le serveur n’a trouvé aucun accès App Store actif pour ce compte Hey.",
"Restore finished, but server confirmation is temporarily unavailable.": "Restauration terminée, mais la confirmation du serveur est temporairement indisponible.",
"App Store purchases could not be restored.": "Les achats App Store n’ont pas pu être restaurés.",
"Could not restore the saved session.": "Impossible de restaurer la session enregistrée."
,
"The first-conversation state could not be loaded.": "Impossible de charger l’état de la première conversation.",
"The guided setup state could not be loaded.": "Impossible de charger l’état de la configuration guidée.",
"Google did not return a valid Hey Hermes identity.": "Google n’a pas renvoyé d’identité Hey Hermes valide.",
"This Google sign-in attempt expired. Start again.": "Cette tentative de connexion Google a expiré. Recommencez.",
"Google sign-in failed.": "La connexion Google a échoué.",
"The Apple credential is revoked or unavailable.": "L’identifiant Apple est révoqué ou indisponible.",
"Apple did not return a valid Hey Hermes identity.": "Apple n’a pas renvoyé d’identité Hey Hermes valide.",
"Apple sign-in failed.": "La connexion Apple a échoué.",
"Could not load Hey Hermes.": "Impossible de charger Hey Hermes.",
"The existing account access status could not be refreshed.": "Impossible d’actualiser l’état d’accès actuel du compte.",
"Finance authorization could not be resumed.": "Impossible de reprendre l’autorisation Finance.",
"Finance authorization did not return a redirect.": "L’autorisation Finance n’a pas renvoyé de redirection.",
"Finance authorization could not be completed.": "Impossible de terminer l’autorisation Finance.",
"Invite could not be redeemed.": "Impossible d’utiliser l’invitation."
,
"Social sign-in": "Connexion avec un compte externe",
"or": "ou",
"Opening Apple…": "Ouverture d’Apple…",
"Link Apple": "Associer Apple",
"Continue with Apple": "Continuer avec Apple",
"Sign-in could not be completed.": "La connexion n’a pas pu être terminée.",
"Sign in with Apple is unavailable.": "La connexion avec Apple est indisponible.",
"The sign-in provider could not be opened.": "Le service de connexion n’a pas pu être ouvert."
},
"es": {
  "Opening Hey Hermes": "Abriendo Hey Hermes",
  "Checking for a secure saved session.": "Comprobando si hay una sesión segura guardada.",
  "Your private assistant, ready when you are.": "Tu asistente privado, listo cuando tú lo estés.",
  "Account access": "Acceso a la cuenta",
  "Sign in": "Iniciar sesión",
  "Create account": "Crear cuenta",
  "Password": "Contraseña",
  "Access code (if you have not set a password)": "Código de acceso (si no has configurado una contraseña)",
  "Create your account securely with Google or Apple.": "Crea tu cuenta de forma segura con Google o Apple.",
  "Account creation is not available in this build.": "No se pueden crear cuentas en esta versión.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "Los datos de conexión están cifrados. El contenido del chat es privado para este espacio y lo procesa Hey Hermes.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "Las pruebas locales usan http://localhost:4100 de forma predeterminada. Los ajustes de Expo pueden dirigir esta versión a otro servidor.",
  "Continue setup securely": "Continuar la configuración de forma segura",
  "Close secure credential entry": "Cerrar la entrada segura de credenciales",
  "Back to sign in": "Volver al inicio de sesión",
  "Private access": "Acceso privado",
  "Access code": "Código de acceso",
  "Only if you received one": "Solo si has recibido uno",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "Las cuentas nuevas usan una contraseña. Las cuentas existentes con código de invitación pueden seguir usando su código de acceso.",
  "Redeem invite": "Canjear invitación",
  "Invite code": "Código de invitación",
  "At least 12 characters": "Al menos 12 caracteres",
  "Confirm password": "Confirmar contraseña",
  "Repeat password": "Repetir contraseña",
  "Create my account": "Crear mi cuenta",
  "A private home for your personal Hermes assistant.": "Un hogar privado para tu asistente personal Hermes.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermes te ofrece un asistente personal de IA para conversar, planificar, recordar lo importante, trabajar con tus notas y crear páginas, herramientas y aplicaciones conectadas útiles. Tu espacio privado está protegido por inicio de sesión, separado de otros usuarios y usa datos de conexión cifrados.",
  "Sensitive details encrypted": "Datos sensibles cifrados",
  "Your machine in Europe": "Tu máquina en Europa",
  "No ads, no data sale": "Sin anuncios ni venta de datos",
  "Private workspace": "Espacio de trabajo privado",
  "Terms": "Condiciones",
  "Loading Hey Hermes...": "Cargando Hey Hermes…",
  "or continue with": "o continuar con",
  "Choose a sign-up method": "Elige un método de registro",
  "Continue with Google": "Continuar con Google",
  "Sign up with Google": "Registrarse con Google",
  "Retry now": "Reintentar ahora"
,
"FinanceHermes authorization": "Autorización de FinanceHermes",
"Review the requested access for your Hey Hermes account.": "Revisa el acceso solicitado a tu cuenta de Hey Hermes.",
"Loading authorization details...": "Cargando los detalles de autorización…",
"Connect FinanceHermes": "Conectar FinanceHermes",
"FinanceHermes will receive:": "FinanceHermes recibirá:",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "Esto conecta tu cuenta y espacio de Hey Hermes existentes. No crea otra cuenta.",
"Enable FinanceHermes access for this account and continue.": "Activa el acceso de FinanceHermes para esta cuenta y continúa.",
"Continue": "Continuar"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "No se pudo conectar con el servidor de prueba local de Hey Hermes. Inícialo e inténtalo de nuevo.",
"Could not reach Hey Hermes. Check your connection, then try again.": "No se pudo conectar con Hey Hermes. Comprueba tu conexión e inténtalo de nuevo.",
"Your saved sign-in has ended. Please sign in again.": "Tu sesión guardada ha caducado. Vuelve a iniciar sesión.",
"Signing in...": "Iniciando sesión…",
"Login failed.": "Error al iniciar sesión.",
"Account session changed.": "La sesión de la cuenta ha cambiado.",
"No voice note audio was saved.": "No se guardó ningún audio para la nota de voz.",
"Voice recording could not be completed.": "No se pudo completar la grabación de voz."
,
"App Store purchases are not configured in this build.": "Las compras del App Store no están configuradas en esta versión.",
"App Store plans are unavailable.": "Las suscripciones del App Store no están disponibles.",
"The signed-in Hey account changed before subscription confirmation.": "La cuenta Hey conectada cambió antes de confirmar la suscripción.",
"Personal is active for this Hey account.": "Personal está activo para esta cuenta Hey.",
"The App Store purchase finished. Access will appear after server confirmation.": "La compra del App Store terminó. El acceso aparecerá tras la confirmación del servidor.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "La compra del App Store terminó, pero la confirmación del servidor sigue pendiente. No vuelvas a comprar.",
"Purchase status could not be confirmed.": "No se pudo confirmar el estado de la compra.",
"Your App Store purchase is restored for this Hey account.": "Tu compra del App Store se restauró para esta cuenta Hey.",
"Restore finished. The server found no active App Store access for this Hey account.": "Restauración terminada. El servidor no encontró acceso activo del App Store para esta cuenta Hey.",
"Restore finished, but server confirmation is temporarily unavailable.": "Restauración terminada, pero la confirmación del servidor no está disponible temporalmente.",
"App Store purchases could not be restored.": "No se pudieron restaurar las compras del App Store.",
"Could not restore the saved session.": "No se pudo restaurar la sesión guardada."
,
"The first-conversation state could not be loaded.": "No se pudo cargar el estado de la primera conversación.",
"The guided setup state could not be loaded.": "No se pudo cargar el estado de la configuración guiada.",
"Google did not return a valid Hey Hermes identity.": "Google no devolvió una identidad válida de Hey Hermes.",
"This Google sign-in attempt expired. Start again.": "Este intento de inicio de sesión con Google caducó. Empieza de nuevo.",
"Google sign-in failed.": "El inicio de sesión con Google falló.",
"The Apple credential is revoked or unavailable.": "La credencial de Apple está revocada o no disponible.",
"Apple did not return a valid Hey Hermes identity.": "Apple no devolvió una identidad válida de Hey Hermes.",
"Apple sign-in failed.": "El inicio de sesión con Apple falló.",
"Could not load Hey Hermes.": "No se pudo cargar Hey Hermes.",
"The existing account access status could not be refreshed.": "No se pudo actualizar el estado de acceso actual de la cuenta.",
"Finance authorization could not be resumed.": "No se pudo reanudar la autorización de Finance.",
"Finance authorization did not return a redirect.": "La autorización de Finance no devolvió una redirección.",
"Finance authorization could not be completed.": "No se pudo completar la autorización de Finance.",
"Invite could not be redeemed.": "No se pudo canjear la invitación."
,
"Social sign-in": "Inicio de sesión con una cuenta externa",
"or": "o",
"Opening Apple…": "Abriendo Apple…",
"Link Apple": "Vincular Apple",
"Continue with Apple": "Continuar con Apple",
"Sign-in could not be completed.": "No se pudo completar el inicio de sesión.",
"Sign in with Apple is unavailable.": "El inicio de sesión con Apple no está disponible.",
"The sign-in provider could not be opened.": "No se pudo abrir el proveedor de inicio de sesión."
},
"it": {
  "Opening Hey Hermes": "Apertura di Hey Hermes",
  "Checking for a secure saved session.": "Verifica di una sessione sicura salvata.",
  "Your private assistant, ready when you are.": "Il tuo assistente privato, pronto quando lo sei tu.",
  "Account access": "Accesso all’account",
  "Sign in": "Accedi",
  "Create account": "Crea account",
  "Password": "Password",
  "Access code (if you have not set a password)": "Codice di accesso (se non hai impostato una password)",
  "Create your account securely with Google or Apple.": "Crea il tuo account in sicurezza con Google o Apple.",
  "Account creation is not available in this build.": "La creazione di account non è disponibile in questa versione.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "I dati di connessione sono crittografati. Il contenuto della chat è privato per questo spazio ed è elaborato da Hey Hermes.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "I test locali usano per impostazione predefinita http://localhost:4100. Le impostazioni Expo possono indirizzare questa versione a un altro server.",
  "Continue setup securely": "Continua la configurazione in sicurezza",
  "Close secure credential entry": "Chiudi l’inserimento sicuro delle credenziali",
  "Back to sign in": "Torna all’accesso",
  "Private access": "Accesso privato",
  "Access code": "Codice di accesso",
  "Only if you received one": "Solo se ne hai ricevuto uno",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "I nuovi account usano una password. Gli account esistenti creati con un invito possono continuare ad accedere con il proprio codice.",
  "Redeem invite": "Utilizza invito",
  "Invite code": "Codice di invito",
  "At least 12 characters": "Almeno 12 caratteri",
  "Confirm password": "Conferma password",
  "Repeat password": "Ripeti password",
  "Create my account": "Crea il mio account",
  "A private home for your personal Hermes assistant.": "Uno spazio privato per il tuo assistente Hermes personale.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermes ti offre un assistente IA personale per chattare, pianificare, ricordare ciò che conta, lavorare con le tue note e creare pagine, strumenti e app collegate utili. Il tuo spazio privato è protetto dall’accesso, separato dagli altri utenti e usa dati di connessione crittografati.",
  "Sensitive details encrypted": "Dati sensibili crittografati",
  "Your machine in Europe": "La tua macchina in Europa",
  "No ads, no data sale": "Niente pubblicità né vendita di dati",
  "Private workspace": "Spazio di lavoro privato",
  "Terms": "Condizioni",
  "Loading Hey Hermes...": "Caricamento di Hey Hermes…",
  "or continue with": "oppure continua con",
  "Choose a sign-up method": "Scegli un metodo di registrazione",
  "Continue with Google": "Continua con Google",
  "Sign up with Google": "Registrati con Google",
  "Retry now": "Riprova ora"
,
"FinanceHermes authorization": "Autorizzazione FinanceHermes",
"Review the requested access for your Hey Hermes account.": "Verifica l’accesso richiesto al tuo account Hey Hermes.",
"Loading authorization details...": "Caricamento dei dettagli dell’autorizzazione…",
"Connect FinanceHermes": "Collega FinanceHermes",
"FinanceHermes will receive:": "FinanceHermes riceverà:",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "Questo collega il tuo account e spazio Hey Hermes esistenti. Non crea un altro account.",
"Enable FinanceHermes access for this account and continue.": "Abilita l’accesso a FinanceHermes per questo account e continua.",
"Continue": "Continua"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "Impossibile raggiungere il server di test locale di Hey Hermes. Avvialo e riprova.",
"Could not reach Hey Hermes. Check your connection, then try again.": "Impossibile raggiungere Hey Hermes. Controlla la connessione e riprova.",
"Your saved sign-in has ended. Please sign in again.": "La sessione salvata è scaduta. Accedi di nuovo.",
"Signing in...": "Accesso in corso…",
"Login failed.": "Accesso non riuscito.",
"Account session changed.": "La sessione dell’account è cambiata.",
"No voice note audio was saved.": "Non è stato salvato alcun audio per la nota vocale.",
"Voice recording could not be completed.": "Impossibile completare la registrazione vocale."
,
"App Store purchases are not configured in this build.": "Gli acquisti App Store non sono configurati in questa versione.",
"App Store plans are unavailable.": "Gli abbonamenti App Store non sono disponibili.",
"The signed-in Hey account changed before subscription confirmation.": "L’account Hey connesso è cambiato prima della conferma dell’abbonamento.",
"Personal is active for this Hey account.": "Personal è attivo per questo account Hey.",
"The App Store purchase finished. Access will appear after server confirmation.": "L’acquisto App Store è terminato. L’accesso apparirà dopo la conferma del server.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "L’acquisto App Store è terminato, ma la conferma del server è ancora in attesa. Non acquistare di nuovo.",
"Purchase status could not be confirmed.": "Impossibile confermare lo stato dell’acquisto.",
"Your App Store purchase is restored for this Hey account.": "Il tuo acquisto App Store è stato ripristinato per questo account Hey.",
"Restore finished. The server found no active App Store access for this Hey account.": "Ripristino terminato. Il server non ha trovato un accesso App Store attivo per questo account Hey.",
"Restore finished, but server confirmation is temporarily unavailable.": "Ripristino terminato, ma la conferma del server è temporaneamente non disponibile.",
"App Store purchases could not be restored.": "Impossibile ripristinare gli acquisti App Store.",
"Could not restore the saved session.": "Impossibile ripristinare la sessione salvata."
,
"The first-conversation state could not be loaded.": "Impossibile caricare lo stato della prima conversazione.",
"The guided setup state could not be loaded.": "Impossibile caricare lo stato della configurazione guidata.",
"Google did not return a valid Hey Hermes identity.": "Google non ha restituito un’identità Hey Hermes valida.",
"This Google sign-in attempt expired. Start again.": "Questo tentativo di accesso con Google è scaduto. Ricomincia.",
"Google sign-in failed.": "Accesso con Google non riuscito.",
"The Apple credential is revoked or unavailable.": "La credenziale Apple è revocata o non disponibile.",
"Apple did not return a valid Hey Hermes identity.": "Apple non ha restituito un’identità Hey Hermes valida.",
"Apple sign-in failed.": "Accesso con Apple non riuscito.",
"Could not load Hey Hermes.": "Impossibile caricare Hey Hermes.",
"The existing account access status could not be refreshed.": "Impossibile aggiornare lo stato di accesso attuale dell’account.",
"Finance authorization could not be resumed.": "Impossibile riprendere l’autorizzazione Finance.",
"Finance authorization did not return a redirect.": "L’autorizzazione Finance non ha restituito un reindirizzamento.",
"Finance authorization could not be completed.": "Impossibile completare l’autorizzazione Finance.",
"Invite could not be redeemed.": "Impossibile utilizzare l’invito."
,
"Social sign-in": "Accesso con un account esterno",
"or": "oppure",
"Opening Apple…": "Apertura di Apple…",
"Link Apple": "Collega Apple",
"Continue with Apple": "Continua con Apple",
"Sign-in could not be completed.": "Non è stato possibile completare l’accesso.",
"Sign in with Apple is unavailable.": "Accedi con Apple non è disponibile.",
"The sign-in provider could not be opened.": "Non è stato possibile aprire il servizio di accesso."
},
"pt-BR": {
  "Opening Hey Hermes": "Abrindo Hey Hermes",
  "Checking for a secure saved session.": "Verificando uma sessão segura salva.",
  "Your private assistant, ready when you are.": "Seu assistente privado, pronto quando você estiver.",
  "Account access": "Acesso à conta",
  "Sign in": "Entrar",
  "Create account": "Criar conta",
  "Password": "Senha",
  "Access code (if you have not set a password)": "Código de acesso (se você não definiu uma senha)",
  "Create your account securely with Google or Apple.": "Crie sua conta com segurança usando Google ou Apple.",
  "Account creation is not available in this build.": "A criação de contas não está disponível nesta versão.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "Os dados de conexão são criptografados. O conteúdo do chat é privado para este espaço e processado pelo Hey Hermes.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "Os testes locais usam http://localhost:4100 por padrão. As configurações do Expo podem direcionar esta versão para outro servidor.",
  "Continue setup securely": "Continuar a configuração com segurança",
  "Close secure credential entry": "Fechar a entrada segura de credenciais",
  "Back to sign in": "Voltar para entrar",
  "Private access": "Acesso privado",
  "Access code": "Código de acesso",
  "Only if you received one": "Somente se você recebeu um",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "Novas contas usam senha. Contas existentes criadas com convite ainda podem entrar com seu código de acesso.",
  "Redeem invite": "Resgatar convite",
  "Invite code": "Código de convite",
  "At least 12 characters": "Pelo menos 12 caracteres",
  "Confirm password": "Confirmar senha",
  "Repeat password": "Repetir senha",
  "Create my account": "Criar minha conta",
  "A private home for your personal Hermes assistant.": "Um espaço privado para seu assistente Hermes pessoal.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "O Hey Hermes oferece um assistente pessoal de IA para conversar, planejar, lembrar do que importa, trabalhar com suas notas e criar páginas, ferramentas e aplicativos conectados úteis. Seu espaço privado é protegido por login, separado de outros usuários e usa dados de conexão criptografados.",
  "Sensitive details encrypted": "Dados sensíveis criptografados",
  "Your machine in Europe": "Sua máquina na Europa",
  "No ads, no data sale": "Sem anúncios nem venda de dados",
  "Private workspace": "Espaço de trabalho privado",
  "Terms": "Termos",
  "Loading Hey Hermes...": "Carregando Hey Hermes…",
  "or continue with": "ou continuar com",
  "Choose a sign-up method": "Escolha um método de cadastro",
  "Continue with Google": "Continuar com Google",
  "Sign up with Google": "Cadastrar com Google",
  "Retry now": "Tentar novamente agora"
,
"FinanceHermes authorization": "Autorização do FinanceHermes",
"Review the requested access for your Hey Hermes account.": "Revise o acesso solicitado à sua conta do Hey Hermes.",
"Loading authorization details...": "Carregando os detalhes da autorização…",
"Connect FinanceHermes": "Conectar FinanceHermes",
"FinanceHermes will receive:": "O FinanceHermes receberá:",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "Isso conecta sua conta e espaço existentes do Hey Hermes. Não cria outra conta.",
"Enable FinanceHermes access for this account and continue.": "Ative o acesso do FinanceHermes para esta conta e continue.",
"Continue": "Continuar"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "Não foi possível acessar o servidor de teste local do Hey Hermes. Inicie o servidor e tente novamente.",
"Could not reach Hey Hermes. Check your connection, then try again.": "Não foi possível acessar o Hey Hermes. Verifique sua conexão e tente novamente.",
"Your saved sign-in has ended. Please sign in again.": "Sua sessão salva expirou. Entre novamente.",
"Signing in...": "Entrando…",
"Login failed.": "Falha ao entrar.",
"Account session changed.": "A sessão da conta mudou.",
"No voice note audio was saved.": "Nenhum áudio foi salvo para a nota de voz.",
"Voice recording could not be completed.": "Não foi possível concluir a gravação de voz."
,
"App Store purchases are not configured in this build.": "As compras da App Store não estão configuradas nesta versão.",
"App Store plans are unavailable.": "As assinaturas da App Store estão indisponíveis.",
"The signed-in Hey account changed before subscription confirmation.": "A conta Hey conectada mudou antes da confirmação da assinatura.",
"Personal is active for this Hey account.": "O Personal está ativo para esta conta Hey.",
"The App Store purchase finished. Access will appear after server confirmation.": "A compra na App Store foi concluída. O acesso aparecerá após a confirmação do servidor.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "A compra na App Store foi concluída, mas a confirmação do servidor ainda está pendente. Não compre novamente.",
"Purchase status could not be confirmed.": "Não foi possível confirmar o estado da compra.",
"Your App Store purchase is restored for this Hey account.": "Sua compra da App Store foi restaurada para esta conta Hey.",
"Restore finished. The server found no active App Store access for this Hey account.": "Restauração concluída. O servidor não encontrou acesso ativo da App Store para esta conta Hey.",
"Restore finished, but server confirmation is temporarily unavailable.": "Restauração concluída, mas a confirmação do servidor está temporariamente indisponível.",
"App Store purchases could not be restored.": "Não foi possível restaurar as compras da App Store.",
"Could not restore the saved session.": "Não foi possível restaurar a sessão salva."
,
"The first-conversation state could not be loaded.": "Não foi possível carregar o estado da primeira conversa.",
"The guided setup state could not be loaded.": "Não foi possível carregar o estado da configuração guiada.",
"Google did not return a valid Hey Hermes identity.": "O Google não retornou uma identidade válida do Hey Hermes.",
"This Google sign-in attempt expired. Start again.": "Esta tentativa de login com o Google expirou. Comece novamente.",
"Google sign-in failed.": "Falha ao entrar com o Google.",
"The Apple credential is revoked or unavailable.": "A credencial da Apple foi revogada ou está indisponível.",
"Apple did not return a valid Hey Hermes identity.": "A Apple não retornou uma identidade válida do Hey Hermes.",
"Apple sign-in failed.": "Falha ao entrar com a Apple.",
"Could not load Hey Hermes.": "Não foi possível carregar o Hey Hermes.",
"The existing account access status could not be refreshed.": "Não foi possível atualizar o estado de acesso atual da conta.",
"Finance authorization could not be resumed.": "Não foi possível retomar a autorização do Finance.",
"Finance authorization did not return a redirect.": "A autorização do Finance não retornou um redirecionamento.",
"Finance authorization could not be completed.": "Não foi possível concluir a autorização do Finance.",
"Invite could not be redeemed.": "Não foi possível resgatar o convite."
,
"Social sign-in": "Entrar com uma conta externa",
"or": "ou",
"Opening Apple…": "Abrindo Apple…",
"Link Apple": "Vincular Apple",
"Continue with Apple": "Continuar com Apple",
"Sign-in could not be completed.": "Não foi possível concluir o login.",
"Sign in with Apple is unavailable.": "Entrar com Apple não está disponível.",
"The sign-in provider could not be opened.": "Não foi possível abrir o serviço de login."
},
"ja": {
  "Opening Hey Hermes": "Hey Hermesを開いています",
  "Checking for a secure saved session.": "保存された安全なセッションを確認しています。",
  "Your private assistant, ready when you are.": "必要なときに使える、あなた専用のプライベートアシスタント。",
  "Account access": "アカウントへのアクセス",
  "Sign in": "サインイン",
  "Create account": "アカウントを作成",
  "Password": "パスワード",
  "Access code (if you have not set a password)": "アクセスコード（パスワード未設定の場合）",
  "Create your account securely with Google or Apple.": "GoogleまたはAppleで安全にアカウントを作成できます。",
  "Account creation is not available in this build.": "このバージョンではアカウントを作成できません。",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "接続情報は暗号化されます。チャット内容はこのワークスペース内で非公開に保たれ、Hey Hermesが処理します。",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "ローカルテストでは標準でhttp://localhost:4100を使用します。Expo設定で別のサーバーを指定できます。",
  "Continue setup securely": "安全に設定を続ける",
  "Close secure credential entry": "認証情報の安全な入力を閉じる",
  "Back to sign in": "サインインに戻る",
  "Private access": "プライベートアクセス",
  "Access code": "アクセスコード",
  "Only if you received one": "受け取った場合のみ",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "新規アカウントはパスワードを使用します。既存の招待コード付きアカウントは引き続きアクセスコードでサインインできます。",
  "Redeem invite": "招待を利用",
  "Invite code": "招待コード",
  "At least 12 characters": "12文字以上",
  "Confirm password": "パスワードを確認",
  "Repeat password": "パスワードを再入力",
  "Create my account": "アカウントを作成",
  "A private home for your personal Hermes assistant.": "あなた専用のHermesアシスタントのためのプライベート空間。",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermesは、会話、計画、大切なことの記憶、ノートの活用を手伝い、便利なページやツール、接続アプリを作成できる個人用AIアシスタントです。専用空間はサインインで保護され、他のユーザーから分離され、接続情報は暗号化されます。",
  "Sensitive details encrypted": "機密情報を暗号化",
  "Your machine in Europe": "ヨーロッパにある専用マシン",
  "No ads, no data sale": "広告なし、データ販売なし",
  "Private workspace": "プライベートワークスペース",
  "Terms": "利用規約",
  "Loading Hey Hermes...": "Hey Hermesを読み込んでいます…",
  "or continue with": "または次で続行",
  "Choose a sign-up method": "登録方法を選択",
  "Continue with Google": "Googleで続行",
  "Sign up with Google": "Googleで登録",
  "Retry now": "今すぐ再試行"
,
"FinanceHermes authorization": "FinanceHermesの認可",
"Review the requested access for your Hey Hermes account.": "Hey Hermesアカウントへのアクセス要求を確認してください。",
"Loading authorization details...": "認可の詳細を読み込み中…",
"Connect FinanceHermes": "FinanceHermesを接続",
"FinanceHermes will receive:": "FinanceHermesに提供される情報：",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "既存のHey Hermesアカウントとワークスペースを接続します。別のアカウントは作成されません。",
"Enable FinanceHermes access for this account and continue.": "このアカウントでFinanceHermesへのアクセスを有効にして続行します。",
"Continue": "続行"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "ローカルのHey Hermesテストサーバーに接続できませんでした。ローカルサーバーを起動して再試行してください。",
"Could not reach Hey Hermes. Check your connection, then try again.": "Hey Hermesに接続できませんでした。接続を確認して再試行してください。",
"Your saved sign-in has ended. Please sign in again.": "保存されたログインの有効期限が切れました。もう一度ログインしてください。",
"Signing in...": "ログイン中…",
"Login failed.": "ログインに失敗しました。",
"Account session changed.": "アカウントのセッションが変更されました。",
"No voice note audio was saved.": "音声メモの音声が保存されませんでした。",
"Voice recording could not be completed.": "音声録音を完了できませんでした。"
,
"App Store purchases are not configured in this build.": "このビルドではApp Storeでの購入が設定されていません。",
"App Store plans are unavailable.": "App Storeのプランを利用できません。",
"The signed-in Hey account changed before subscription confirmation.": "サブスクリプション確認前に、ログイン中のHeyアカウントが変更されました。",
"Personal is active for this Hey account.": "このHeyアカウントではPersonalが有効です。",
"The App Store purchase finished. Access will appear after server confirmation.": "App Storeでの購入が完了しました。サーバーの確認後にアクセスが表示されます。",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "App Storeでの購入は完了しましたが、サーバーの確認はまだ保留中です。再購入しないでください。",
"Purchase status could not be confirmed.": "購入状況を確認できませんでした。",
"Your App Store purchase is restored for this Hey account.": "このHeyアカウントのApp Store購入を復元しました。",
"Restore finished. The server found no active App Store access for this Hey account.": "復元が完了しました。このHeyアカウントの有効なApp Storeアクセスはサーバーで見つかりませんでした。",
"Restore finished, but server confirmation is temporarily unavailable.": "復元は完了しましたが、サーバーの確認を一時的に利用できません。",
"App Store purchases could not be restored.": "App Storeでの購入を復元できませんでした。",
"Could not restore the saved session.": "保存されたセッションを復元できませんでした。"
,
"The first-conversation state could not be loaded.": "最初の会話の状態を読み込めませんでした。",
"The guided setup state could not be loaded.": "ガイド付き設定の状態を読み込めませんでした。",
"Google did not return a valid Hey Hermes identity.": "Googleから有効なHey HermesのIDが返されませんでした。",
"This Google sign-in attempt expired. Start again.": "このGoogleログイン試行は期限切れです。やり直してください。",
"Google sign-in failed.": "Googleでのログインに失敗しました。",
"The Apple credential is revoked or unavailable.": "Appleの認証情報が取り消されたか、利用できません。",
"Apple did not return a valid Hey Hermes identity.": "Appleから有効なHey HermesのIDが返されませんでした。",
"Apple sign-in failed.": "Appleでのログインに失敗しました。",
"Could not load Hey Hermes.": "Hey Hermesを読み込めませんでした。",
"The existing account access status could not be refreshed.": "現在のアカウントのアクセス状態を更新できませんでした。",
"Finance authorization could not be resumed.": "Financeの承認を再開できませんでした。",
"Finance authorization did not return a redirect.": "Financeの承認からリダイレクトが返されませんでした。",
"Finance authorization could not be completed.": "Financeの承認を完了できませんでした。",
"Invite could not be redeemed.": "招待を利用できませんでした。"
,
"Social sign-in": "外部アカウントでサインイン",
"or": "または",
"Opening Apple…": "Appleを開いています…",
"Link Apple": "Appleを連携",
"Continue with Apple": "Appleで続ける",
"Sign-in could not be completed.": "サインインを完了できませんでした。",
"Sign in with Apple is unavailable.": "Appleでサインインは利用できません。",
"The sign-in provider could not be opened.": "サインインサービスを開けませんでした。"
},
"ko": {
  "Opening Hey Hermes": "Hey Hermes를 여는 중",
  "Checking for a secure saved session.": "저장된 보안 세션을 확인하고 있습니다.",
  "Your private assistant, ready when you are.": "필요할 때 준비된 나만의 비공개 어시스턴트.",
  "Account access": "계정 접근",
  "Sign in": "로그인",
  "Create account": "계정 만들기",
  "Password": "비밀번호",
  "Access code (if you have not set a password)": "접근 코드(비밀번호를 설정하지 않은 경우)",
  "Create your account securely with Google or Apple.": "Google 또는 Apple로 안전하게 계정을 만드세요.",
  "Account creation is not available in this build.": "이 버전에서는 계정을 만들 수 없습니다.",
  "Connection details are encrypted. Chat content is private to this workspace and processed by Hey Hermes.": "연결 정보는 암호화됩니다. 채팅 내용은 이 워크스페이스 안에서 비공개로 유지되며 Hey Hermes가 처리합니다.",
  "Default local testing uses http://localhost:4100. Expo settings can point this build at another server.": "로컬 테스트는 기본적으로 http://localhost:4100을 사용합니다. Expo 설정에서 이 버전을 다른 서버로 연결할 수 있습니다.",
  "Continue setup securely": "안전하게 설정 계속하기",
  "Close secure credential entry": "안전한 인증 정보 입력 닫기",
  "Back to sign in": "로그인으로 돌아가기",
  "Private access": "비공개 접근",
  "Access code": "접근 코드",
  "Only if you received one": "받은 경우에만 입력",
  "New accounts use a password. Existing invite-code accounts can still sign in with their access code.": "새 계정은 비밀번호를 사용합니다. 기존 초대 코드 계정은 계속 접근 코드로 로그인할 수 있습니다.",
  "Redeem invite": "초대 사용",
  "Invite code": "초대 코드",
  "At least 12 characters": "12자 이상",
  "Confirm password": "비밀번호 확인",
  "Repeat password": "비밀번호 다시 입력",
  "Create my account": "내 계정 만들기",
  "A private home for your personal Hermes assistant.": "나만의 Hermes 어시스턴트를 위한 비공개 공간.",
  "Hey Hermes gives you a personal AI helper that can chat, plan, remember what matters, work with your notes, and grow into useful pages, tools, and connected apps. Your private space is protected by login, separated from other users, and built with encrypted connection details.": "Hey Hermes는 대화, 계획, 중요한 내용 기억, 메모 작업을 돕고 유용한 페이지, 도구, 연결 앱을 만들 수 있는 개인 AI 어시스턴트입니다. 비공개 공간은 로그인으로 보호되며 다른 사용자와 분리되고 연결 정보는 암호화됩니다.",
  "Sensitive details encrypted": "민감 정보 암호화",
  "Your machine in Europe": "유럽에 있는 전용 기기",
  "No ads, no data sale": "광고 및 데이터 판매 없음",
  "Private workspace": "비공개 워크스페이스",
  "Terms": "이용약관",
  "Loading Hey Hermes...": "Hey Hermes를 불러오는 중…",
  "or continue with": "또는 다음으로 계속",
  "Choose a sign-up method": "가입 방법 선택",
  "Continue with Google": "Google로 계속",
  "Sign up with Google": "Google로 가입",
  "Retry now": "지금 다시 시도"
,
"FinanceHermes authorization": "FinanceHermes 승인",
"Review the requested access for your Hey Hermes account.": "Hey Hermes 계정에 요청된 접근 권한을 확인하세요.",
"Loading authorization details...": "승인 세부 정보 불러오는 중…",
"Connect FinanceHermes": "FinanceHermes 연결",
"FinanceHermes will receive:": "FinanceHermes에 제공되는 정보:",
"This connects your existing Hey Hermes account and workspace. It does not create another account.": "기존 Hey Hermes 계정과 작업 공간을 연결합니다. 다른 계정을 만들지 않습니다.",
"Enable FinanceHermes access for this account and continue.": "이 계정의 FinanceHermes 접근을 활성화하고 계속하세요.",
"Continue": "계속"
,
"Could not reach the local Hey Hermes test server. Start the local server, then try again.": "로컬 Hey Hermes 테스트 서버에 연결할 수 없습니다. 로컬 서버를 시작한 뒤 다시 시도하세요.",
"Could not reach Hey Hermes. Check your connection, then try again.": "Hey Hermes에 연결할 수 없습니다. 연결을 확인한 뒤 다시 시도하세요.",
"Your saved sign-in has ended. Please sign in again.": "저장된 로그인 세션이 만료되었습니다. 다시 로그인하세요.",
"Signing in...": "로그인 중…",
"Login failed.": "로그인에 실패했습니다.",
"Account session changed.": "계정 세션이 변경되었습니다.",
"No voice note audio was saved.": "음성 메모의 오디오가 저장되지 않았습니다.",
"Voice recording could not be completed.": "음성 녹음을 완료하지 못했습니다."
,
"App Store purchases are not configured in this build.": "이 빌드에는 App Store 구매가 설정되어 있지 않습니다.",
"App Store plans are unavailable.": "App Store 구독을 사용할 수 없습니다.",
"The signed-in Hey account changed before subscription confirmation.": "구독 확인 전에 로그인한 Hey 계정이 변경되었습니다.",
"Personal is active for this Hey account.": "이 Hey 계정에 Personal이 활성화되어 있습니다.",
"The App Store purchase finished. Access will appear after server confirmation.": "App Store 구매가 완료되었습니다. 서버 확인 후 접근 권한이 표시됩니다.",
"The App Store purchase finished, but server confirmation is still pending. Do not purchase again.": "App Store 구매는 완료되었지만 서버 확인은 아직 대기 중입니다. 다시 구매하지 마세요.",
"Purchase status could not be confirmed.": "구매 상태를 확인하지 못했습니다.",
"Your App Store purchase is restored for this Hey account.": "이 Hey 계정의 App Store 구매를 복원했습니다.",
"Restore finished. The server found no active App Store access for this Hey account.": "복원이 완료되었습니다. 서버에서 이 Hey 계정의 활성 App Store 접근 권한을 찾지 못했습니다.",
"Restore finished, but server confirmation is temporarily unavailable.": "복원은 완료되었지만 서버 확인을 일시적으로 사용할 수 없습니다.",
"App Store purchases could not be restored.": "App Store 구매를 복원하지 못했습니다.",
"Could not restore the saved session.": "저장된 세션을 복원하지 못했습니다."
,
"The first-conversation state could not be loaded.": "첫 대화 상태를 불러오지 못했습니다.",
"The guided setup state could not be loaded.": "안내 설정 상태를 불러오지 못했습니다.",
"Google did not return a valid Hey Hermes identity.": "Google이 유효한 Hey Hermes 신원을 반환하지 않았습니다.",
"This Google sign-in attempt expired. Start again.": "이 Google 로그인 시도가 만료되었습니다. 다시 시작하세요.",
"Google sign-in failed.": "Google 로그인에 실패했습니다.",
"The Apple credential is revoked or unavailable.": "Apple 인증 정보가 취소되었거나 사용할 수 없습니다.",
"Apple did not return a valid Hey Hermes identity.": "Apple이 유효한 Hey Hermes 신원을 반환하지 않았습니다.",
"Apple sign-in failed.": "Apple 로그인에 실패했습니다.",
"Could not load Hey Hermes.": "Hey Hermes를 불러오지 못했습니다.",
"The existing account access status could not be refreshed.": "현재 계정 접근 상태를 새로 고치지 못했습니다.",
"Finance authorization could not be resumed.": "Finance 승인을 재개하지 못했습니다.",
"Finance authorization did not return a redirect.": "Finance 승인에서 리디렉션이 반환되지 않았습니다.",
"Finance authorization could not be completed.": "Finance 승인을 완료하지 못했습니다.",
"Invite could not be redeemed.": "초대를 사용하지 못했습니다."
,
"Social sign-in": "외부 계정으로 로그인",
"or": "또는",
"Opening Apple…": "Apple 여는 중…",
"Link Apple": "Apple 연결",
"Continue with Apple": "Apple로 계속하기",
"Sign-in could not be completed.": "로그인을 완료하지 못했습니다.",
"Sign in with Apple is unavailable.": "Apple로 로그인을 사용할 수 없습니다.",
"The sign-in provider could not be opened.": "로그인 서비스를 열지 못했습니다."
}
};
export function authUiCopy(locale: AppLocale) {
  const copy = catalog[locale];
  return {
    ...copy,
    "Hey Hermes could not be loaded.": locale === "en" ? "Hey Hermes could not be loaded." : copy["Could not load Hey Hermes."],
  };
}
