import type { AppLocale } from "./types";
const en = {
  "Hey suggestion": "Hey suggestion",
  "Suggestion": "Suggestion",
  "Load earlier messages": "Load earlier messages",
  "Scroll to latest message": "Scroll to latest message",
  "Add attachment": "Add attachment",
  "Message": "Message",
  "Suggestions": "Suggestions",
  "Small, optional ways to get more from your private Hermes workspace.": "Small, optional ways to get more from your private Hermes workspace.",
  "Suggestion filters": "Suggestion filters",
  "No suggestions in this filter.": "No suggestions in this filter.",
  "Pages": "Pages",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Links to private pages, apps, or tools Hermes has saved for this workspace.",
  "Manage the account and service connections Hermes can use with your approval.": "Manage the account and service connections Hermes can use with your approval.",
  "Dismiss notification": "Dismiss notification",
  "Confirmation choices": "Confirmation choices",
  "Hermes is working": "Hermes is working",
  "Delegated tasks": "Delegated tasks",
  "Selected files": "Selected files",
  "Discuss": "Discuss",
  "Hermes Kanban is not reachable": "Hermes Kanban is not reachable",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "Tasks are only shown when they come from the real Hermes Kanban source.",
  "Accounts": "Accounts",
  "Prepared workspaces": "Prepared workspaces",
  "Audit": "Audit",
  "Advanced": "Advanced",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "Owner setup for model access and user-connected email, Telegram, and WhatsApp.",
  "Dismiss run status": "Dismiss run status",
  "Browser results": "Browser results",
  "Sources": "Sources",
  "Steps": "Steps",
  "Suggested first messages": "Suggested first messages",
  "Used": "Used",
  "Review cards": "Review cards",
  "Connection setup request": "Connection setup request",
  "No secret is saved and no provider action is taken by this request.": "No secret is saved and no provider action is taken by this request.",
  "Review in chat": "Review in chat",
  "Target": "Target",
  "Action": "Action",
  "Capability": "Capability",
  "Proposed change": "Proposed change",
  "Type": "Type",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once."
,
"Queueing follow-up": "Queueing follow-up",
"Follow-up is running": "Follow-up is running",
"Cancelling follow-up": "Cancelling follow-up",
"Follow-up cancelled": "Follow-up cancelled",
"Follow-up could not run": "Follow-up could not run",
"Follow-up queued": "Follow-up queued",
"Cancel queued follow-up": "Cancel queued follow-up",
"Dismiss queued follow-up": "Dismiss queued follow-up"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.",
"Please sign in again.": "Please sign in again.",
"Today's chat limit has been reached.": "Today's chat limit has been reached.",
"Hermes took too long to answer. Please try again.": "Hermes took too long to answer. Please try again.",
"Hermes could not finish that reply. Try again from this chat.": "Hermes could not finish that reply. Try again from this chat.",
"AI connection needs attention.": "AI connection needs attention.",
"The connection dropped. Please try again.": "The connection dropped. Please try again.",
"That code is approved. The bot answers you from now on.": "That code is approved. The bot answers you from now on."
,
"Could not open that chat.": "Could not open that chat.",
"Could not load earlier messages.": "Could not load earlier messages.",
"Could not open Home chat.": "Could not open Home chat.",
"Could not start a new chat.": "Could not start a new chat.",
"Could not queue the follow-up.": "Could not queue the follow-up.",
"Could not cancel the queued follow-up.": "Could not cancel the queued follow-up.",
"Could not stop that reply.": "Could not stop that reply.",
"Could not reconnect to the current reply.": "Could not reconnect to the current reply.",
"Could not send the message.": "Could not send the message.",
"Your message is being saved. Try again in a moment.": "Your message is being saved. Try again in a moment.",
"Hermes is busy. Try again in a moment.": "Hermes is busy. Try again in a moment.",
"Could not attach the selected photos.": "Could not attach the selected photos.",
"Could not take a photo.": "Could not take a photo.",
"Could not attach the selected files.": "Could not attach the selected files.",
"One attached file is too large. Keep each file under 5 MB.": "One attached file is too large. Keep each file under 5 MB.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "Those attachments are too large together. Keep one message under 10 MB of files.",
"Voice recording could not start.": "Voice recording could not start.",
"Voice note could not be transcribed.": "Voice note could not be transcribed.",
"Could not stop that delegated task.": "Could not stop that delegated task.",
"This chat could not be loaded. Pull down to try again.": "This chat could not be loaded. Pull down to try again."
,
"Could not open that page.": "Could not open that page.",
"Could not copy that public link.": "Could not copy that public link.",
"This page is not a private preview link.": "This page is not a private preview link.",
"Could not publish that page.": "Could not publish that page.",
"Removed from Pages.": "Removed from Pages.",
"Public link copied.": "Public link copied.",
"Public link created and copied.": "Public link created and copied.",
"Public link created.": "Public link created.",
"Ranked Tasks could not be loaded.": "Ranked Tasks could not be loaded.",
"Ranked Tasks automations could not be loaded.": "Ranked Tasks automations could not be loaded.",
"Ranked Tasks automation could not be changed.": "Ranked Tasks automation could not be changed.",
"Ranked Tasks could not be refreshed.": "Ranked Tasks could not be refreshed.",
"That stored ranking could not be shown again.": "That stored ranking could not be shown again.",
"Suggestions are temporarily unavailable.": "Suggestions are temporarily unavailable.",
"Draft added to Chat. Edit it before sending.": "Draft added to Chat. Edit it before sending."
,
"Could not save this secure entry. It may have expired.": "Could not save this secure entry. It may have expired.",
"Could not cancel this secure entry. It may have expired.": "Could not cancel this secure entry. It may have expired.",
"This secure entry request has expired. Ask Hermes to open a new one.": "This secure entry request has expired. Ask Hermes to open a new one.",
"The secure value could not be saved. It was not added to chat.": "The secure value could not be saved. It was not added to chat.",
"The secure entry request could not be cancelled.": "The secure entry request could not be cancelled.",
"{label} was saved securely.": "{label} was saved securely.",
"Camera access is needed to take a photo.": "Camera access is needed to take a photo.",
"The voice recording could not be removed.": "The voice recording could not be removed.",
"Voice note could not be read.": "Voice note could not be read.",
"Check App Store subscriptions before trying again.": "Check App Store subscriptions before trying again."
,
"Photos": "Photos",
"Camera": "Camera",
"Files": "Files"
,
"Loading...": "Loading...",
"Earlier messages": "Earlier messages",
"Delegated work is running": "Delegated work is running",
"Delegated work is waiting": "Delegated work is waiting",
"Open delegated task {name}": "Open delegated task {name}",
"Close delegated task {name}": "Close delegated task {name}",
"Stop and close delegated task {name}": "Stop and close delegated task {name}",
"Working": "Working",
"Waiting for you": "Waiting for you",
"{environment} is starting. I will keep checking automatically.": "{environment} is starting. I will keep checking automatically.",
"Connecting…": "Connecting…",
"Connect workspace": "Connect workspace"
,
"Hermes is getting ready": "Hermes is getting ready",
"Hermes is typing": "Hermes is typing",
"Reply ready": "Reply ready",
"You can attach up to {count} files.": "You can attach up to {count} files.",
"{name} is larger than 5 MB.": "{name} is larger than 5 MB.",
"Attachments can be up to 10 MB in total.": "Attachments can be up to 10 MB in total."
};
const catalog: Record<AppLocale, typeof en> = { en,
"de": {
  "Hey suggestion": "Hey-Vorschlag",
  "Suggestion": "Vorschlag",
  "Load earlier messages": "Frühere Nachrichten laden",
  "Scroll to latest message": "Zur neuesten Nachricht scrollen",
  "Add attachment": "Anhang hinzufügen",
  "Message": "Nachricht",
  "Suggestions": "Vorschläge",
  "Small, optional ways to get more from your private Hermes workspace.": "Kleine, optionale Möglichkeiten, mehr aus deinem privaten Hermes-Workspace zu machen.",
  "Suggestion filters": "Vorschläge filtern",
  "No suggestions in this filter.": "Keine Vorschläge in diesem Filter.",
  "Pages": "Seiten",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Links zu privaten Seiten, Apps oder Werkzeugen, die Hermes für diesen Workspace gespeichert hat.",
  "Manage the account and service connections Hermes can use with your approval.": "Verwalte Account- und Dienstverbindungen, die Hermes mit deiner Zustimmung nutzen darf.",
  "Dismiss notification": "Mitteilung schließen",
  "Confirmation choices": "Bestätigungsoptionen",
  "Hermes is working": "Hermes arbeitet",
  "Delegated tasks": "Delegierte Aufgaben",
  "Selected files": "Ausgewählte Dateien",
  "Discuss": "Besprechen",
  "Hermes Kanban is not reachable": "Hermes-Kanban ist nicht erreichbar",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "Aufgaben werden nur angezeigt, wenn sie aus dem tatsächlichen Hermes-Kanban stammen.",
  "Accounts": "Accounts",
  "Prepared workspaces": "Vorbereitete Workspaces",
  "Audit": "Prüfprotokoll",
  "Advanced": "Erweitert",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "Eigentümereinrichtung für Modellzugang und selbst verbundene E-Mail-, Telegram- und WhatsApp-Konten.",
  "Dismiss run status": "Laufstatus schließen",
  "Browser results": "Browserergebnisse",
  "Sources": "Quellen",
  "Steps": "Schritte",
  "Suggested first messages": "Vorgeschlagene erste Nachrichten",
  "Used": "Verwendet",
  "Review cards": "Prüfkarten",
  "Connection setup request": "Anfrage zur Verbindungseinrichtung",
  "No secret is saved and no provider action is taken by this request.": "Diese Anfrage speichert keine Zugangsdaten und führt keine Provideraktion aus.",
  "Review in chat": "Im Chat prüfen",
  "Target": "Ziel",
  "Action": "Aktion",
  "Capability": "Funktion",
  "Proposed change": "Vorgeschlagene Änderung",
  "Type": "Typ",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "Dies speichert deine Entscheidung für die gespeicherte Aktion. Ist die Karte mit einer ausführbaren Aktion verknüpft, gibt die Zustimmung genau diese Aktion einmalig frei."
,
"Queueing follow-up": "Folgenachricht wird vorgemerkt",
"Follow-up is running": "Folgenachricht wird bearbeitet",
"Cancelling follow-up": "Folgenachricht wird abgebrochen",
"Follow-up cancelled": "Folgenachricht abgebrochen",
"Follow-up could not run": "Folgenachricht konnte nicht ausgeführt werden",
"Follow-up queued": "Folgenachricht vorgemerkt",
"Cancel queued follow-up": "Vorgemerkte Folgenachricht abbrechen",
"Dismiss queued follow-up": "Vorgemerkte Folgenachricht ausblenden"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "Dieser private Hermes-Server ist noch nicht aktiv. Die Admin-Übergabe muss abgeschlossen oder erlassen werden, bevor der Chat starten kann.",
"Please sign in again.": "Bitte melde dich erneut an.",
"Today's chat limit has been reached.": "Das heutige Chat-Limit ist erreicht.",
"Hermes took too long to answer. Please try again.": "Hermes hat zu lange für die Antwort gebraucht. Bitte versuche es erneut.",
"Hermes could not finish that reply. Try again from this chat.": "Hermes konnte diese Antwort nicht abschließen. Versuche es in diesem Chat erneut.",
"AI connection needs attention.": "Die KI-Verbindung benötigt Aufmerksamkeit.",
"The connection dropped. Please try again.": "Die Verbindung wurde unterbrochen. Bitte versuche es erneut.",
"That code is approved. The bot answers you from now on.": "Der Code wurde bestätigt. Der Bot antwortet dir ab jetzt."
,
"Could not open that chat.": "Dieser Chat konnte nicht geöffnet werden.",
"Could not load earlier messages.": "Frühere Nachrichten konnten nicht geladen werden.",
"Could not open Home chat.": "Der Home-Chat konnte nicht geöffnet werden.",
"Could not start a new chat.": "Ein neuer Chat konnte nicht gestartet werden.",
"Could not queue the follow-up.": "Die Folgenachricht konnte nicht eingereiht werden.",
"Could not cancel the queued follow-up.": "Die wartende Folgenachricht konnte nicht abgebrochen werden.",
"Could not stop that reply.": "Diese Antwort konnte nicht gestoppt werden.",
"Could not reconnect to the current reply.": "Die Verbindung zur aktuellen Antwort konnte nicht wiederhergestellt werden.",
"Could not send the message.": "Die Nachricht konnte nicht gesendet werden.",
"Your message is being saved. Try again in a moment.": "Deine Nachricht wird gespeichert. Versuche es gleich erneut.",
"Hermes is busy. Try again in a moment.": "Hermes ist beschäftigt. Versuche es gleich erneut.",
"Could not attach the selected photos.": "Die ausgewählten Fotos konnten nicht angehängt werden.",
"Could not take a photo.": "Es konnte kein Foto aufgenommen werden.",
"Could not attach the selected files.": "Die ausgewählten Dateien konnten nicht angehängt werden.",
"One attached file is too large. Keep each file under 5 MB.": "Eine angehängte Datei ist zu groß. Jede Datei muss kleiner als 5 MB sein.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "Die Anhänge sind zusammen zu groß. Pro Nachricht müssen die Dateien insgesamt kleiner als 10 MB sein.",
"Voice recording could not start.": "Die Sprachaufnahme konnte nicht gestartet werden.",
"Voice note could not be transcribed.": "Die Sprachnotiz konnte nicht transkribiert werden.",
"Could not stop that delegated task.": "Diese delegierte Aufgabe konnte nicht gestoppt werden.",
"This chat could not be loaded. Pull down to try again.": "Dieser Chat konnte nicht geladen werden. Ziehe zum erneuten Versuch nach unten."
,
"Could not open that page.": "Diese Seite konnte nicht geöffnet werden.",
"Could not copy that public link.": "Der öffentliche Link konnte nicht kopiert werden.",
"This page is not a private preview link.": "Diese Seite ist kein privater Vorschaulink.",
"Could not publish that page.": "Diese Seite konnte nicht veröffentlicht werden.",
"Removed from Pages.": "Aus Seiten entfernt.",
"Public link copied.": "Öffentlicher Link kopiert.",
"Public link created and copied.": "Öffentlicher Link erstellt und kopiert.",
"Public link created.": "Öffentlicher Link erstellt.",
"Ranked Tasks could not be loaded.": "Priorisierte Aufgaben konnten nicht geladen werden.",
"Ranked Tasks automations could not be loaded.": "Automationen für priorisierte Aufgaben konnten nicht geladen werden.",
"Ranked Tasks automation could not be changed.": "Die Automation für priorisierte Aufgaben konnte nicht geändert werden.",
"Ranked Tasks could not be refreshed.": "Priorisierte Aufgaben konnten nicht aktualisiert werden.",
"That stored ranking could not be shown again.": "Diese gespeicherte Rangfolge konnte nicht erneut angezeigt werden.",
"Suggestions are temporarily unavailable.": "Vorschläge sind vorübergehend nicht verfügbar.",
"Draft added to Chat. Edit it before sending.": "Entwurf zu Chat hinzugefügt. Bearbeite ihn vor dem Senden."
,
"Could not save this secure entry. It may have expired.": "Diese sichere Eingabe konnte nicht gespeichert werden. Sie ist möglicherweise abgelaufen.",
"Could not cancel this secure entry. It may have expired.": "Diese sichere Eingabe konnte nicht abgebrochen werden. Sie ist möglicherweise abgelaufen.",
"This secure entry request has expired. Ask Hermes to open a new one.": "Diese sichere Eingabe ist abgelaufen. Bitte Hermes, eine neue zu öffnen.",
"The secure value could not be saved. It was not added to chat.": "Der geschützte Wert konnte nicht gespeichert werden. Er wurde nicht zum Chat hinzugefügt.",
"The secure entry request could not be cancelled.": "Die sichere Eingabe konnte nicht abgebrochen werden.",
"{label} was saved securely.": "{label} wurde sicher gespeichert.",
"Camera access is needed to take a photo.": "Zum Fotografieren ist der Kamerazugriff erforderlich.",
"The voice recording could not be removed.": "Die Sprachaufnahme konnte nicht entfernt werden.",
"Voice note could not be read.": "Die Sprachnotiz konnte nicht gelesen werden.",
"Check App Store subscriptions before trying again.": "Prüfe deine App-Store-Abonnements, bevor du es erneut versuchst."
,
"Photos": "Fotos",
"Camera": "Kamera",
"Files": "Dateien"
,
"Loading...": "Wird geladen…",
"Earlier messages": "Frühere Nachrichten",
"Delegated work is running": "Delegierte Arbeit läuft",
"Delegated work is waiting": "Delegierte Arbeit wartet",
"Open delegated task {name}": "Delegierte Aufgabe {name} öffnen",
"Close delegated task {name}": "Delegierte Aufgabe {name} schließen",
"Stop and close delegated task {name}": "Delegierte Aufgabe {name} stoppen und schließen",
"Working": "In Arbeit",
"Waiting for you": "Wartet auf dich",
"{environment} is starting. I will keep checking automatically.": "{environment} startet. Ich prüfe automatisch weiter.",
"Connecting…": "Verbindung wird hergestellt…",
"Connect workspace": "Workspace verbinden"
,
"Hermes is getting ready": "Hermes bereitet sich vor",
"Hermes is typing": "Hermes schreibt",
"Reply ready": "Antwort bereit",
"You can attach up to {count} files.": "Du kannst bis zu {count} Dateien anhängen.",
"{name} is larger than 5 MB.": "{name} ist größer als 5 MB.",
"Attachments can be up to 10 MB in total.": "Anhänge dürfen insgesamt bis zu 10 MB groß sein."
},
"fr": {
  "Hey suggestion": "Suggestion Hey",
  "Suggestion": "Suggestion",
  "Load earlier messages": "Charger les messages précédents",
  "Scroll to latest message": "Aller au dernier message",
  "Add attachment": "Ajouter une pièce jointe",
  "Message": "Message",
  "Suggestions": "Suggestions",
  "Small, optional ways to get more from your private Hermes workspace.": "De petites options pour profiter davantage de votre espace Hermes privé.",
  "Suggestion filters": "Filtres des suggestions",
  "No suggestions in this filter.": "Aucune suggestion avec ce filtre.",
  "Pages": "Pages",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Liens vers les pages, applications ou outils privés enregistrés par Hermes pour cet espace.",
  "Manage the account and service connections Hermes can use with your approval.": "Gérez les connexions aux comptes et services que Hermes peut utiliser avec votre accord.",
  "Dismiss notification": "Fermer la notification",
  "Confirmation choices": "Choix de confirmation",
  "Hermes is working": "Hermes travaille",
  "Delegated tasks": "Tâches déléguées",
  "Selected files": "Fichiers sélectionnés",
  "Discuss": "Discuter",
  "Hermes Kanban is not reachable": "Hermes Kanban est inaccessible",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "Les tâches ne sont affichées que si elles proviennent de la source Hermes Kanban réelle.",
  "Accounts": "Comptes",
  "Prepared workspaces": "Espaces préparés",
  "Audit": "Journal d’audit",
  "Advanced": "Avancé",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "Configuration propriétaire pour l’accès aux modèles et les comptes e-mail, Telegram et WhatsApp connectés par l’utilisateur.",
  "Dismiss run status": "Fermer l’état d’exécution",
  "Browser results": "Résultats du navigateur",
  "Sources": "Sources",
  "Steps": "Étapes",
  "Suggested first messages": "Premiers messages suggérés",
  "Used": "Utilisé",
  "Review cards": "Cartes à vérifier",
  "Connection setup request": "Demande de configuration de connexion",
  "No secret is saved and no provider action is taken by this request.": "Cette demande n’enregistre aucun identifiant secret et n’effectue aucune action chez un fournisseur.",
  "Review in chat": "Vérifier dans le chat",
  "Target": "Cible",
  "Action": "Action",
  "Capability": "Capacité",
  "Proposed change": "Modification proposée",
  "Type": "Type",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "Votre décision est enregistrée pour l’action stockée. Si la carte est liée à une action exécutable, l’approbation autorise cette action précise une seule fois."
,
"Queueing follow-up": "Mise en attente du message suivant",
"Follow-up is running": "Traitement du message suivant",
"Cancelling follow-up": "Annulation du message suivant",
"Follow-up cancelled": "Message suivant annulé",
"Follow-up could not run": "Le message suivant n’a pas pu être traité",
"Follow-up queued": "Message suivant en attente",
"Cancel queued follow-up": "Annuler le message en attente",
"Dismiss queued follow-up": "Masquer le message en attente"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "Ce serveur Hermes privé n’est pas encore actif. Le transfert administrateur doit être terminé ou levé avant de pouvoir discuter.",
"Please sign in again.": "Veuillez vous reconnecter.",
"Today's chat limit has been reached.": "La limite de discussion du jour est atteinte.",
"Hermes took too long to answer. Please try again.": "Hermes a mis trop de temps à répondre. Veuillez réessayer.",
"Hermes could not finish that reply. Try again from this chat.": "Hermes n’a pas pu terminer cette réponse. Réessayez depuis cette discussion.",
"AI connection needs attention.": "La connexion IA nécessite votre attention.",
"The connection dropped. Please try again.": "La connexion a été interrompue. Veuillez réessayer.",
"That code is approved. The bot answers you from now on.": "Ce code est approuvé. Le bot vous répondra désormais."
,
"Could not open that chat.": "Impossible d’ouvrir cette discussion.",
"Could not load earlier messages.": "Impossible de charger les messages précédents.",
"Could not open Home chat.": "Impossible d’ouvrir la discussion d’accueil.",
"Could not start a new chat.": "Impossible de démarrer une nouvelle discussion.",
"Could not queue the follow-up.": "Impossible de mettre le message suivant en attente.",
"Could not cancel the queued follow-up.": "Impossible d’annuler le message suivant en attente.",
"Could not stop that reply.": "Impossible d’arrêter cette réponse.",
"Could not reconnect to the current reply.": "Impossible de rétablir la connexion à la réponse en cours.",
"Could not send the message.": "Impossible d’envoyer le message.",
"Your message is being saved. Try again in a moment.": "Votre message est en cours d’enregistrement. Réessayez dans un instant.",
"Hermes is busy. Try again in a moment.": "Hermes est occupé. Réessayez dans un instant.",
"Could not attach the selected photos.": "Impossible de joindre les photos sélectionnées.",
"Could not take a photo.": "Impossible de prendre une photo.",
"Could not attach the selected files.": "Impossible de joindre les fichiers sélectionnés.",
"One attached file is too large. Keep each file under 5 MB.": "Un fichier joint est trop volumineux. Chaque fichier doit faire moins de 5 Mo.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "Les pièces jointes sont trop volumineuses ensemble. Gardez le total sous 10 Mo par message.",
"Voice recording could not start.": "Impossible de démarrer l’enregistrement vocal.",
"Voice note could not be transcribed.": "Impossible de transcrire la note vocale.",
"Could not stop that delegated task.": "Impossible d’arrêter cette tâche déléguée.",
"This chat could not be loaded. Pull down to try again.": "Impossible de charger cette discussion. Faites glisser vers le bas pour réessayer."
,
"Could not open that page.": "Impossible d’ouvrir cette page.",
"Could not copy that public link.": "Impossible de copier ce lien public.",
"This page is not a private preview link.": "Cette page n’est pas un lien d’aperçu privé.",
"Could not publish that page.": "Impossible de publier cette page.",
"Removed from Pages.": "Retiré des pages.",
"Public link copied.": "Lien public copié.",
"Public link created and copied.": "Lien public créé et copié.",
"Public link created.": "Lien public créé.",
"Ranked Tasks could not be loaded.": "Impossible de charger les tâches prioritaires.",
"Ranked Tasks automations could not be loaded.": "Impossible de charger les automatisations des tâches prioritaires.",
"Ranked Tasks automation could not be changed.": "Impossible de modifier l’automatisation des tâches prioritaires.",
"Ranked Tasks could not be refreshed.": "Impossible d’actualiser les tâches prioritaires.",
"That stored ranking could not be shown again.": "Impossible d’afficher à nouveau ce classement enregistré.",
"Suggestions are temporarily unavailable.": "Les suggestions sont temporairement indisponibles.",
"Draft added to Chat. Edit it before sending.": "Brouillon ajouté à la discussion. Modifiez-le avant de l’envoyer."
,
"Could not save this secure entry. It may have expired.": "Impossible d’enregistrer cette saisie sécurisée. Elle a peut-être expiré.",
"Could not cancel this secure entry. It may have expired.": "Impossible d’annuler cette saisie sécurisée. Elle a peut-être expiré.",
"This secure entry request has expired. Ask Hermes to open a new one.": "Cette demande de saisie sécurisée a expiré. Demandez à Hermes d’en ouvrir une nouvelle.",
"The secure value could not be saved. It was not added to chat.": "La valeur sécurisée n’a pas pu être enregistrée. Elle n’a pas été ajoutée à la discussion.",
"The secure entry request could not be cancelled.": "Impossible d’annuler la demande de saisie sécurisée.",
"{label} was saved securely.": "{label} a été enregistré de façon sécurisée.",
"Camera access is needed to take a photo.": "L’accès à l’appareil photo est nécessaire pour prendre une photo.",
"The voice recording could not be removed.": "Impossible de supprimer l’enregistrement vocal.",
"Voice note could not be read.": "Impossible de lire la note vocale.",
"Check App Store subscriptions before trying again.": "Vérifiez vos abonnements App Store avant de réessayer."
,
"Photos": "Photos",
"Camera": "Appareil photo",
"Files": "Fichiers"
,
"Loading...": "Chargement…",
"Earlier messages": "Messages précédents",
"Delegated work is running": "Le travail délégué est en cours",
"Delegated work is waiting": "Le travail délégué est en attente",
"Open delegated task {name}": "Ouvrir la tâche déléguée {name}",
"Close delegated task {name}": "Fermer la tâche déléguée {name}",
"Stop and close delegated task {name}": "Arrêter et fermer la tâche déléguée {name}",
"Working": "En cours",
"Waiting for you": "En attente de vous",
"{environment} is starting. I will keep checking automatically.": "{environment} démarre. Je continuerai à vérifier automatiquement.",
"Connecting…": "Connexion…",
"Connect workspace": "Connecter l’espace de travail"
,
"Hermes is getting ready": "Hermes se prépare",
"Hermes is typing": "Hermes écrit",
"Reply ready": "Réponse prête",
"You can attach up to {count} files.": "Vous pouvez joindre jusqu’à {count} fichiers.",
"{name} is larger than 5 MB.": "{name} dépasse 5 Mo.",
"Attachments can be up to 10 MB in total.": "Les pièces jointes peuvent atteindre 10 Mo au total."
},
"es": {
  "Hey suggestion": "Sugerencia de Hey",
  "Suggestion": "Sugerencia",
  "Load earlier messages": "Cargar mensajes anteriores",
  "Scroll to latest message": "Ir al último mensaje",
  "Add attachment": "Añadir archivo adjunto",
  "Message": "Mensaje",
  "Suggestions": "Sugerencias",
  "Small, optional ways to get more from your private Hermes workspace.": "Pequeñas opciones para aprovechar más tu espacio privado de Hermes.",
  "Suggestion filters": "Filtros de sugerencias",
  "No suggestions in this filter.": "No hay sugerencias con este filtro.",
  "Pages": "Páginas",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Enlaces a páginas, aplicaciones o herramientas privadas que Hermes guardó para este espacio.",
  "Manage the account and service connections Hermes can use with your approval.": "Gestiona las conexiones de cuentas y servicios que Hermes puede usar con tu permiso.",
  "Dismiss notification": "Cerrar notificación",
  "Confirmation choices": "Opciones de confirmación",
  "Hermes is working": "Hermes está trabajando",
  "Delegated tasks": "Tareas delegadas",
  "Selected files": "Archivos seleccionados",
  "Discuss": "Comentar",
  "Hermes Kanban is not reachable": "Hermes Kanban no está accesible",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "Las tareas solo se muestran cuando proceden de la fuente real de Hermes Kanban.",
  "Accounts": "Cuentas",
  "Prepared workspaces": "Espacios preparados",
  "Audit": "Auditoría",
  "Advanced": "Avanzado",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "Configuración del propietario para acceso a modelos y cuentas de correo, Telegram y WhatsApp conectadas por el usuario.",
  "Dismiss run status": "Cerrar estado de ejecución",
  "Browser results": "Resultados del navegador",
  "Sources": "Fuentes",
  "Steps": "Pasos",
  "Suggested first messages": "Primeros mensajes sugeridos",
  "Used": "Usado",
  "Review cards": "Tarjetas de revisión",
  "Connection setup request": "Solicitud de configuración de conexión",
  "No secret is saved and no provider action is taken by this request.": "Esta solicitud no guarda secretos ni realiza acciones del proveedor.",
  "Review in chat": "Revisar en el chat",
  "Target": "Destino",
  "Action": "Acción",
  "Capability": "Capacidad",
  "Proposed change": "Cambio propuesto",
  "Type": "Tipo",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "Esto guarda tu decisión para la acción almacenada. Si la tarjeta está vinculada a una acción ejecutable, la aprobación habilita esa acción exacta una sola vez."
,
"Queueing follow-up": "Poniendo el siguiente mensaje en cola",
"Follow-up is running": "Procesando el siguiente mensaje",
"Cancelling follow-up": "Cancelando el siguiente mensaje",
"Follow-up cancelled": "Siguiente mensaje cancelado",
"Follow-up could not run": "No se pudo procesar el siguiente mensaje",
"Follow-up queued": "Siguiente mensaje en cola",
"Cancel queued follow-up": "Cancelar el mensaje en cola",
"Dismiss queued follow-up": "Ocultar el mensaje en cola"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "Este servidor privado de Hermes aún no está activo. La transferencia de administración debe completarse o dispensarse antes de poder usar el chat.",
"Please sign in again.": "Vuelve a iniciar sesión.",
"Today's chat limit has been reached.": "Se alcanzó el límite de chat de hoy.",
"Hermes took too long to answer. Please try again.": "Hermes tardó demasiado en responder. Inténtalo de nuevo.",
"Hermes could not finish that reply. Try again from this chat.": "Hermes no pudo terminar esta respuesta. Inténtalo de nuevo desde este chat.",
"AI connection needs attention.": "La conexión de IA necesita atención.",
"The connection dropped. Please try again.": "Se perdió la conexión. Inténtalo de nuevo.",
"That code is approved. The bot answers you from now on.": "El código está aprobado. El bot te responderá a partir de ahora."
,
"Could not open that chat.": "No se pudo abrir ese chat.",
"Could not load earlier messages.": "No se pudieron cargar los mensajes anteriores.",
"Could not open Home chat.": "No se pudo abrir el chat de inicio.",
"Could not start a new chat.": "No se pudo iniciar un nuevo chat.",
"Could not queue the follow-up.": "No se pudo poner en cola el mensaje de seguimiento.",
"Could not cancel the queued follow-up.": "No se pudo cancelar el mensaje de seguimiento en cola.",
"Could not stop that reply.": "No se pudo detener esa respuesta.",
"Could not reconnect to the current reply.": "No se pudo reconectar con la respuesta actual.",
"Could not send the message.": "No se pudo enviar el mensaje.",
"Your message is being saved. Try again in a moment.": "Tu mensaje se está guardando. Inténtalo de nuevo en un momento.",
"Hermes is busy. Try again in a moment.": "Hermes está ocupado. Inténtalo de nuevo en un momento.",
"Could not attach the selected photos.": "No se pudieron adjuntar las fotos seleccionadas.",
"Could not take a photo.": "No se pudo tomar una foto.",
"Could not attach the selected files.": "No se pudieron adjuntar los archivos seleccionados.",
"One attached file is too large. Keep each file under 5 MB.": "Un archivo adjunto es demasiado grande. Cada archivo debe ser menor de 5 MB.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "Los archivos adjuntos son demasiado grandes en conjunto. El total debe ser menor de 10 MB por mensaje.",
"Voice recording could not start.": "No se pudo iniciar la grabación de voz.",
"Voice note could not be transcribed.": "No se pudo transcribir la nota de voz.",
"Could not stop that delegated task.": "No se pudo detener esa tarea delegada.",
"This chat could not be loaded. Pull down to try again.": "No se pudo cargar este chat. Desliza hacia abajo para intentarlo de nuevo."
,
"Could not open that page.": "No se pudo abrir esa página.",
"Could not copy that public link.": "No se pudo copiar ese enlace público.",
"This page is not a private preview link.": "Esta página no es un enlace de vista previa privada.",
"Could not publish that page.": "No se pudo publicar esa página.",
"Removed from Pages.": "Eliminado de Páginas.",
"Public link copied.": "Enlace público copiado.",
"Public link created and copied.": "Enlace público creado y copiado.",
"Public link created.": "Enlace público creado.",
"Ranked Tasks could not be loaded.": "No se pudieron cargar las tareas priorizadas.",
"Ranked Tasks automations could not be loaded.": "No se pudieron cargar las automatizaciones de tareas priorizadas.",
"Ranked Tasks automation could not be changed.": "No se pudo cambiar la automatización de tareas priorizadas.",
"Ranked Tasks could not be refreshed.": "No se pudieron actualizar las tareas priorizadas.",
"That stored ranking could not be shown again.": "No se pudo volver a mostrar esa clasificación guardada.",
"Suggestions are temporarily unavailable.": "Las sugerencias no están disponibles temporalmente.",
"Draft added to Chat. Edit it before sending.": "Borrador añadido al chat. Edítalo antes de enviarlo."
,
"Could not save this secure entry. It may have expired.": "No se pudo guardar esta entrada segura. Puede haber caducado.",
"Could not cancel this secure entry. It may have expired.": "No se pudo cancelar esta entrada segura. Puede haber caducado.",
"This secure entry request has expired. Ask Hermes to open a new one.": "Esta solicitud de entrada segura ha caducado. Pide a Hermes que abra una nueva.",
"The secure value could not be saved. It was not added to chat.": "No se pudo guardar el valor seguro. No se añadió al chat.",
"The secure entry request could not be cancelled.": "No se pudo cancelar la solicitud de entrada segura.",
"{label} was saved securely.": "{label} se guardó de forma segura.",
"Camera access is needed to take a photo.": "Se necesita acceso a la cámara para tomar una foto.",
"The voice recording could not be removed.": "No se pudo eliminar la grabación de voz.",
"Voice note could not be read.": "No se pudo leer la nota de voz.",
"Check App Store subscriptions before trying again.": "Comprueba tus suscripciones del App Store antes de intentarlo de nuevo."
,
"Photos": "Fotos",
"Camera": "Cámara",
"Files": "Archivos"
,
"Loading...": "Cargando…",
"Earlier messages": "Mensajes anteriores",
"Delegated work is running": "El trabajo delegado está en curso",
"Delegated work is waiting": "El trabajo delegado está en espera",
"Open delegated task {name}": "Abrir la tarea delegada {name}",
"Close delegated task {name}": "Cerrar la tarea delegada {name}",
"Stop and close delegated task {name}": "Detener y cerrar la tarea delegada {name}",
"Working": "En curso",
"Waiting for you": "Esperando tu respuesta",
"{environment} is starting. I will keep checking automatically.": "{environment} se está iniciando. Seguiré comprobándolo automáticamente.",
"Connecting…": "Conectando…",
"Connect workspace": "Conectar espacio de trabajo"
,
"Hermes is getting ready": "Hermes se está preparando",
"Hermes is typing": "Hermes está escribiendo",
"Reply ready": "Respuesta lista",
"You can attach up to {count} files.": "Puedes adjuntar hasta {count} archivos.",
"{name} is larger than 5 MB.": "{name} supera los 5 MB.",
"Attachments can be up to 10 MB in total.": "Los archivos adjuntos pueden ocupar hasta 10 MB en total."
},
"it": {
  "Hey suggestion": "Suggerimento Hey",
  "Suggestion": "Suggerimento",
  "Load earlier messages": "Carica messaggi precedenti",
  "Scroll to latest message": "Vai all’ultimo messaggio",
  "Add attachment": "Aggiungi allegato",
  "Message": "Messaggio",
  "Suggestions": "Suggerimenti",
  "Small, optional ways to get more from your private Hermes workspace.": "Piccole opzioni per ottenere di più dal tuo spazio Hermes privato.",
  "Suggestion filters": "Filtri dei suggerimenti",
  "No suggestions in this filter.": "Nessun suggerimento con questo filtro.",
  "Pages": "Pagine",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Link a pagine, app o strumenti privati salvati da Hermes per questo spazio.",
  "Manage the account and service connections Hermes can use with your approval.": "Gestisci le connessioni ad account e servizi che Hermes può usare con il tuo consenso.",
  "Dismiss notification": "Chiudi notifica",
  "Confirmation choices": "Opzioni di conferma",
  "Hermes is working": "Hermes sta lavorando",
  "Delegated tasks": "Attività delegate",
  "Selected files": "File selezionati",
  "Discuss": "Discuti",
  "Hermes Kanban is not reachable": "Hermes Kanban non è raggiungibile",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "Le attività vengono mostrate solo quando provengono dalla fonte reale di Hermes Kanban.",
  "Accounts": "Account",
  "Prepared workspaces": "Spazi preparati",
  "Audit": "Registro di controllo",
  "Advanced": "Avanzate",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "Configurazione del proprietario per l’accesso ai modelli e gli account e-mail, Telegram e WhatsApp collegati dall’utente.",
  "Dismiss run status": "Chiudi stato di esecuzione",
  "Browser results": "Risultati del browser",
  "Sources": "Fonti",
  "Steps": "Passaggi",
  "Suggested first messages": "Primi messaggi suggeriti",
  "Used": "Usato",
  "Review cards": "Schede da verificare",
  "Connection setup request": "Richiesta di configurazione della connessione",
  "No secret is saved and no provider action is taken by this request.": "Questa richiesta non salva segreti né esegue azioni del fornitore.",
  "Review in chat": "Verifica nella chat",
  "Target": "Destinazione",
  "Action": "Azione",
  "Capability": "Funzionalità",
  "Proposed change": "Modifica proposta",
  "Type": "Tipo",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "Salva la tua decisione per l’azione memorizzata. Se la scheda è collegata a un’azione eseguibile, l’approvazione abilita esattamente quell’azione una sola volta."
,
"Queueing follow-up": "Messaggio successivo in accodamento",
"Follow-up is running": "Elaborazione del messaggio successivo",
"Cancelling follow-up": "Annullamento del messaggio successivo",
"Follow-up cancelled": "Messaggio successivo annullato",
"Follow-up could not run": "Impossibile elaborare il messaggio successivo",
"Follow-up queued": "Messaggio successivo in coda",
"Cancel queued follow-up": "Annulla il messaggio in coda",
"Dismiss queued follow-up": "Nascondi il messaggio in coda"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "Questo server Hermes privato non è ancora attivo. Il passaggio amministratore deve essere completato o esentato prima di poter usare la chat.",
"Please sign in again.": "Accedi di nuovo.",
"Today's chat limit has been reached.": "È stato raggiunto il limite di chat di oggi.",
"Hermes took too long to answer. Please try again.": "Hermes ha impiegato troppo tempo a rispondere. Riprova.",
"Hermes could not finish that reply. Try again from this chat.": "Hermes non ha potuto completare questa risposta. Riprova da questa chat.",
"AI connection needs attention.": "La connessione IA richiede attenzione.",
"The connection dropped. Please try again.": "La connessione si è interrotta. Riprova.",
"That code is approved. The bot answers you from now on.": "Il codice è approvato. Il bot ti risponderà d’ora in poi."
,
"Could not open that chat.": "Impossibile aprire questa chat.",
"Could not load earlier messages.": "Impossibile caricare i messaggi precedenti.",
"Could not open Home chat.": "Impossibile aprire la chat Home.",
"Could not start a new chat.": "Impossibile avviare una nuova chat.",
"Could not queue the follow-up.": "Impossibile mettere in coda il messaggio successivo.",
"Could not cancel the queued follow-up.": "Impossibile annullare il messaggio successivo in coda.",
"Could not stop that reply.": "Impossibile interrompere questa risposta.",
"Could not reconnect to the current reply.": "Impossibile riconnettersi alla risposta in corso.",
"Could not send the message.": "Impossibile inviare il messaggio.",
"Your message is being saved. Try again in a moment.": "Il messaggio è in fase di salvataggio. Riprova tra poco.",
"Hermes is busy. Try again in a moment.": "Hermes è occupato. Riprova tra poco.",
"Could not attach the selected photos.": "Impossibile allegare le foto selezionate.",
"Could not take a photo.": "Impossibile scattare una foto.",
"Could not attach the selected files.": "Impossibile allegare i file selezionati.",
"One attached file is too large. Keep each file under 5 MB.": "Un allegato è troppo grande. Ogni file deve essere inferiore a 5 MB.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "Gli allegati sono troppo grandi nel complesso. Il totale deve restare sotto 10 MB per messaggio.",
"Voice recording could not start.": "Impossibile avviare la registrazione vocale.",
"Voice note could not be transcribed.": "Impossibile trascrivere la nota vocale.",
"Could not stop that delegated task.": "Impossibile interrompere questa attività delegata.",
"This chat could not be loaded. Pull down to try again.": "Impossibile caricare questa chat. Scorri verso il basso per riprovare."
,
"Could not open that page.": "Impossibile aprire questa pagina.",
"Could not copy that public link.": "Impossibile copiare questo link pubblico.",
"This page is not a private preview link.": "Questa pagina non è un link di anteprima privata.",
"Could not publish that page.": "Impossibile pubblicare questa pagina.",
"Removed from Pages.": "Rimosso da Pagine.",
"Public link copied.": "Link pubblico copiato.",
"Public link created and copied.": "Link pubblico creato e copiato.",
"Public link created.": "Link pubblico creato.",
"Ranked Tasks could not be loaded.": "Impossibile caricare le attività prioritarie.",
"Ranked Tasks automations could not be loaded.": "Impossibile caricare le automazioni delle attività prioritarie.",
"Ranked Tasks automation could not be changed.": "Impossibile modificare l’automazione delle attività prioritarie.",
"Ranked Tasks could not be refreshed.": "Impossibile aggiornare le attività prioritarie.",
"That stored ranking could not be shown again.": "Impossibile mostrare di nuovo questa classifica salvata.",
"Suggestions are temporarily unavailable.": "I suggerimenti sono temporaneamente non disponibili.",
"Draft added to Chat. Edit it before sending.": "Bozza aggiunta alla chat. Modificala prima di inviarla."
,
"Could not save this secure entry. It may have expired.": "Impossibile salvare questa immissione sicura. Potrebbe essere scaduta.",
"Could not cancel this secure entry. It may have expired.": "Impossibile annullare questa immissione sicura. Potrebbe essere scaduta.",
"This secure entry request has expired. Ask Hermes to open a new one.": "Questa richiesta di immissione sicura è scaduta. Chiedi a Hermes di aprirne una nuova.",
"The secure value could not be saved. It was not added to chat.": "Impossibile salvare il valore sicuro. Non è stato aggiunto alla chat.",
"The secure entry request could not be cancelled.": "Impossibile annullare la richiesta di immissione sicura.",
"{label} was saved securely.": "{label} è stato salvato in modo sicuro.",
"Camera access is needed to take a photo.": "Per scattare una foto è necessario l’accesso alla fotocamera.",
"The voice recording could not be removed.": "Impossibile rimuovere la registrazione vocale.",
"Voice note could not be read.": "Impossibile leggere la nota vocale.",
"Check App Store subscriptions before trying again.": "Controlla gli abbonamenti App Store prima di riprovare."
,
"Photos": "Foto",
"Camera": "Fotocamera",
"Files": "File"
,
"Loading...": "Caricamento…",
"Earlier messages": "Messaggi precedenti",
"Delegated work is running": "Il lavoro delegato è in corso",
"Delegated work is waiting": "Il lavoro delegato è in attesa",
"Open delegated task {name}": "Apri l’attività delegata {name}",
"Close delegated task {name}": "Chiudi l’attività delegata {name}",
"Stop and close delegated task {name}": "Interrompi e chiudi l’attività delegata {name}",
"Working": "In corso",
"Waiting for you": "In attesa di te",
"{environment} is starting. I will keep checking automatically.": "{environment} si sta avviando. Continuerò a controllare automaticamente.",
"Connecting…": "Connessione…",
"Connect workspace": "Collega lo spazio di lavoro"
,
"Hermes is getting ready": "Hermes si sta preparando",
"Hermes is typing": "Hermes sta scrivendo",
"Reply ready": "Risposta pronta",
"You can attach up to {count} files.": "Puoi allegare fino a {count} file.",
"{name} is larger than 5 MB.": "{name} supera i 5 MB.",
"Attachments can be up to 10 MB in total.": "Gli allegati possono raggiungere 10 MB in totale."
},
"pt-BR": {
  "Hey suggestion": "Sugestão do Hey",
  "Suggestion": "Sugestão",
  "Load earlier messages": "Carregar mensagens anteriores",
  "Scroll to latest message": "Ir para a mensagem mais recente",
  "Add attachment": "Adicionar anexo",
  "Message": "Mensagem",
  "Suggestions": "Sugestões",
  "Small, optional ways to get more from your private Hermes workspace.": "Pequenas opções para aproveitar mais seu espaço privado do Hermes.",
  "Suggestion filters": "Filtros de sugestões",
  "No suggestions in this filter.": "Nenhuma sugestão neste filtro.",
  "Pages": "Páginas",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Links para páginas, aplicativos ou ferramentas privadas que o Hermes salvou para este espaço.",
  "Manage the account and service connections Hermes can use with your approval.": "Gerencie conexões de contas e serviços que o Hermes pode usar com sua aprovação.",
  "Dismiss notification": "Fechar notificação",
  "Confirmation choices": "Opções de confirmação",
  "Hermes is working": "Hermes está trabalhando",
  "Delegated tasks": "Tarefas delegadas",
  "Selected files": "Arquivos selecionados",
  "Discuss": "Conversar",
  "Hermes Kanban is not reachable": "O Hermes Kanban está inacessível",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "As tarefas só são mostradas quando vêm da fonte real do Hermes Kanban.",
  "Accounts": "Contas",
  "Prepared workspaces": "Espaços preparados",
  "Audit": "Auditoria",
  "Advanced": "Avançado",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "Configuração do proprietário para acesso a modelos e contas de e-mail, Telegram e WhatsApp conectadas pelo usuário.",
  "Dismiss run status": "Fechar estado da execução",
  "Browser results": "Resultados do navegador",
  "Sources": "Fontes",
  "Steps": "Etapas",
  "Suggested first messages": "Primeiras mensagens sugeridas",
  "Used": "Usado",
  "Review cards": "Cartões de revisão",
  "Connection setup request": "Solicitação de configuração de conexão",
  "No secret is saved and no provider action is taken by this request.": "Esta solicitação não salva segredos nem executa ações do provedor.",
  "Review in chat": "Revisar no chat",
  "Target": "Destino",
  "Action": "Ação",
  "Capability": "Recurso",
  "Proposed change": "Alteração proposta",
  "Type": "Tipo",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "Isso salva sua decisão para a ação armazenada. Se o cartão estiver ligado a uma ação executável, a aprovação libera exatamente essa ação uma única vez."
,
"Queueing follow-up": "Colocando a próxima mensagem na fila",
"Follow-up is running": "Processando a próxima mensagem",
"Cancelling follow-up": "Cancelando a próxima mensagem",
"Follow-up cancelled": "Próxima mensagem cancelada",
"Follow-up could not run": "Não foi possível processar a próxima mensagem",
"Follow-up queued": "Próxima mensagem na fila",
"Cancel queued follow-up": "Cancelar a mensagem na fila",
"Dismiss queued follow-up": "Ocultar a mensagem na fila"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "Este servidor privado do Hermes ainda não está ativo. A transferência de administração precisa ser concluída ou dispensada antes de usar o chat.",
"Please sign in again.": "Entre novamente.",
"Today's chat limit has been reached.": "O limite de chat de hoje foi atingido.",
"Hermes took too long to answer. Please try again.": "O Hermes demorou demais para responder. Tente novamente.",
"Hermes could not finish that reply. Try again from this chat.": "O Hermes não conseguiu concluir esta resposta. Tente novamente neste chat.",
"AI connection needs attention.": "A conexão de IA precisa de atenção.",
"The connection dropped. Please try again.": "A conexão caiu. Tente novamente.",
"That code is approved. The bot answers you from now on.": "O código foi aprovado. O bot responderá a você a partir de agora."
,
"Could not open that chat.": "Não foi possível abrir esse chat.",
"Could not load earlier messages.": "Não foi possível carregar as mensagens anteriores.",
"Could not open Home chat.": "Não foi possível abrir o chat inicial.",
"Could not start a new chat.": "Não foi possível iniciar um novo chat.",
"Could not queue the follow-up.": "Não foi possível colocar a mensagem seguinte na fila.",
"Could not cancel the queued follow-up.": "Não foi possível cancelar a mensagem seguinte na fila.",
"Could not stop that reply.": "Não foi possível interromper essa resposta.",
"Could not reconnect to the current reply.": "Não foi possível reconectar à resposta atual.",
"Could not send the message.": "Não foi possível enviar a mensagem.",
"Your message is being saved. Try again in a moment.": "Sua mensagem está sendo salva. Tente novamente em instantes.",
"Hermes is busy. Try again in a moment.": "O Hermes está ocupado. Tente novamente em instantes.",
"Could not attach the selected photos.": "Não foi possível anexar as fotos selecionadas.",
"Could not take a photo.": "Não foi possível tirar uma foto.",
"Could not attach the selected files.": "Não foi possível anexar os arquivos selecionados.",
"One attached file is too large. Keep each file under 5 MB.": "Um arquivo anexado é grande demais. Cada arquivo deve ter menos de 5 MB.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "Os anexos são grandes demais juntos. O total deve ficar abaixo de 10 MB por mensagem.",
"Voice recording could not start.": "Não foi possível iniciar a gravação de voz.",
"Voice note could not be transcribed.": "Não foi possível transcrever a nota de voz.",
"Could not stop that delegated task.": "Não foi possível interromper essa tarefa delegada.",
"This chat could not be loaded. Pull down to try again.": "Não foi possível carregar este chat. Puxe para baixo para tentar novamente."
,
"Could not open that page.": "Não foi possível abrir essa página.",
"Could not copy that public link.": "Não foi possível copiar esse link público.",
"This page is not a private preview link.": "Esta página não é um link de prévia privada.",
"Could not publish that page.": "Não foi possível publicar essa página.",
"Removed from Pages.": "Removido de Páginas.",
"Public link copied.": "Link público copiado.",
"Public link created and copied.": "Link público criado e copiado.",
"Public link created.": "Link público criado.",
"Ranked Tasks could not be loaded.": "Não foi possível carregar as tarefas priorizadas.",
"Ranked Tasks automations could not be loaded.": "Não foi possível carregar as automações de tarefas priorizadas.",
"Ranked Tasks automation could not be changed.": "Não foi possível alterar a automação de tarefas priorizadas.",
"Ranked Tasks could not be refreshed.": "Não foi possível atualizar as tarefas priorizadas.",
"That stored ranking could not be shown again.": "Não foi possível mostrar novamente essa classificação salva.",
"Suggestions are temporarily unavailable.": "As sugestões estão temporariamente indisponíveis.",
"Draft added to Chat. Edit it before sending.": "Rascunho adicionado ao chat. Edite antes de enviar."
,
"Could not save this secure entry. It may have expired.": "Não foi possível salvar esta entrada segura. Ela pode ter expirado.",
"Could not cancel this secure entry. It may have expired.": "Não foi possível cancelar esta entrada segura. Ela pode ter expirado.",
"This secure entry request has expired. Ask Hermes to open a new one.": "Esta solicitação de entrada segura expirou. Peça ao Hermes para abrir uma nova.",
"The secure value could not be saved. It was not added to chat.": "Não foi possível salvar o valor seguro. Ele não foi adicionado ao chat.",
"The secure entry request could not be cancelled.": "Não foi possível cancelar a solicitação de entrada segura.",
"{label} was saved securely.": "{label} foi salvo com segurança.",
"Camera access is needed to take a photo.": "É necessário acesso à câmera para tirar uma foto.",
"The voice recording could not be removed.": "Não foi possível remover a gravação de voz.",
"Voice note could not be read.": "Não foi possível ler a nota de voz.",
"Check App Store subscriptions before trying again.": "Verifique suas assinaturas da App Store antes de tentar novamente."
,
"Photos": "Fotos",
"Camera": "Câmera",
"Files": "Arquivos"
,
"Loading...": "Carregando…",
"Earlier messages": "Mensagens anteriores",
"Delegated work is running": "O trabalho delegado está em andamento",
"Delegated work is waiting": "O trabalho delegado está aguardando",
"Open delegated task {name}": "Abrir tarefa delegada {name}",
"Close delegated task {name}": "Fechar tarefa delegada {name}",
"Stop and close delegated task {name}": "Parar e fechar tarefa delegada {name}",
"Working": "Em andamento",
"Waiting for you": "Aguardando você",
"{environment} is starting. I will keep checking automatically.": "{environment} está iniciando. Continuarei verificando automaticamente.",
"Connecting…": "Conectando…",
"Connect workspace": "Conectar espaço de trabalho"
,
"Hermes is getting ready": "Hermes está se preparando",
"Hermes is typing": "Hermes está escrevendo",
"Reply ready": "Resposta pronta",
"You can attach up to {count} files.": "Você pode anexar até {count} arquivos.",
"{name} is larger than 5 MB.": "{name} é maior que 5 MB.",
"Attachments can be up to 10 MB in total.": "Os anexos podem ter até 10 MB no total."
},
"ja": {
  "Hey suggestion": "Heyの提案",
  "Suggestion": "提案",
  "Load earlier messages": "以前のメッセージを読み込む",
  "Scroll to latest message": "最新のメッセージに移動",
  "Add attachment": "添付ファイルを追加",
  "Message": "メッセージ",
  "Suggestions": "提案",
  "Small, optional ways to get more from your private Hermes workspace.": "プライベートなHermesワークスペースをさらに活用するための、任意の小さな提案です。",
  "Suggestion filters": "提案の絞り込み",
  "No suggestions in this filter.": "この条件の提案はありません。",
  "Pages": "ページ",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Hermesがこのワークスペースに保存したプライベートなページ、アプリ、ツールへのリンクです。",
  "Manage the account and service connections Hermes can use with your approval.": "Hermesがあなたの許可を得て使用するアカウントやサービスの接続を管理します。",
  "Dismiss notification": "通知を閉じる",
  "Confirmation choices": "確認の選択肢",
  "Hermes is working": "Hermesが作業中",
  "Delegated tasks": "委任したタスク",
  "Selected files": "選択したファイル",
  "Discuss": "相談する",
  "Hermes Kanban is not reachable": "Hermes Kanbanに接続できません",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "実際のHermes Kanbanから取得したタスクのみを表示します。",
  "Accounts": "アカウント",
  "Prepared workspaces": "準備済みワークスペース",
  "Audit": "監査",
  "Advanced": "詳細設定",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "モデルへのアクセスと、ユーザーが接続するメール、Telegram、WhatsAppの所有者向け設定です。",
  "Dismiss run status": "実行状態を閉じる",
  "Browser results": "ブラウザーの結果",
  "Sources": "情報源",
  "Steps": "手順",
  "Suggested first messages": "最初のメッセージの提案",
  "Used": "使用済み",
  "Review cards": "確認カード",
  "Connection setup request": "接続設定の依頼",
  "No secret is saved and no provider action is taken by this request.": "この依頼で秘密情報を保存したり、プロバイダー側の操作を行ったりすることはありません。",
  "Review in chat": "チャットで確認",
  "Target": "対象",
  "Action": "操作",
  "Capability": "機能",
  "Proposed change": "変更案",
  "Type": "種類",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "保存された操作に対するあなたの判断を記録します。カードが実行可能な操作に結び付いている場合、承認するとその操作だけを一度実行できるようになります。"
,
"Queueing follow-up": "次のメッセージを待機列に追加中",
"Follow-up is running": "次のメッセージを処理中",
"Cancelling follow-up": "次のメッセージをキャンセル中",
"Follow-up cancelled": "次のメッセージをキャンセルしました",
"Follow-up could not run": "次のメッセージを処理できませんでした",
"Follow-up queued": "次のメッセージは待機中",
"Cancel queued follow-up": "待機中のメッセージをキャンセル",
"Dismiss queued follow-up": "待機中のメッセージを非表示"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "このプライベートHermesサーバーはまだ有効ではありません。チャットを開始するには、管理者の引き継ぎを完了するか免除する必要があります。",
"Please sign in again.": "もう一度ログインしてください。",
"Today's chat limit has been reached.": "本日のチャット上限に達しました。",
"Hermes took too long to answer. Please try again.": "Hermesの応答に時間がかかりすぎました。再試行してください。",
"Hermes could not finish that reply. Try again from this chat.": "Hermesはこの応答を完了できませんでした。このチャットから再試行してください。",
"AI connection needs attention.": "AI接続の確認が必要です。",
"The connection dropped. Please try again.": "接続が切れました。再試行してください。",
"That code is approved. The bot answers you from now on.": "コードが承認されました。これからボットが応答します。"
,
"Could not open that chat.": "このチャットを開けませんでした。",
"Could not load earlier messages.": "以前のメッセージを読み込めませんでした。",
"Could not open Home chat.": "ホームチャットを開けませんでした。",
"Could not start a new chat.": "新しいチャットを開始できませんでした。",
"Could not queue the follow-up.": "追加メッセージをキューに追加できませんでした。",
"Could not cancel the queued follow-up.": "待機中の追加メッセージをキャンセルできませんでした。",
"Could not stop that reply.": "この応答を停止できませんでした。",
"Could not reconnect to the current reply.": "現在の応答に再接続できませんでした。",
"Could not send the message.": "メッセージを送信できませんでした。",
"Your message is being saved. Try again in a moment.": "メッセージを保存しています。しばらくしてから再試行してください。",
"Hermes is busy. Try again in a moment.": "Hermesは処理中です。しばらくしてから再試行してください。",
"Could not attach the selected photos.": "選択した写真を添付できませんでした。",
"Could not take a photo.": "写真を撮影できませんでした。",
"Could not attach the selected files.": "選択したファイルを添付できませんでした。",
"One attached file is too large. Keep each file under 5 MB.": "添付ファイルが大きすぎます。各ファイルを5 MB未満にしてください。",
"Those attachments are too large together. Keep one message under 10 MB of files.": "添付ファイルの合計サイズが大きすぎます。1つのメッセージにつき合計10 MB未満にしてください。",
"Voice recording could not start.": "音声録音を開始できませんでした。",
"Voice note could not be transcribed.": "音声メモを文字に起こせませんでした。",
"Could not stop that delegated task.": "この委任タスクを停止できませんでした。",
"This chat could not be loaded. Pull down to try again.": "このチャットを読み込めませんでした。下に引いて再試行してください。"
,
"Could not open that page.": "このページを開けませんでした。",
"Could not copy that public link.": "この公開リンクをコピーできませんでした。",
"This page is not a private preview link.": "このページは非公開プレビューリンクではありません。",
"Could not publish that page.": "このページを公開できませんでした。",
"Removed from Pages.": "ページから削除しました。",
"Public link copied.": "公開リンクをコピーしました。",
"Public link created and copied.": "公開リンクを作成してコピーしました。",
"Public link created.": "公開リンクを作成しました。",
"Ranked Tasks could not be loaded.": "優先タスクを読み込めませんでした。",
"Ranked Tasks automations could not be loaded.": "優先タスクの自動化を読み込めませんでした。",
"Ranked Tasks automation could not be changed.": "優先タスクの自動化を変更できませんでした。",
"Ranked Tasks could not be refreshed.": "優先タスクを更新できませんでした。",
"That stored ranking could not be shown again.": "この保存済みランキングを再表示できませんでした。",
"Suggestions are temporarily unavailable.": "提案を一時的に利用できません。",
"Draft added to Chat. Edit it before sending.": "下書きをチャットに追加しました。送信前に編集してください。"
,
"Could not save this secure entry. It may have expired.": "この安全な入力を保存できませんでした。有効期限が切れた可能性があります。",
"Could not cancel this secure entry. It may have expired.": "この安全な入力をキャンセルできませんでした。有効期限が切れた可能性があります。",
"This secure entry request has expired. Ask Hermes to open a new one.": "この安全な入力リクエストは期限切れです。Hermesに新しいものを開くよう依頼してください。",
"The secure value could not be saved. It was not added to chat.": "安全な値を保存できませんでした。チャットには追加されていません。",
"The secure entry request could not be cancelled.": "安全な入力リクエストをキャンセルできませんでした。",
"{label} was saved securely.": "{label}を安全に保存しました。",
"Camera access is needed to take a photo.": "写真を撮るにはカメラへのアクセスが必要です。",
"The voice recording could not be removed.": "音声録音を削除できませんでした。",
"Voice note could not be read.": "音声メモを読み取れませんでした。",
"Check App Store subscriptions before trying again.": "再試行する前にApp Storeのサブスクリプションを確認してください。"
,
"Photos": "写真",
"Camera": "カメラ",
"Files": "ファイル"
,
"Loading...": "読み込み中…",
"Earlier messages": "以前のメッセージ",
"Delegated work is running": "委任した作業は実行中です",
"Delegated work is waiting": "委任した作業は待機中です",
"Open delegated task {name}": "委任したタスク{name}を開く",
"Close delegated task {name}": "委任したタスク{name}を閉じる",
"Stop and close delegated task {name}": "委任したタスク{name}を停止して閉じる",
"Working": "作業中",
"Waiting for you": "あなたの対応待ち",
"{environment} is starting. I will keep checking automatically.": "{environment}を起動しています。自動で確認を続けます。",
"Connecting…": "接続中…",
"Connect workspace": "ワークスペースを接続"
,
"Hermes is getting ready": "Hermesが準備中",
"Hermes is typing": "Hermesが入力中",
"Reply ready": "返信の準備ができました",
"You can attach up to {count} files.": "最大{count}個のファイルを添付できます。",
"{name} is larger than 5 MB.": "{name}は5 MBを超えています。",
"Attachments can be up to 10 MB in total.": "添付ファイルの合計サイズは10 MBまでです。"
},
"ko": {
  "Hey suggestion": "Hey 제안",
  "Suggestion": "제안",
  "Load earlier messages": "이전 메시지 불러오기",
  "Scroll to latest message": "최신 메시지로 이동",
  "Add attachment": "첨부 파일 추가",
  "Message": "메시지",
  "Suggestions": "제안",
  "Small, optional ways to get more from your private Hermes workspace.": "비공개 Hermes 워크스페이스를 더 활용할 수 있는 작은 선택 사항입니다.",
  "Suggestion filters": "제안 필터",
  "No suggestions in this filter.": "이 필터에 해당하는 제안이 없습니다.",
  "Pages": "페이지",
  "Links to private pages, apps, or tools Hermes has saved for this workspace.": "Hermes가 이 워크스페이스에 저장한 비공개 페이지, 앱 또는 도구 링크입니다.",
  "Manage the account and service connections Hermes can use with your approval.": "Hermes가 사용자의 승인으로 사용할 계정 및 서비스 연결을 관리합니다.",
  "Dismiss notification": "알림 닫기",
  "Confirmation choices": "확인 선택지",
  "Hermes is working": "Hermes 작업 중",
  "Delegated tasks": "위임된 작업",
  "Selected files": "선택한 파일",
  "Discuss": "논의하기",
  "Hermes Kanban is not reachable": "Hermes Kanban에 연결할 수 없습니다",
  "Tasks are only shown when they come from the real Hermes Kanban source.": "실제 Hermes Kanban에서 가져온 작업만 표시합니다.",
  "Accounts": "계정",
  "Prepared workspaces": "준비된 워크스페이스",
  "Audit": "감사 기록",
  "Advanced": "고급",
  "Owner setup for model access and user-connected email, Telegram, and WhatsApp.": "모델 접근과 사용자가 연결한 이메일, Telegram, WhatsApp의 소유자 설정입니다.",
  "Dismiss run status": "실행 상태 닫기",
  "Browser results": "브라우저 결과",
  "Sources": "출처",
  "Steps": "단계",
  "Suggested first messages": "첫 메시지 제안",
  "Used": "사용됨",
  "Review cards": "검토 카드",
  "Connection setup request": "연결 설정 요청",
  "No secret is saved and no provider action is taken by this request.": "이 요청은 비밀 정보를 저장하거나 제공업체 작업을 실행하지 않습니다.",
  "Review in chat": "채팅에서 검토",
  "Target": "대상",
  "Action": "작업",
  "Capability": "기능",
  "Proposed change": "제안된 변경",
  "Type": "유형",
  "This saves your decision for the stored action. If the card is tied to an executable action, approval unlocks that exact action once.": "저장된 작업에 대한 사용자의 결정을 기록합니다. 카드가 실행 가능한 작업에 연결되어 있으면 승인 시 그 작업만 한 번 실행할 수 있게 됩니다."
,
"Queueing follow-up": "다음 메시지를 대기열에 추가하는 중",
"Follow-up is running": "다음 메시지 처리 중",
"Cancelling follow-up": "다음 메시지 취소 중",
"Follow-up cancelled": "다음 메시지가 취소됨",
"Follow-up could not run": "다음 메시지를 처리하지 못했습니다",
"Follow-up queued": "다음 메시지 대기 중",
"Cancel queued follow-up": "대기 중인 메시지 취소",
"Dismiss queued follow-up": "대기 중인 메시지 숨기기"
,
"This private Hermes server is not active yet. Admin handover needs to be completed or waived before chat can run.": "이 비공개 Hermes 서버는 아직 활성화되지 않았습니다. 채팅을 시작하려면 관리자 인계를 완료하거나 면제해야 합니다.",
"Please sign in again.": "다시 로그인하세요.",
"Today's chat limit has been reached.": "오늘의 채팅 한도에 도달했습니다.",
"Hermes took too long to answer. Please try again.": "Hermes가 응답하는 데 너무 오래 걸렸습니다. 다시 시도하세요.",
"Hermes could not finish that reply. Try again from this chat.": "Hermes가 이 응답을 완료하지 못했습니다. 이 채팅에서 다시 시도하세요.",
"AI connection needs attention.": "AI 연결을 확인해야 합니다.",
"The connection dropped. Please try again.": "연결이 끊겼습니다. 다시 시도하세요.",
"That code is approved. The bot answers you from now on.": "코드가 승인되었습니다. 이제 봇이 응답합니다."
,
"Could not open that chat.": "이 채팅을 열지 못했습니다.",
"Could not load earlier messages.": "이전 메시지를 불러오지 못했습니다.",
"Could not open Home chat.": "홈 채팅을 열지 못했습니다.",
"Could not start a new chat.": "새 채팅을 시작하지 못했습니다.",
"Could not queue the follow-up.": "후속 메시지를 대기열에 추가하지 못했습니다.",
"Could not cancel the queued follow-up.": "대기 중인 후속 메시지를 취소하지 못했습니다.",
"Could not stop that reply.": "이 응답을 중지하지 못했습니다.",
"Could not reconnect to the current reply.": "현재 응답에 다시 연결하지 못했습니다.",
"Could not send the message.": "메시지를 보내지 못했습니다.",
"Your message is being saved. Try again in a moment.": "메시지를 저장하고 있습니다. 잠시 후 다시 시도하세요.",
"Hermes is busy. Try again in a moment.": "Hermes가 처리 중입니다. 잠시 후 다시 시도하세요.",
"Could not attach the selected photos.": "선택한 사진을 첨부하지 못했습니다.",
"Could not take a photo.": "사진을 촬영하지 못했습니다.",
"Could not attach the selected files.": "선택한 파일을 첨부하지 못했습니다.",
"One attached file is too large. Keep each file under 5 MB.": "첨부 파일 하나가 너무 큽니다. 각 파일은 5 MB 미만이어야 합니다.",
"Those attachments are too large together. Keep one message under 10 MB of files.": "첨부 파일의 합계가 너무 큽니다. 메시지당 파일 합계를 10 MB 미만으로 유지하세요.",
"Voice recording could not start.": "음성 녹음을 시작하지 못했습니다.",
"Voice note could not be transcribed.": "음성 메모를 텍스트로 변환하지 못했습니다.",
"Could not stop that delegated task.": "이 위임된 작업을 중지하지 못했습니다.",
"This chat could not be loaded. Pull down to try again.": "이 채팅을 불러오지 못했습니다. 아래로 당겨 다시 시도하세요."
,
"Could not open that page.": "이 페이지를 열지 못했습니다.",
"Could not copy that public link.": "이 공개 링크를 복사하지 못했습니다.",
"This page is not a private preview link.": "이 페이지는 비공개 미리보기 링크가 아닙니다.",
"Could not publish that page.": "이 페이지를 게시하지 못했습니다.",
"Removed from Pages.": "페이지에서 제거했습니다.",
"Public link copied.": "공개 링크를 복사했습니다.",
"Public link created and copied.": "공개 링크를 만들고 복사했습니다.",
"Public link created.": "공개 링크를 만들었습니다.",
"Ranked Tasks could not be loaded.": "우선순위 작업을 불러오지 못했습니다.",
"Ranked Tasks automations could not be loaded.": "우선순위 작업 자동화를 불러오지 못했습니다.",
"Ranked Tasks automation could not be changed.": "우선순위 작업 자동화를 변경하지 못했습니다.",
"Ranked Tasks could not be refreshed.": "우선순위 작업을 새로 고치지 못했습니다.",
"That stored ranking could not be shown again.": "저장된 순위를 다시 표시하지 못했습니다.",
"Suggestions are temporarily unavailable.": "제안을 일시적으로 사용할 수 없습니다.",
"Draft added to Chat. Edit it before sending.": "초안을 채팅에 추가했습니다. 보내기 전에 수정하세요."
,
"Could not save this secure entry. It may have expired.": "이 보안 입력을 저장하지 못했습니다. 만료되었을 수 있습니다.",
"Could not cancel this secure entry. It may have expired.": "이 보안 입력을 취소하지 못했습니다. 만료되었을 수 있습니다.",
"This secure entry request has expired. Ask Hermes to open a new one.": "이 보안 입력 요청이 만료되었습니다. Hermes에게 새 요청을 열어 달라고 하세요.",
"The secure value could not be saved. It was not added to chat.": "보안 값을 저장하지 못했습니다. 채팅에 추가되지 않았습니다.",
"The secure entry request could not be cancelled.": "보안 입력 요청을 취소하지 못했습니다.",
"{label} was saved securely.": "{label}을(를) 안전하게 저장했습니다.",
"Camera access is needed to take a photo.": "사진을 촬영하려면 카메라 접근 권한이 필요합니다.",
"The voice recording could not be removed.": "음성 녹음을 제거하지 못했습니다.",
"Voice note could not be read.": "음성 메모를 읽지 못했습니다.",
"Check App Store subscriptions before trying again.": "다시 시도하기 전에 App Store 구독을 확인하세요."
,
"Photos": "사진",
"Camera": "카메라",
"Files": "파일"
,
"Loading...": "불러오는 중…",
"Earlier messages": "이전 메시지",
"Delegated work is running": "위임한 작업이 실행 중입니다",
"Delegated work is waiting": "위임한 작업이 대기 중입니다",
"Open delegated task {name}": "위임한 작업 {name} 열기",
"Close delegated task {name}": "위임한 작업 {name} 닫기",
"Stop and close delegated task {name}": "위임한 작업 {name} 중지 후 닫기",
"Working": "작업 중",
"Waiting for you": "사용자 응답 대기 중",
"{environment} is starting. I will keep checking automatically.": "{environment} 시작 중입니다. 자동으로 계속 확인하겠습니다.",
"Connecting…": "연결 중…",
"Connect workspace": "워크스페이스 연결"
,
"Hermes is getting ready": "Hermes 준비 중",
"Hermes is typing": "Hermes 입력 중",
"Reply ready": "답변 준비됨",
"You can attach up to {count} files.": "최대 {count}개의 파일을 첨부할 수 있습니다.",
"{name} is larger than 5 MB.": "{name}의 크기가 5 MB를 초과합니다.",
"Attachments can be up to 10 MB in total.": "첨부 파일의 총 크기는 최대 10 MB입니다."
}
};
export function interactionUiCopy(locale: AppLocale) {
  const copy = catalog[locale];
  return {
    ...copy,
    "Could not load Ranked Tasks automations.": locale === "en" ? "Could not load Ranked Tasks automations." : copy["Ranked Tasks automations could not be loaded."],
    "Older messages could not be loaded.": locale === "en" ? "Older messages could not be loaded." : copy["Could not load earlier messages."],
    "Home chat could not be loaded.": locale === "en" ? "Home chat could not be loaded." : copy["Could not open Home chat."],
    "New chat could not be created.": locale === "en" ? "New chat could not be created." : copy["Could not start a new chat."],
    "That reply could not be stopped.": locale === "en" ? "That reply could not be stopped." : copy["Could not stop that reply."],
    "That follow-up could not be queued.": locale === "en" ? "That follow-up could not be queued." : copy["Could not queue the follow-up."],
    "Chat could not be loaded.": locale === "en" ? "Chat could not be loaded." : copy["Could not open that chat."],
  };
}
