/**
 * Die von Justus entschiedenen Gedächtnis-Werte, an einer Stelle.
 * MVP-SOLL.md, Abschnitt „Die Gedächtnis-Konfiguration".
 * Wer einen Wert ändert, erhöht MEMORY_CONFIG_VERSION und trägt die alte
 * Form in KNOWN_GENERATED_SHAPES nach, sonst zieht der Bestand nicht nach.
 */
export const MEMORY_CONFIG_VERSION = 2;

export const HONCHO_CONTEXT_TOKENS = 1200;

export type HonchoConfigInput = {
  enabled: boolean;
  baseUrl: string;
  workspace: string;
  peerName: string | null;
  apiKey?: string;
};

export function buildHonchoConfig(input: HonchoConfigInput): Record<string, unknown> {
  const config: Record<string, unknown> = {
    memoryConfigVersion: MEMORY_CONFIG_VERSION,
    enabled: input.enabled,
    baseUrl: input.baseUrl,
    workspace: input.workspace,
    recallMode: "context",
    contextTokens: input.enabled ? HONCHO_CONTEXT_TOKENS : 0,
    contextCadence: 1,
    dialecticCadence: 5,
    dialecticDepth: 1,
    dialecticReasoningLevel: "low",
    dialecticDynamic: false,
    reasoningHeuristic: false,
    reasoningLevelCap: "low",
    pinUserPeer: true,
  };
  if (input.peerName) config.peerName = input.peerName;
  if (input.apiKey) config.api_key = input.apiKey;
  return config;
}

/** Die Schlüsselmengen, die frühere Fassungen erzeugt haben. */
const KNOWN_GENERATED_SHAPES: string[][] = [
  ["enabled", "baseUrl", "workspace", "recallMode", "contextTokens", "contextCadence", "dialecticCadence", "dialecticDepth"],
  ["enabled", "baseUrl", "workspace", "recallMode", "contextTokens", "contextCadence", "dialecticCadence", "dialecticDepth", "api_key"],
];

/** Die beiden Schlüssel, die buildHonchoConfig nur bedingt setzt. */
const OPTIONAL_GENERATED_KEYS = ["peerName", "api_key"];

/** Die Pflicht-Schlüsselmenge, die buildHonchoConfig für die aktuelle Version immer setzt. */
function currentGeneratedMandatoryKeys(): string[] {
  return Object.keys(
    buildHonchoConfig({ enabled: false, baseUrl: "", workspace: "", peerName: null }),
  );
}

/**
 * "Repairable" means "this file is ours" (generated by us, at or below our own
 * version), not "this file is current." A version at or below MEMORY_CONFIG_VERSION
 * is still ours, so the caller keeps resyncing it — its own `existing !== desired`
 * check is what decides whether that resync is actually needed. A version above
 * MEMORY_CONFIG_VERSION belongs to a newer writer; we never downgrade that file.
 *
 * A version number alone only says the file claims to be ours; it says nothing
 * about the content. At the current version we also compare the file's key set
 * against what buildHonchoConfig actually produces for that version, so a
 * hand-added or hand-removed key is caught even though the version matches.
 * `peerName` and `api_key` are optional in the generated shape (absent when no
 * account id / api key is known), so their absence alone must not fail the check.
 */
export function isRepairableHonchoConfig(parsed: unknown): boolean {
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return false;
  const keys = Object.keys(parsed as Record<string, unknown>);
  if (keys.length === 0) return true;
  const version = (parsed as Record<string, unknown>).memoryConfigVersion;
  if (typeof version === "number") {
    if (version > MEMORY_CONFIG_VERSION) return false;
    if (version < MEMORY_CONFIG_VERSION) return true;
    const mandatory = currentGeneratedMandatoryKeys();
    const allowed = new Set([...mandatory, ...OPTIONAL_GENERATED_KEYS]);
    if (!keys.every((key) => allowed.has(key))) return false;
    return mandatory.every((key) => keys.includes(key));
  }
  return KNOWN_GENERATED_SHAPES.some(
    (shape) => shape.length === keys.length && shape.every((key) => keys.includes(key)),
  );
}
