import type { AppLocale } from "./types";
const en = {
  "workspaceTitle": "Workspace status",
  "workspaceDescription": "Current server-authoritative account, plan, AI, server, security, and capability state.",
  "account": "Account",
  "plan": "Plan",
  "aiModel": "AI model",
  "server": "Server",
  "security": "Security",
  "capabilities": "Capabilities",
  "notifications": "Notifications",
  "on": "On",
  "off": "Off",
  "notConnected": "Not connected",
  "devices": "Registered devices: {count}",
  "enableHint": "Enable this device for reply alerts",
  "support": "Support",
  "closed": "Closed",
  "observation": "Last server observation {date}",
  "noObservation": "No current server observation",
  "pushTitle": "Push notifications",
  "pushDescription": "Get a device notification when Hermes finishes or needs attention.",
  "reconnect": "Reconnect",
  "enable": "Enable",
  "sendTest": "Send test",
  "checking": "Checking...",
  "checkAgain": "Check again",
  "signOut": "Sign out",
  "connectorTitle": "Connector status",
  "connectorDescription": "Owner-only readout of saved connector state. Member workspace pages do not show setup forms.",
  "ownerOnly": "owner only",
  "savedSecrets": "secrets saved",
  "connectorEmpty": "No connector records are available for this workspace.",
  "chat": "Chat",
  "provider": "Provider",
  "runsToday": "Runs today",
  "dailyLimit": "Daily limit",
  "lastMessage": "Last message",
  "noneYet": "none yet",
  "last": "Last",
  "you": "you",
  "openChat": "Open chat",
  "checkChat": "Check chat",
  "ready": "ready",
  "settingUp": "setting up",
  "includedModels": "Included models",
  "unavailable": "Status unavailable",
  "routeReady": "Current server and AI-provider evidence confirm this route is ready.",
  "routeUnconfirmed": "Current server or AI-provider readiness could not be confirmed.",
  "runtime": "Runtime",
  "workspaceAccess": "Workspace access",
  "lastObservation": "Last observation",
  "notConfirmed": "Not confirmed",
  "temporaryAccess": "Temporary accesses: {count}",
  "supportCodes": "Support codes: {count}"
,
"workspaceAttention": "Workspace needs attention",
"workspaceUnavailable": "Workspace status unavailable",
"supportOpenTitle": "Ready, with support access open",
"supportOpenDetail": "A temporary repair pass is active. You can close it at any time.",
"workspaceLive": "Your private workspace is live",
"workspaceLiveDetail": "Chat, account status, usage, and workspace health stay tied to this private space.",
"notRecorded": "Not recorded",
"storageUnmeasured": "Not measured yet. Limit {limit} MB"
};
const catalog: Record<AppLocale, typeof en> = { en,
"de": {
  "workspaceTitle": "Workspace-Status",
  "workspaceDescription": "Aktueller, vom Server bestätigter Zustand von Account, Abo, KI, Server, Sicherheit und Funktionen.",
  "account": "Account",
  "plan": "Abo",
  "aiModel": "KI-Modell",
  "server": "Server",
  "security": "Sicherheit",
  "capabilities": "Funktionen",
  "notifications": "Mitteilungen",
  "on": "An",
  "off": "Aus",
  "notConnected": "Nicht verbunden",
  "devices": "Registrierte Geräte: {count}",
  "enableHint": "Dieses Gerät für Antwortmitteilungen aktivieren",
  "support": "Support",
  "closed": "Geschlossen",
  "observation": "Letzte Serverbeobachtung {date}",
  "noObservation": "Keine aktuelle Serverbeobachtung",
  "pushTitle": "Push-Mitteilungen",
  "pushDescription": "Erhalte eine Gerätemitteilung, wenn Hermes fertig ist oder deine Aufmerksamkeit braucht.",
  "reconnect": "Erneut verbinden",
  "enable": "Aktivieren",
  "sendTest": "Test senden",
  "checking": "Wird geprüft…",
  "checkAgain": "Erneut prüfen",
  "signOut": "Abmelden",
  "connectorTitle": "Verbindungsstatus",
  "connectorDescription": "Nur für Eigentümer: gespeicherter Verbindungsstatus. Mitglieder sehen keine Einrichtungsformulare.",
  "ownerOnly": "nur Eigentümer",
  "savedSecrets": "Zugangsdaten gespeichert",
  "connectorEmpty": "Für diesen Workspace sind keine Verbindungseinträge verfügbar.",
  "chat": "Chat",
  "provider": "Anbieter",
  "runsToday": "Läufe heute",
  "dailyLimit": "Tageslimit",
  "lastMessage": "Letzte Nachricht",
  "noneYet": "noch keine",
  "last": "Zuletzt",
  "you": "du",
  "openChat": "Chat öffnen",
  "checkChat": "Chat prüfen",
  "ready": "bereit",
  "settingUp": "Einrichtung läuft",
  "includedModels": "Enthaltene Modelle",
  "unavailable": "Status nicht verfügbar",
  "routeReady": "Aktuelle Server- und KI-Anbieterbelege bestätigen, dass dieser Weg bereit ist.",
  "routeUnconfirmed": "Die aktuelle Bereitschaft des Servers oder KI-Anbieters konnte nicht bestätigt werden.",
  "runtime": "Laufzeitumgebung",
  "workspaceAccess": "Workspace-Zugriff",
  "lastObservation": "Letzte Beobachtung",
  "notConfirmed": "Nicht bestätigt",
  "temporaryAccess": "Zeitlich begrenzte Zugriffe: {count}",
  "supportCodes": "Supportcodes: {count}"
,
"workspaceAttention": "Workspace benötigt Aufmerksamkeit",
"workspaceUnavailable": "Workspace-Status nicht verfügbar",
"supportOpenTitle": "Bereit, Supportzugriff ist offen",
"supportOpenDetail": "Ein zeitlich begrenzter Reparaturzugriff ist aktiv. Du kannst ihn jederzeit schließen.",
"workspaceLive": "Dein privater Workspace ist aktiv",
"workspaceLiveDetail": "Chat, Account-Status, Nutzung und Workspace-Zustand bleiben diesem privaten Bereich zugeordnet.",
"notRecorded": "Nicht erfasst",
"storageUnmeasured": "Noch nicht gemessen. Limit: {limit} MB"
},
"fr": {
  "workspaceTitle": "État de l’espace de travail",
  "workspaceDescription": "État actuel du compte, de l’abonnement, de l’IA, du serveur, de la sécurité et des capacités, confirmé par le serveur.",
  "account": "Compte",
  "plan": "Abonnement",
  "aiModel": "Modèle IA",
  "server": "Serveur",
  "security": "Sécurité",
  "capabilities": "Capacités",
  "notifications": "Notifications",
  "on": "Activées",
  "off": "Désactivées",
  "notConnected": "Non connecté",
  "devices": "Appareils enregistrés : {count}",
  "enableHint": "Activez cet appareil pour les alertes de réponse",
  "support": "Support",
  "closed": "Fermé",
  "observation": "Dernière observation du serveur : {date}",
  "noObservation": "Aucune observation actuelle du serveur",
  "pushTitle": "Notifications push",
  "pushDescription": "Recevez une notification lorsque Hermes a terminé ou demande votre attention.",
  "reconnect": "Reconnecter",
  "enable": "Activer",
  "sendTest": "Envoyer un test",
  "checking": "Vérification…",
  "checkAgain": "Vérifier à nouveau",
  "signOut": "Se déconnecter",
  "connectorTitle": "État des connexions",
  "connectorDescription": "État enregistré des connexions, réservé au propriétaire. Les membres ne voient pas les formulaires de configuration.",
  "ownerOnly": "propriétaire uniquement",
  "savedSecrets": "identifiants enregistrés",
  "connectorEmpty": "Aucune connexion enregistrée n’est disponible pour cet espace.",
  "chat": "Chat",
  "provider": "Fournisseur",
  "runsToday": "Exécutions aujourd’hui",
  "dailyLimit": "Limite quotidienne",
  "lastMessage": "Dernier message",
  "noneYet": "aucun pour le moment",
  "last": "Dernier",
  "you": "vous",
  "openChat": "Ouvrir le chat",
  "checkChat": "Vérifier le chat",
  "ready": "prêt",
  "settingUp": "configuration en cours",
  "includedModels": "Modèles inclus",
  "unavailable": "État indisponible",
  "routeReady": "Les preuves actuelles du serveur et du fournisseur IA confirment que cette voie est prête.",
  "routeUnconfirmed": "La disponibilité actuelle du serveur ou du fournisseur IA n’a pas pu être confirmée.",
  "runtime": "Environnement d’exécution",
  "workspaceAccess": "Accès à l’espace",
  "lastObservation": "Dernière observation",
  "notConfirmed": "Non confirmé",
  "temporaryAccess": "Accès temporaires : {count}",
  "supportCodes": "Codes de support : {count}"
,
"workspaceAttention": "L’espace de travail nécessite votre attention",
"workspaceUnavailable": "État de l’espace de travail indisponible",
"supportOpenTitle": "Prêt, avec un accès au support ouvert",
"supportOpenDetail": "Un accès temporaire de réparation est actif. Vous pouvez le fermer à tout moment.",
"workspaceLive": "Votre espace de travail privé est actif",
"workspaceLiveDetail": "Le chat, l’état du compte, l’utilisation et l’état de l’espace de travail restent liés à cet espace privé.",
"notRecorded": "Non enregistré",
"storageUnmeasured": "Pas encore mesuré. Limite : {limit} Mo"
},
"es": {
  "workspaceTitle": "Estado del espacio de trabajo",
  "workspaceDescription": "Estado actual de cuenta, plan, IA, servidor, seguridad y capacidades confirmado por el servidor.",
  "account": "Cuenta",
  "plan": "Plan",
  "aiModel": "Modelo de IA",
  "server": "Servidor",
  "security": "Seguridad",
  "capabilities": "Capacidades",
  "notifications": "Notificaciones",
  "on": "Activadas",
  "off": "Desactivadas",
  "notConnected": "No conectado",
  "devices": "Dispositivos registrados: {count}",
  "enableHint": "Activa este dispositivo para recibir avisos de respuesta",
  "support": "Soporte",
  "closed": "Cerrado",
  "observation": "Última observación del servidor: {date}",
  "noObservation": "No hay observación actual del servidor",
  "pushTitle": "Notificaciones push",
  "pushDescription": "Recibe una notificación cuando Hermes termine o necesite tu atención.",
  "reconnect": "Reconectar",
  "enable": "Activar",
  "sendTest": "Enviar prueba",
  "checking": "Comprobando…",
  "checkAgain": "Comprobar de nuevo",
  "signOut": "Cerrar sesión",
  "connectorTitle": "Estado de conexiones",
  "connectorDescription": "Estado guardado de las conexiones, solo para propietarios. Los miembros no ven formularios de configuración.",
  "ownerOnly": "solo propietario",
  "savedSecrets": "credenciales guardadas",
  "connectorEmpty": "No hay registros de conexiones disponibles para este espacio.",
  "chat": "Chat",
  "provider": "Proveedor",
  "runsToday": "Ejecuciones de hoy",
  "dailyLimit": "Límite diario",
  "lastMessage": "Último mensaje",
  "noneYet": "ninguno aún",
  "last": "Último",
  "you": "tú",
  "openChat": "Abrir chat",
  "checkChat": "Comprobar chat",
  "ready": "listo",
  "settingUp": "configurando",
  "includedModels": "Modelos incluidos",
  "unavailable": "Estado no disponible",
  "routeReady": "Las pruebas actuales del servidor y del proveedor de IA confirman que esta ruta está lista.",
  "routeUnconfirmed": "No se pudo confirmar la disponibilidad actual del servidor o del proveedor de IA.",
  "runtime": "Entorno de ejecución",
  "workspaceAccess": "Acceso al espacio",
  "lastObservation": "Última observación",
  "notConfirmed": "Sin confirmar",
  "temporaryAccess": "Accesos temporales: {count}",
  "supportCodes": "Códigos de soporte: {count}"
,
"workspaceAttention": "El espacio de trabajo necesita atención",
"workspaceUnavailable": "Estado del espacio de trabajo no disponible",
"supportOpenTitle": "Listo, con acceso de soporte abierto",
"supportOpenDetail": "Hay un acceso temporal de reparación activo. Puedes cerrarlo en cualquier momento.",
"workspaceLive": "Tu espacio de trabajo privado está activo",
"workspaceLiveDetail": "El chat, el estado de la cuenta, el uso y el estado del espacio de trabajo siguen vinculados a este espacio privado.",
"notRecorded": "No registrado",
"storageUnmeasured": "Aún no medido. Límite: {limit} MB"
},
"it": {
  "workspaceTitle": "Stato dello spazio di lavoro",
  "workspaceDescription": "Stato attuale di account, piano, IA, server, sicurezza e funzionalità confermato dal server.",
  "account": "Account",
  "plan": "Piano",
  "aiModel": "Modello IA",
  "server": "Server",
  "security": "Sicurezza",
  "capabilities": "Funzionalità",
  "notifications": "Notifiche",
  "on": "Attive",
  "off": "Disattivate",
  "notConnected": "Non connesso",
  "devices": "Dispositivi registrati: {count}",
  "enableHint": "Attiva questo dispositivo per gli avvisi di risposta",
  "support": "Supporto",
  "closed": "Chiuso",
  "observation": "Ultima osservazione del server: {date}",
  "noObservation": "Nessuna osservazione attuale del server",
  "pushTitle": "Notifiche push",
  "pushDescription": "Ricevi una notifica quando Hermes termina o richiede attenzione.",
  "reconnect": "Riconnetti",
  "enable": "Attiva",
  "sendTest": "Invia prova",
  "checking": "Verifica…",
  "checkAgain": "Verifica di nuovo",
  "signOut": "Esci",
  "connectorTitle": "Stato delle connessioni",
  "connectorDescription": "Stato salvato delle connessioni, riservato al proprietario. I membri non vedono i moduli di configurazione.",
  "ownerOnly": "solo proprietario",
  "savedSecrets": "credenziali salvate",
  "connectorEmpty": "Nessun record di connessione disponibile per questo spazio.",
  "chat": "Chat",
  "provider": "Fornitore",
  "runsToday": "Esecuzioni di oggi",
  "dailyLimit": "Limite giornaliero",
  "lastMessage": "Ultimo messaggio",
  "noneYet": "nessuno ancora",
  "last": "Ultimo",
  "you": "tu",
  "openChat": "Apri chat",
  "checkChat": "Verifica chat",
  "ready": "pronto",
  "settingUp": "configurazione in corso",
  "includedModels": "Modelli inclusi",
  "unavailable": "Stato non disponibile",
  "routeReady": "Le prove attuali del server e del fornitore IA confermano che questo percorso è pronto.",
  "routeUnconfirmed": "Impossibile confermare la disponibilità attuale del server o del fornitore IA.",
  "runtime": "Ambiente di esecuzione",
  "workspaceAccess": "Accesso allo spazio",
  "lastObservation": "Ultima osservazione",
  "notConfirmed": "Non confermato",
  "temporaryAccess": "Accessi temporanei: {count}",
  "supportCodes": "Codici di supporto: {count}"
,
"workspaceAttention": "Lo spazio di lavoro richiede attenzione",
"workspaceUnavailable": "Stato dello spazio di lavoro non disponibile",
"supportOpenTitle": "Pronto, con accesso di supporto aperto",
"supportOpenDetail": "È attivo un accesso temporaneo per la riparazione. Puoi chiuderlo in qualsiasi momento.",
"workspaceLive": "Il tuo spazio di lavoro privato è attivo",
"workspaceLiveDetail": "Chat, stato dell’account, utilizzo e stato dello spazio di lavoro restano collegati a questo spazio privato.",
"notRecorded": "Non registrato",
"storageUnmeasured": "Non ancora misurato. Limite: {limit} MB"
},
"pt-BR": {
  "workspaceTitle": "Estado do espaço de trabalho",
  "workspaceDescription": "Estado atual de conta, plano, IA, servidor, segurança e recursos confirmado pelo servidor.",
  "account": "Conta",
  "plan": "Plano",
  "aiModel": "Modelo de IA",
  "server": "Servidor",
  "security": "Segurança",
  "capabilities": "Recursos",
  "notifications": "Notificações",
  "on": "Ativadas",
  "off": "Desativadas",
  "notConnected": "Não conectado",
  "devices": "Dispositivos registrados: {count}",
  "enableHint": "Ative este dispositivo para receber alertas de resposta",
  "support": "Suporte",
  "closed": "Fechado",
  "observation": "Última observação do servidor: {date}",
  "noObservation": "Nenhuma observação atual do servidor",
  "pushTitle": "Notificações push",
  "pushDescription": "Receba uma notificação quando o Hermes terminar ou precisar de atenção.",
  "reconnect": "Reconectar",
  "enable": "Ativar",
  "sendTest": "Enviar teste",
  "checking": "Verificando…",
  "checkAgain": "Verificar novamente",
  "signOut": "Sair",
  "connectorTitle": "Estado das conexões",
  "connectorDescription": "Estado salvo das conexões, apenas para o proprietário. Membros não veem formulários de configuração.",
  "ownerOnly": "somente proprietário",
  "savedSecrets": "credenciais salvas",
  "connectorEmpty": "Nenhum registro de conexão disponível para este espaço.",
  "chat": "Chat",
  "provider": "Provedor",
  "runsToday": "Execuções hoje",
  "dailyLimit": "Limite diário",
  "lastMessage": "Última mensagem",
  "noneYet": "nenhuma ainda",
  "last": "Última",
  "you": "você",
  "openChat": "Abrir chat",
  "checkChat": "Verificar chat",
  "ready": "pronto",
  "settingUp": "configurando",
  "includedModels": "Modelos incluídos",
  "unavailable": "Estado indisponível",
  "routeReady": "As evidências atuais do servidor e do provedor de IA confirmam que esta rota está pronta.",
  "routeUnconfirmed": "Não foi possível confirmar a disponibilidade atual do servidor ou do provedor de IA.",
  "runtime": "Ambiente de execução",
  "workspaceAccess": "Acesso ao espaço",
  "lastObservation": "Última observação",
  "notConfirmed": "Não confirmado",
  "temporaryAccess": "Acessos temporários: {count}",
  "supportCodes": "Códigos de suporte: {count}"
,
"workspaceAttention": "O espaço de trabalho precisa de atenção",
"workspaceUnavailable": "Estado do espaço de trabalho indisponível",
"supportOpenTitle": "Pronto, com acesso de suporte aberto",
"supportOpenDetail": "Um acesso temporário de reparo está ativo. Você pode fechá-lo a qualquer momento.",
"workspaceLive": "Seu espaço de trabalho privado está ativo",
"workspaceLiveDetail": "O chat, o estado da conta, o uso e o estado do espaço de trabalho continuam vinculados a este espaço privado.",
"notRecorded": "Não registrado",
"storageUnmeasured": "Ainda não medido. Limite: {limit} MB"
},
"ja": {
  "workspaceTitle": "ワークスペースの状態",
  "workspaceDescription": "サーバーで確認した、アカウント、プラン、AI、サーバー、セキュリティ、機能の現在の状態です。",
  "account": "アカウント",
  "plan": "プラン",
  "aiModel": "AIモデル",
  "server": "サーバー",
  "security": "セキュリティ",
  "capabilities": "機能",
  "notifications": "通知",
  "on": "オン",
  "off": "オフ",
  "notConnected": "未接続",
  "devices": "登録デバイス数：{count}",
  "enableHint": "このデバイスで返信通知を有効にする",
  "support": "サポート",
  "closed": "閉じています",
  "observation": "最後のサーバー確認：{date}",
  "noObservation": "現在のサーバー確認情報なし",
  "pushTitle": "プッシュ通知",
  "pushDescription": "Hermesが完了したときや確認が必要なときに通知を受け取ります。",
  "reconnect": "再接続",
  "enable": "有効にする",
  "sendTest": "テスト送信",
  "checking": "確認中…",
  "checkAgain": "再確認",
  "signOut": "サインアウト",
  "connectorTitle": "接続の状態",
  "connectorDescription": "保存された接続状態の所有者専用表示です。メンバーには設定フォームは表示されません。",
  "ownerOnly": "所有者のみ",
  "savedSecrets": "認証情報保存済み",
  "connectorEmpty": "このワークスペースで利用できる接続記録はありません。",
  "chat": "チャット",
  "provider": "プロバイダー",
  "runsToday": "今日の実行回数",
  "dailyLimit": "1日の上限",
  "lastMessage": "最後のメッセージ",
  "noneYet": "まだありません",
  "last": "直近",
  "you": "あなた",
  "openChat": "チャットを開く",
  "checkChat": "チャットを確認",
  "ready": "準備完了",
  "settingUp": "設定中",
  "includedModels": "付属モデル",
  "unavailable": "状態を取得できません",
  "routeReady": "サーバーとAIプロバイダーの現在の確認情報により、この経路が利用可能と確認できています。",
  "routeUnconfirmed": "サーバーまたはAIプロバイダーが現在利用可能か確認できませんでした。",
  "runtime": "実行環境",
  "workspaceAccess": "ワークスペースへのアクセス",
  "lastObservation": "最後の確認",
  "notConfirmed": "未確認",
  "temporaryAccess": "一時アクセス数：{count}",
  "supportCodes": "サポートコード数：{count}"
,
"workspaceAttention": "ワークスペースの確認が必要です",
"workspaceUnavailable": "ワークスペースの状態を取得できません",
"supportOpenTitle": "準備完了、サポートアクセスは有効です",
"supportOpenDetail": "一時的な修復アクセスが有効です。いつでも終了できます。",
"workspaceLive": "プライベートワークスペースは稼働中です",
"workspaceLiveDetail": "チャット、アカウントの状態、使用量、ワークスペースの状態はこのプライベート空間に紐付きます。",
"notRecorded": "記録なし",
"storageUnmeasured": "まだ計測されていません。上限：{limit} MB"
},
"ko": {
  "workspaceTitle": "워크스페이스 상태",
  "workspaceDescription": "서버에서 확인한 계정, 요금제, AI, 서버, 보안 및 기능의 현재 상태입니다.",
  "account": "계정",
  "plan": "요금제",
  "aiModel": "AI 모델",
  "server": "서버",
  "security": "보안",
  "capabilities": "기능",
  "notifications": "알림",
  "on": "켜짐",
  "off": "꺼짐",
  "notConnected": "연결되지 않음",
  "devices": "등록된 기기: {count}",
  "enableHint": "이 기기에서 답변 알림을 활성화하세요",
  "support": "지원",
  "closed": "닫힘",
  "observation": "최근 서버 확인: {date}",
  "noObservation": "현재 서버 확인 정보 없음",
  "pushTitle": "푸시 알림",
  "pushDescription": "Hermes가 완료하거나 확인이 필요할 때 기기 알림을 받습니다.",
  "reconnect": "다시 연결",
  "enable": "활성화",
  "sendTest": "테스트 보내기",
  "checking": "확인 중…",
  "checkAgain": "다시 확인",
  "signOut": "로그아웃",
  "connectorTitle": "연결 상태",
  "connectorDescription": "소유자만 볼 수 있는 저장된 연결 상태입니다. 멤버에게는 설정 양식이 표시되지 않습니다.",
  "ownerOnly": "소유자 전용",
  "savedSecrets": "인증 정보 저장됨",
  "connectorEmpty": "이 워크스페이스에 사용 가능한 연결 기록이 없습니다.",
  "chat": "채팅",
  "provider": "제공업체",
  "runsToday": "오늘 실행 횟수",
  "dailyLimit": "일일 한도",
  "lastMessage": "마지막 메시지",
  "noneYet": "아직 없음",
  "last": "최근",
  "you": "나",
  "openChat": "채팅 열기",
  "checkChat": "채팅 확인",
  "ready": "준비됨",
  "settingUp": "설정 중",
  "includedModels": "포함 모델",
  "unavailable": "상태를 확인할 수 없음",
  "routeReady": "현재 서버와 AI 제공업체의 확인 정보로 이 경로가 준비되었음을 확인했습니다.",
  "routeUnconfirmed": "서버 또는 AI 제공업체가 현재 준비되었는지 확인할 수 없습니다.",
  "runtime": "실행 환경",
  "workspaceAccess": "워크스페이스 접근",
  "lastObservation": "최근 확인",
  "notConfirmed": "확인되지 않음",
  "temporaryAccess": "임시 접근: {count}",
  "supportCodes": "지원 코드: {count}"
,
"workspaceAttention": "작업 공간 확인이 필요합니다",
"workspaceUnavailable": "작업 공간 상태를 확인할 수 없습니다",
"supportOpenTitle": "준비 완료, 지원 접근이 열려 있음",
"supportOpenDetail": "임시 복구 접근이 활성화되어 있습니다. 언제든 종료할 수 있습니다.",
"workspaceLive": "개인 작업 공간이 실행 중입니다",
"workspaceLiveDetail": "채팅, 계정 상태, 사용량 및 작업 공간 상태는 이 개인 공간에 연결됩니다.",
"notRecorded": "기록 없음",
"storageUnmeasured": "아직 측정되지 않았습니다. 한도: {limit} MB"
}
};
export function statusPanelCopy(locale: AppLocale) { return catalog[locale]; }
