import type { AppLocale } from "./types";
const en = {
  "unavailable": "Status unavailable",
  "noEvidence": "Current server evidence could not be loaded.",
  "routeUnknown": "The current AI route or model could not be confirmed.",
  "accountRouteModel": "Current account route · saved Included model: {model}",
  "accountRouteNoModel": "Current account route · no Included model is currently confirmed",
  "includedSaved": "Included AI · saved for later runs",
  "includedUnknown": "The current Included model could not be confirmed.",
  "accountUnknown": "The current Hey account could not be confirmed.",
  "planUnknown": "The current entitlement and plan could not be confirmed.",
  "includedWithAccount": "Included with account",
  "staleServer": "The last server observation is no longer current.",
  "noServer": "No private server assignment is currently proven.",
  "securityUnknown": "Current security status could not be confirmed.",
  "capabilityUnknown": "Current capability policy could not be confirmed.",
  "securityDetail": "{standing} · {handover} handover · {infrastructure} infrastructure · active support grants: {count}",
  "capabilityValue": "{count} policy-enabled",
  "capabilityDetail": "Current server policy entries: {count} · require approval: {approval}",
  "chatgptAccount": "ChatGPT account",
  "claudeAccount": "Claude account",
  "serverAssignmentUnknown": "The canonical server assignment could not be loaded.",
  "serverMismatch": "The last server observation does not belong to the current canonical server assignment.",
  "agentMissing": "A current Management Agent check is unavailable for the canonical workspace binding.",
  "agentMismatch": "The Management Agent check does not belong to the current workspace.",
  "agentNotRunning": "The current Management Agent check did not confirm a running workspace runtime.",
  "agentStale": "The Management Agent check is not current enough to confirm readiness.",
  "runtimeReady": "Your private Hermes runtime is ready.",
  "runtimeSettingUp": "Your private Hermes runtime is still being set up. Please try again shortly.",
  "runtimePaused": "Your private Hermes runtime is paused. Please resume access before trying again.",
  "runtimeAttention": "Your private Hermes runtime needs attention. Please try again shortly."
};
const catalog: Record<AppLocale, typeof en> = { en,
"de": {
  "unavailable": "Status nicht verfügbar",
  "noEvidence": "Aktuelle Serverbelege konnten nicht geladen werden.",
  "routeUnknown": "Der aktuelle KI-Weg oder das Modell konnte nicht bestätigt werden.",
  "accountRouteModel": "Aktueller Account-Zugang · gespeichertes enthaltenes Modell: {model}",
  "accountRouteNoModel": "Aktueller Account-Zugang · kein enthaltenes Modell bestätigt",
  "includedSaved": "Enthaltene KI · für spätere Läufe gespeichert",
  "includedUnknown": "Das aktuelle enthaltene Modell konnte nicht bestätigt werden.",
  "accountUnknown": "Der aktuelle Hey-Account konnte nicht bestätigt werden.",
  "planUnknown": "Die aktuelle Berechtigung und das Abo konnten nicht bestätigt werden.",
  "includedWithAccount": "Im Account enthalten",
  "staleServer": "Die letzte Serverbeobachtung ist nicht mehr aktuell.",
  "noServer": "Derzeit ist keine private Serverzuordnung belegt.",
  "securityUnknown": "Der aktuelle Sicherheitsstatus konnte nicht bestätigt werden.",
  "capabilityUnknown": "Die aktuelle Funktionsrichtlinie konnte nicht bestätigt werden.",
  "securityDetail": "{standing} · Übergabe: {handover} · Infrastruktur: {infrastructure} · aktive Supportfreigaben: {count}",
  "capabilityValue": "Durch Richtlinie aktiviert: {count}",
  "capabilityDetail": "Aktuelle Serverrichtlinien: {count} · Freigabe erforderlich: {approval}",
  "chatgptAccount": "ChatGPT-Account",
  "claudeAccount": "Claude-Account",
  "serverAssignmentUnknown": "Die maßgebliche Serverzuordnung konnte nicht geladen werden.",
  "serverMismatch": "Die letzte Serverbeobachtung gehört nicht zur aktuellen maßgeblichen Serverzuordnung.",
  "agentMissing": "Für die maßgebliche Workspace-Zuordnung ist keine aktuelle Management-Agent-Prüfung verfügbar.",
  "agentMismatch": "Die Management-Agent-Prüfung gehört nicht zum aktuellen Workspace.",
  "agentNotRunning": "Die aktuelle Management-Agent-Prüfung hat keine laufende Workspace-Umgebung bestätigt.",
  "agentStale": "Die Management-Agent-Prüfung ist nicht aktuell genug, um die Bereitschaft zu bestätigen.",
  "runtimeReady": "Deine private Hermes-Umgebung ist bereit.",
  "runtimeSettingUp": "Deine private Hermes-Umgebung wird noch eingerichtet. Versuche es gleich erneut.",
  "runtimePaused": "Deine private Hermes-Umgebung ist pausiert. Aktiviere den Zugriff vor einem neuen Versuch.",
  "runtimeAttention": "Deine private Hermes-Umgebung benötigt Aufmerksamkeit. Versuche es gleich erneut."
},
"fr": {
  "unavailable": "État indisponible",
  "noEvidence": "Impossible de charger les preuves actuelles du serveur.",
  "routeUnknown": "Impossible de confirmer la voie IA ou le modèle actuel.",
  "accountRouteModel": "Voie du compte actuelle · modèle inclus enregistré : {model}",
  "accountRouteNoModel": "Voie du compte actuelle · aucun modèle inclus confirmé",
  "includedSaved": "IA incluse · enregistrée pour les prochaines exécutions",
  "includedUnknown": "Impossible de confirmer le modèle inclus actuel.",
  "accountUnknown": "Impossible de confirmer le compte Hey actuel.",
  "planUnknown": "Impossible de confirmer les droits et l’abonnement actuels.",
  "includedWithAccount": "Inclus avec le compte",
  "staleServer": "La dernière observation du serveur n’est plus actuelle.",
  "noServer": "Aucune affectation de serveur privé n’est actuellement prouvée.",
  "securityUnknown": "Impossible de confirmer l’état actuel de la sécurité.",
  "capabilityUnknown": "Impossible de confirmer la politique actuelle des capacités.",
  "securityDetail": "{standing} · transfert : {handover} · infrastructure : {infrastructure} · autorisations de support actives : {count}",
  "capabilityValue": "Activées par la politique : {count}",
  "capabilityDetail": "Règles serveur actuelles : {count} · autorisation requise : {approval}",
  "chatgptAccount": "Compte ChatGPT",
  "claudeAccount": "Compte Claude",
  "serverAssignmentUnknown": "Impossible de charger l’affectation de serveur de référence.",
  "serverMismatch": "La dernière observation ne correspond pas à l’affectation de serveur de référence actuelle.",
  "agentMissing": "Aucune vérification actuelle de l’agent de gestion n’est disponible pour l’affectation de référence de cet espace.",
  "agentMismatch": "La vérification de l’agent de gestion ne correspond pas à cet espace.",
  "agentNotRunning": "La vérification actuelle de l’agent de gestion n’a pas confirmé un environnement en cours d’exécution.",
  "agentStale": "La vérification de l’agent de gestion est trop ancienne pour confirmer la disponibilité.",
  "runtimeReady": "Votre environnement Hermes privé est prêt.",
  "runtimeSettingUp": "Votre environnement Hermes privé est encore en configuration. Réessayez dans un instant.",
  "runtimePaused": "Votre environnement Hermes privé est en pause. Réactivez l’accès avant de réessayer.",
  "runtimeAttention": "Votre environnement Hermes privé nécessite une vérification. Réessayez dans un instant."
},
"es": {
  "unavailable": "Estado no disponible",
  "noEvidence": "No se pudieron cargar las pruebas actuales del servidor.",
  "routeUnknown": "No se pudo confirmar la ruta de IA o el modelo actual.",
  "accountRouteModel": "Ruta de cuenta actual · modelo incluido guardado: {model}",
  "accountRouteNoModel": "Ruta de cuenta actual · ningún modelo incluido confirmado",
  "includedSaved": "IA incluida · guardada para próximas ejecuciones",
  "includedUnknown": "No se pudo confirmar el modelo incluido actual.",
  "accountUnknown": "No se pudo confirmar la cuenta Hey actual.",
  "planUnknown": "No se pudieron confirmar los derechos y el plan actuales.",
  "includedWithAccount": "Incluido con la cuenta",
  "staleServer": "La última observación del servidor ya no es actual.",
  "noServer": "No hay una asignación de servidor privado demostrada actualmente.",
  "securityUnknown": "No se pudo confirmar el estado de seguridad actual.",
  "capabilityUnknown": "No se pudo confirmar la política actual de capacidades.",
  "securityDetail": "{standing} · transferencia: {handover} · infraestructura: {infrastructure} · permisos de soporte activos: {count}",
  "capabilityValue": "Habilitadas por política: {count}",
  "capabilityDetail": "Reglas actuales del servidor: {count} · requieren aprobación: {approval}",
  "chatgptAccount": "Cuenta de ChatGPT",
  "claudeAccount": "Cuenta de Claude",
  "serverAssignmentUnknown": "No se pudo cargar la asignación de servidor de referencia.",
  "serverMismatch": "La última observación no pertenece a la asignación de servidor de referencia actual.",
  "agentMissing": "No hay una comprobación actual del agente de gestión para la asignación de referencia de este espacio.",
  "agentMismatch": "La comprobación del agente de gestión no pertenece al espacio actual.",
  "agentNotRunning": "La comprobación actual del agente de gestión no confirmó un entorno del espacio en ejecución.",
  "agentStale": "La comprobación del agente de gestión no es lo bastante reciente para confirmar la disponibilidad.",
  "runtimeReady": "Tu entorno privado de Hermes está listo.",
  "runtimeSettingUp": "Tu entorno privado de Hermes sigue configurándose. Inténtalo de nuevo en un momento.",
  "runtimePaused": "Tu entorno privado de Hermes está en pausa. Reactiva el acceso antes de volver a intentarlo.",
  "runtimeAttention": "Tu entorno privado de Hermes necesita atención. Inténtalo de nuevo en un momento."
},
"it": {
  "unavailable": "Stato non disponibile",
  "noEvidence": "Impossibile caricare le prove attuali del server.",
  "routeUnknown": "Impossibile confermare il percorso IA o il modello attuale.",
  "accountRouteModel": "Percorso account attuale · modello incluso salvato: {model}",
  "accountRouteNoModel": "Percorso account attuale · nessun modello incluso confermato",
  "includedSaved": "IA inclusa · salvata per le prossime esecuzioni",
  "includedUnknown": "Impossibile confermare il modello incluso attuale.",
  "accountUnknown": "Impossibile confermare l’account Hey attuale.",
  "planUnknown": "Impossibile confermare i diritti e il piano attuali.",
  "includedWithAccount": "Incluso nell’account",
  "staleServer": "L’ultima osservazione del server non è più attuale.",
  "noServer": "Nessuna assegnazione a un server privato è attualmente provata.",
  "securityUnknown": "Impossibile confermare lo stato di sicurezza attuale.",
  "capabilityUnknown": "Impossibile confermare la politica attuale delle funzionalità.",
  "securityDetail": "{standing} · trasferimento: {handover} · infrastruttura: {infrastructure} · permessi di supporto attivi: {count}",
  "capabilityValue": "Abilitate dalla politica: {count}",
  "capabilityDetail": "Regole server attuali: {count} · richiedono approvazione: {approval}",
  "chatgptAccount": "Account ChatGPT",
  "claudeAccount": "Account Claude",
  "serverAssignmentUnknown": "Impossibile caricare l’assegnazione del server di riferimento.",
  "serverMismatch": "L’ultima osservazione non appartiene all’attuale assegnazione del server di riferimento.",
  "agentMissing": "Non è disponibile una verifica attuale dell’agente di gestione per l’assegnazione di riferimento dello spazio.",
  "agentMismatch": "La verifica dell’agente di gestione non appartiene allo spazio attuale.",
  "agentNotRunning": "La verifica attuale dell’agente di gestione non ha confermato un ambiente dello spazio in esecuzione.",
  "agentStale": "La verifica dell’agente di gestione non è abbastanza recente per confermare la disponibilità.",
  "runtimeReady": "Il tuo ambiente Hermes privato è pronto.",
  "runtimeSettingUp": "Il tuo ambiente Hermes privato è ancora in configurazione. Riprova tra poco.",
  "runtimePaused": "Il tuo ambiente Hermes privato è in pausa. Riattiva l’accesso prima di riprovare.",
  "runtimeAttention": "Il tuo ambiente Hermes privato richiede attenzione. Riprova tra poco."
},
"pt-BR": {
  "unavailable": "Estado indisponível",
  "noEvidence": "Não foi possível carregar as evidências atuais do servidor.",
  "routeUnknown": "Não foi possível confirmar a rota de IA ou o modelo atual.",
  "accountRouteModel": "Rota de conta atual · modelo incluído salvo: {model}",
  "accountRouteNoModel": "Rota de conta atual · nenhum modelo incluído confirmado",
  "includedSaved": "IA incluída · salva para próximas execuções",
  "includedUnknown": "Não foi possível confirmar o modelo incluído atual.",
  "accountUnknown": "Não foi possível confirmar a conta Hey atual.",
  "planUnknown": "Não foi possível confirmar os direitos e o plano atuais.",
  "includedWithAccount": "Incluído na conta",
  "staleServer": "A última observação do servidor não é mais atual.",
  "noServer": "Nenhuma atribuição de servidor privado está comprovada atualmente.",
  "securityUnknown": "Não foi possível confirmar o estado atual de segurança.",
  "capabilityUnknown": "Não foi possível confirmar a política atual de recursos.",
  "securityDetail": "{standing} · transferência: {handover} · infraestrutura: {infrastructure} · permissões de suporte ativas: {count}",
  "capabilityValue": "Habilitados pela política: {count}",
  "capabilityDetail": "Regras atuais do servidor: {count} · exigem aprovação: {approval}",
  "chatgptAccount": "Conta ChatGPT",
  "claudeAccount": "Conta Claude",
  "serverAssignmentUnknown": "Não foi possível carregar a atribuição do servidor de referência.",
  "serverMismatch": "A última observação não pertence à atribuição atual do servidor de referência.",
  "agentMissing": "Não há verificação atual do agente de gestão para a atribuição de referência deste espaço.",
  "agentMismatch": "A verificação do agente de gestão não pertence ao espaço atual.",
  "agentNotRunning": "A verificação atual do agente de gestão não confirmou um ambiente do espaço em execução.",
  "agentStale": "A verificação do agente de gestão não é recente o bastante para confirmar a disponibilidade.",
  "runtimeReady": "Seu ambiente privado do Hermes está pronto.",
  "runtimeSettingUp": "Seu ambiente privado do Hermes ainda está sendo configurado. Tente novamente em instantes.",
  "runtimePaused": "Seu ambiente privado do Hermes está pausado. Reative o acesso antes de tentar novamente.",
  "runtimeAttention": "Seu ambiente privado do Hermes precisa de atenção. Tente novamente em instantes."
},
"ja": {
  "unavailable": "状態を取得できません",
  "noEvidence": "現在のサーバー確認情報を読み込めませんでした。",
  "routeUnknown": "現在のAI経路またはモデルを確認できませんでした。",
  "accountRouteModel": "現在のアカウント経路 · 保存済み付属モデル：{model}",
  "accountRouteNoModel": "現在のアカウント経路 · 付属モデルは未確認",
  "includedSaved": "付属AI · 今後の実行用に保存済み",
  "includedUnknown": "現在の付属モデルを確認できませんでした。",
  "accountUnknown": "現在のHeyアカウントを確認できませんでした。",
  "planUnknown": "現在の利用権限とプランを確認できませんでした。",
  "includedWithAccount": "アカウントに含まれます",
  "staleServer": "最後のサーバー確認情報は古くなっています。",
  "noServer": "現在、プライベートサーバーの割り当ては確認できていません。",
  "securityUnknown": "現在のセキュリティ状態を確認できませんでした。",
  "capabilityUnknown": "現在の機能ポリシーを確認できませんでした。",
  "securityDetail": "{standing} · 引き渡し：{handover} · インフラ：{infrastructure} · 有効なサポート許可：{count}",
  "capabilityValue": "ポリシーで有効：{count}",
  "capabilityDetail": "現在のサーバーポリシー項目：{count} · 承認が必要：{approval}",
  "chatgptAccount": "ChatGPTアカウント",
  "claudeAccount": "Claudeアカウント",
  "serverAssignmentUnknown": "正式なサーバー割り当てを読み込めませんでした。",
  "serverMismatch": "最後のサーバー確認情報は現在の正式な割り当てと一致しません。",
  "agentMissing": "正式なワークスペース割り当てに対する管理エージェントの現在の確認情報がありません。",
  "agentMismatch": "管理エージェントの確認情報は現在のワークスペースのものではありません。",
  "agentNotRunning": "管理エージェントの現在の確認情報ではワークスペースが稼働中であると確認できませんでした。",
  "agentStale": "管理エージェントの確認情報が古いため、利用可能か確認できません。",
  "runtimeReady": "プライベートなHermes実行環境は準備完了です。",
  "runtimeSettingUp": "プライベートなHermes実行環境は設定中です。しばらくしてから再試行してください。",
  "runtimePaused": "プライベートなHermes実行環境は一時停止中です。アクセスを再開してから再試行してください。",
  "runtimeAttention": "プライベートなHermes実行環境に確認が必要です。しばらくしてから再試行してください。"
},
"ko": {
  "unavailable": "상태를 확인할 수 없음",
  "noEvidence": "현재 서버 확인 정보를 불러오지 못했습니다.",
  "routeUnknown": "현재 AI 경로 또는 모델을 확인하지 못했습니다.",
  "accountRouteModel": "현재 계정 경로 · 저장된 포함 모델: {model}",
  "accountRouteNoModel": "현재 계정 경로 · 확인된 포함 모델 없음",
  "includedSaved": "포함 AI · 다음 실행을 위해 저장됨",
  "includedUnknown": "현재 포함 모델을 확인하지 못했습니다.",
  "accountUnknown": "현재 Hey 계정을 확인하지 못했습니다.",
  "planUnknown": "현재 이용 권한과 요금제를 확인하지 못했습니다.",
  "includedWithAccount": "계정에 포함됨",
  "staleServer": "최근 서버 확인 정보가 더 이상 최신이 아닙니다.",
  "noServer": "현재 확인된 비공개 서버 할당이 없습니다.",
  "securityUnknown": "현재 보안 상태를 확인하지 못했습니다.",
  "capabilityUnknown": "현재 기능 정책을 확인하지 못했습니다.",
  "securityDetail": "{standing} · 인계: {handover} · 인프라: {infrastructure} · 활성 지원 권한: {count}",
  "capabilityValue": "정책으로 활성화됨: {count}",
  "capabilityDetail": "현재 서버 정책 항목: {count} · 승인 필요: {approval}",
  "chatgptAccount": "ChatGPT 계정",
  "claudeAccount": "Claude 계정",
  "serverAssignmentUnknown": "기준 서버 할당 정보를 불러오지 못했습니다.",
  "serverMismatch": "최근 서버 확인 정보가 현재 기준 서버 할당에 해당하지 않습니다.",
  "agentMissing": "기준 워크스페이스 할당에 대한 관리 에이전트의 현재 확인 정보가 없습니다.",
  "agentMismatch": "관리 에이전트 확인 정보가 현재 워크스페이스에 해당하지 않습니다.",
  "agentNotRunning": "관리 에이전트의 현재 확인 정보로 워크스페이스 환경이 실행 중인지 확인하지 못했습니다.",
  "agentStale": "관리 에이전트 확인 정보가 오래되어 준비 상태를 확인할 수 없습니다.",
  "runtimeReady": "비공개 Hermes 실행 환경이 준비되었습니다.",
  "runtimeSettingUp": "비공개 Hermes 실행 환경을 설정 중입니다. 잠시 후 다시 시도하세요.",
  "runtimePaused": "비공개 Hermes 실행 환경이 일시 중지되었습니다. 접근을 재개한 후 다시 시도하세요.",
  "runtimeAttention": "비공개 Hermes 실행 환경에 확인이 필요합니다. 잠시 후 다시 시도하세요."
}
};
export function statusSummaryCopy(locale: AppLocale) { return catalog[locale]; }
export function statusServerMessage(locale: AppLocale, message: string) {
 const key = (Object.keys(en) as Array<keyof typeof en>).find(key => en[key] === message);
 return key ? catalog[locale][key] : message;
}
