import { defaultAppLocale, type AppLocale } from "./types";

const en = {
  "title": "Contact support",
  "loading": "Loading your signed-in support details…",
  "retry": "Retry",
  "email": "Email",
  "copyEmail": "Copy support email address",
  "copied": "Copied",
  "emailCopied": "Support email copied.",
  "accepted": "Support request accepted",
  "keepReference": "Keep this reference for follow-up:",
  "copyReference": "Copy reference",
  "newRequest": "New support request",
  "subtitle": "A normal Hey Hermes support request — not an AI chat.",
  "account": "Hey account",
  "sessionSource": "Taken from your signed-in session. It cannot be changed here.",
  "verifiedEmail": "Verified reply email",
  "alternateEmail": "Optional alternate reply email",
  "alternateHint": "Leave blank to receive the reply at your verified email",
  "replyChannel": "Reply channel",
  "replyEmail": "Reply email",
  "invalidEmail": "Enter a valid reply email.",
  "requiredEmail": "A reply email is required.",
  "problem": "What happened?",
  "problemLabel": "Problem description",
  "problemHint": "Required. Do not include passwords, tokens, chat history or private files",
  "boundary": "Hey Hermes adds the app version, platform, language and time automatically. It does not attach chats, prompts, credentials, logs, workspace files or VPS data. Do not paste passwords or tokens. Sending this form grants no Support Pass or private-data access.",
  "reference": "Support reference:",
  "sending": "Sending…",
  "retryRequest": "Retry support request",
  "sendRequest": "Send support request",
  "copy": "Copy",
  "offline": "You appear to be offline. Reconnect and try again, or use the support email below.",
  "rateLimited": "Too many support requests were attempted. Please wait and try again, or use the support email below.",
  "sessionExpired": "Your sign-in has ended. Sign in again before retrying, or use the support email below.",
  "deliveryFailed": "Your case was recorded, but mailbox delivery failed. Use the support email below and include the reference.",
  "deliveryPending": "Your case was recorded and delivery is still being checked. Keep the reference and retry shortly.",
  "invalidInput": "Remove credentials or unsupported content, then try again.",
  "invalidResponse": "The support service returned an invalid response. Nothing is shown as sent. Retry or use the support email below.",
  "unavailable": "The support form is unavailable right now. Nothing is shown as sent. Retry or use the support email below.",
  "problemTooLong": "Keep the description under 4,000 characters.",
  "problemSensitive": "Remove passwords, tokens or private keys before sending.",
  "problemRequired": "Describe the problem before sending."
};

const copy: Record<AppLocale, typeof en> = {
  en,
  "de": {
  "title": "Support kontaktieren",
  "loading": "Deine Support-Angaben werden geladen…",
  "retry": "Erneut versuchen",
  "email": "E-Mail an",
  "copyEmail": "Support-E-Mail-Adresse kopieren",
  "copied": "Kopiert",
  "emailCopied": "Support-E-Mail-Adresse kopiert.",
  "accepted": "Support-Anfrage angenommen",
  "keepReference": "Bewahre diese Referenz für Rückfragen auf:",
  "copyReference": "Referenz kopieren",
  "newRequest": "Neue Support-Anfrage",
  "subtitle": "Eine normale Support-Anfrage an Hey Hermes — kein KI-Chat.",
  "account": "Hey-Konto",
  "sessionSource": "Aus deiner angemeldeten Sitzung übernommen. Hier nicht änderbar.",
  "verifiedEmail": "Bestätigte Antwortadresse",
  "alternateEmail": "Optionale alternative Antwortadresse",
  "alternateHint": "Leer lassen, um die Antwort an deine bestätigte E-Mail-Adresse zu erhalten",
  "replyChannel": "Antwortkanal",
  "replyEmail": "E-Mail-Adresse für die Antwort",
  "invalidEmail": "Gib eine gültige E-Mail-Adresse für die Antwort ein.",
  "requiredEmail": "Eine E-Mail-Adresse für die Antwort ist erforderlich.",
  "problem": "Was ist passiert?",
  "problemLabel": "Problembeschreibung",
  "problemHint": "Erforderlich. Keine Passwörter, Tokens, Chatverläufe oder privaten Dateien angeben",
  "boundary": "Hey Hermes ergänzt automatisch App-Version, Plattform, Sprache und Zeitpunkt. Chats, Prompts, Zugangsdaten, Protokolle, Workspace-Dateien oder VPS-Daten werden nicht angehängt. Füge keine Passwörter oder Tokens ein. Das Absenden erteilt weder einen Support-Pass noch Zugriff auf private Daten.",
  "reference": "Support-Referenz:",
  "sending": "Wird gesendet…",
  "retryRequest": "Support-Anfrage erneut senden",
  "sendRequest": "Support-Anfrage senden",
  "copy": "Kopieren",
  "offline": "Du scheinst offline zu sein. Stelle die Verbindung wieder her und versuche es erneut oder nutze die Support-E-Mail-Adresse unten.",
  "rateLimited": "Zu viele Support-Anfragen. Warte bitte und versuche es erneut oder nutze die Support-E-Mail-Adresse unten.",
  "sessionExpired": "Deine Anmeldung ist abgelaufen. Melde dich erneut an oder nutze die Support-E-Mail-Adresse unten.",
  "deliveryFailed": "Dein Fall wurde erfasst, aber die E-Mail-Zustellung ist fehlgeschlagen. Nutze die Support-E-Mail-Adresse unten und gib die Referenz an.",
  "deliveryPending": "Dein Fall wurde erfasst. Die Zustellung wird noch geprüft. Bewahre die Referenz auf und versuche es in Kürze erneut.",
  "invalidInput": "Entferne Zugangsdaten oder nicht unterstützte Inhalte und versuche es erneut.",
  "invalidResponse": "Der Support-Dienst hat eine ungültige Antwort geliefert. Es wird nichts als gesendet angezeigt. Versuche es erneut oder nutze die Support-E-Mail-Adresse unten.",
  "unavailable": "Das Support-Formular ist derzeit nicht verfügbar. Es wird nichts als gesendet angezeigt. Versuche es erneut oder nutze die Support-E-Mail-Adresse unten.",
  "problemTooLong": "Halte die Beschreibung unter 4.000 Zeichen.",
  "problemSensitive": "Entferne vor dem Senden Passwörter, Tokens oder private Schlüssel.",
  "problemRequired": "Beschreibe das Problem vor dem Senden."
},
  "fr": {
  "title": "Contacter l’assistance",
  "loading": "Chargement de vos informations d’assistance…",
  "retry": "Réessayer",
  "email": "Écrire à",
  "copyEmail": "Copier l’adresse de l’assistance",
  "copied": "Copié",
  "emailCopied": "Adresse de l’assistance copiée.",
  "accepted": "Demande d’assistance acceptée",
  "keepReference": "Conservez cette référence pour le suivi :",
  "copyReference": "Copier la référence",
  "newRequest": "Nouvelle demande d’assistance",
  "subtitle": "Une demande d’assistance Hey Hermes classique — pas un chat avec l’IA.",
  "account": "Compte Hey",
  "sessionSource": "Informations de votre session connectée. Elles ne peuvent pas être modifiées ici.",
  "verifiedEmail": "Adresse de réponse vérifiée",
  "alternateEmail": "Autre adresse de réponse facultative",
  "alternateHint": "Laissez vide pour recevoir la réponse à votre adresse vérifiée",
  "replyChannel": "Canal de réponse",
  "replyEmail": "Adresse e-mail de réponse",
  "invalidEmail": "Saisissez une adresse de réponse valide.",
  "requiredEmail": "Une adresse de réponse est requise.",
  "problem": "Que s’est-il passé ?",
  "problemLabel": "Description du problème",
  "problemHint": "Obligatoire. N’incluez aucun mot de passe, jeton, historique de chat ou fichier privé",
  "boundary": "Hey Hermes ajoute automatiquement la version de l’application, la plateforme, la langue et l’heure. Aucun chat, prompt, identifiant, journal, fichier de l’espace de travail ou donnée VPS n’est joint. Ne collez aucun mot de passe ni jeton. L’envoi de ce formulaire n’accorde aucun pass d’assistance ni accès aux données privées.",
  "reference": "Référence d’assistance :",
  "sending": "Envoi…",
  "retryRequest": "Renvoyer la demande",
  "sendRequest": "Envoyer la demande",
  "copy": "Copier",
  "offline": "Vous semblez hors ligne. Reconnectez-vous et réessayez, ou utilisez l’adresse de l’assistance ci-dessous.",
  "rateLimited": "Trop de demandes d’assistance. Patientez et réessayez, ou utilisez l’adresse de l’assistance ci-dessous.",
  "sessionExpired": "Votre session a expiré. Reconnectez-vous avant de réessayer, ou utilisez l’adresse de l’assistance ci-dessous.",
  "deliveryFailed": "Votre dossier est enregistré, mais l’envoi par e-mail a échoué. Écrivez à l’assistance ci-dessous en indiquant la référence.",
  "deliveryPending": "Votre dossier est enregistré et l’envoi est encore en cours de vérification. Conservez la référence et réessayez bientôt.",
  "invalidInput": "Retirez les identifiants ou le contenu non pris en charge, puis réessayez.",
  "invalidResponse": "Le service d’assistance a renvoyé une réponse invalide. Rien n’est indiqué comme envoyé. Réessayez ou utilisez l’adresse ci-dessous.",
  "unavailable": "Le formulaire d’assistance est indisponible. Rien n’est indiqué comme envoyé. Réessayez ou utilisez l’adresse ci-dessous.",
  "problemTooLong": "Limitez la description à moins de 4 000 caractères.",
  "problemSensitive": "Retirez les mots de passe, jetons ou clés privées avant l’envoi.",
  "problemRequired": "Décrivez le problème avant l’envoi."
},
  "es": {
  "title": "Contactar con soporte",
  "loading": "Cargando tus datos de soporte…",
  "retry": "Reintentar",
  "email": "Escribir a",
  "copyEmail": "Copiar dirección de soporte",
  "copied": "Copiado",
  "emailCopied": "Dirección de soporte copiada.",
  "accepted": "Solicitud de soporte aceptada",
  "keepReference": "Guarda esta referencia para el seguimiento:",
  "copyReference": "Copiar referencia",
  "newRequest": "Nueva solicitud de soporte",
  "subtitle": "Una solicitud normal al soporte de Hey Hermes — no un chat con IA.",
  "account": "Cuenta Hey",
  "sessionSource": "Datos de tu sesión iniciada. No se pueden cambiar aquí.",
  "verifiedEmail": "Correo de respuesta verificado",
  "alternateEmail": "Correo alternativo de respuesta opcional",
  "alternateHint": "Déjalo vacío para recibir la respuesta en tu correo verificado",
  "replyChannel": "Canal de respuesta",
  "replyEmail": "Correo de respuesta",
  "invalidEmail": "Introduce un correo de respuesta válido.",
  "requiredEmail": "Se requiere un correo de respuesta.",
  "problem": "¿Qué ocurrió?",
  "problemLabel": "Descripción del problema",
  "problemHint": "Obligatorio. No incluyas contraseñas, tokens, historial de chat ni archivos privados",
  "boundary": "Hey Hermes añade automáticamente la versión de la app, plataforma, idioma y hora. No adjunta chats, prompts, credenciales, registros, archivos del espacio de trabajo ni datos del VPS. No pegues contraseñas ni tokens. Enviar este formulario no concede un pase de soporte ni acceso a datos privados.",
  "reference": "Referencia de soporte:",
  "sending": "Enviando…",
  "retryRequest": "Reintentar solicitud",
  "sendRequest": "Enviar solicitud",
  "copy": "Copiar",
  "offline": "Parece que no tienes conexión. Conéctate y reintenta, o usa el correo de soporte de abajo.",
  "rateLimited": "Se han intentado demasiadas solicitudes. Espera y reintenta, o usa el correo de soporte de abajo.",
  "sessionExpired": "Tu sesión ha finalizado. Inicia sesión de nuevo, o usa el correo de soporte de abajo.",
  "deliveryFailed": "Tu caso se registró, pero falló la entrega por correo. Usa el correo de soporte de abajo e incluye la referencia.",
  "deliveryPending": "Tu caso se registró y aún se está comprobando la entrega. Guarda la referencia y reintenta en breve.",
  "invalidInput": "Elimina las credenciales o el contenido no admitido y reintenta.",
  "invalidResponse": "El servicio de soporte devolvió una respuesta inválida. Nada se muestra como enviado. Reintenta o usa el correo de abajo.",
  "unavailable": "El formulario de soporte no está disponible. Nada se muestra como enviado. Reintenta o usa el correo de abajo.",
  "problemTooLong": "La descripción debe tener menos de 4000 caracteres.",
  "problemSensitive": "Elimina contraseñas, tokens o claves privadas antes de enviar.",
  "problemRequired": "Describe el problema antes de enviar."
},
  "it": {
  "title": "Contatta l’assistenza",
  "loading": "Caricamento dei tuoi dati di assistenza…",
  "retry": "Riprova",
  "email": "Scrivi a",
  "copyEmail": "Copia indirizzo dell’assistenza",
  "copied": "Copiato",
  "emailCopied": "Indirizzo dell’assistenza copiato.",
  "accepted": "Richiesta di assistenza accettata",
  "keepReference": "Conserva questo riferimento per il seguito:",
  "copyReference": "Copia riferimento",
  "newRequest": "Nuova richiesta di assistenza",
  "subtitle": "Una normale richiesta di assistenza Hey Hermes — non una chat con l’IA.",
  "account": "Account Hey",
  "sessionSource": "Dati della sessione connessa. Non possono essere modificati qui.",
  "verifiedEmail": "Email di risposta verificata",
  "alternateEmail": "Email di risposta alternativa facoltativa",
  "alternateHint": "Lascia vuoto per ricevere la risposta all’email verificata",
  "replyChannel": "Canale di risposta",
  "replyEmail": "Email di risposta",
  "invalidEmail": "Inserisci un’email di risposta valida.",
  "requiredEmail": "È richiesta un’email di risposta.",
  "problem": "Che cosa è successo?",
  "problemLabel": "Descrizione del problema",
  "problemHint": "Obbligatorio. Non includere password, token, cronologia della chat o file privati",
  "boundary": "Hey Hermes aggiunge automaticamente versione dell’app, piattaforma, lingua e ora. Non allega chat, prompt, credenziali, registri, file dello spazio di lavoro o dati VPS. Non incollare password o token. L’invio del modulo non concede un pass di assistenza né accesso ai dati privati.",
  "reference": "Riferimento assistenza:",
  "sending": "Invio…",
  "retryRequest": "Riprova la richiesta",
  "sendRequest": "Invia richiesta",
  "copy": "Copia",
  "offline": "Sembra che tu sia offline. Riconnettiti e riprova oppure usa l’email dell’assistenza qui sotto.",
  "rateLimited": "Troppe richieste di assistenza. Attendi e riprova oppure usa l’email dell’assistenza qui sotto.",
  "sessionExpired": "La sessione è terminata. Accedi di nuovo oppure usa l’email dell’assistenza qui sotto.",
  "deliveryFailed": "Il caso è stato registrato, ma l’invio email non è riuscito. Usa l’email dell’assistenza qui sotto e includi il riferimento.",
  "deliveryPending": "Il caso è stato registrato e la consegna è ancora in verifica. Conserva il riferimento e riprova tra poco.",
  "invalidInput": "Rimuovi credenziali o contenuti non supportati e riprova.",
  "invalidResponse": "Il servizio di assistenza ha restituito una risposta non valida. Nulla è indicato come inviato. Riprova o usa l’email qui sotto.",
  "unavailable": "Il modulo di assistenza non è disponibile. Nulla è indicato come inviato. Riprova o usa l’email qui sotto.",
  "problemTooLong": "Mantieni la descrizione sotto i 4000 caratteri.",
  "problemSensitive": "Rimuovi password, token o chiavi private prima dell’invio.",
  "problemRequired": "Descrivi il problema prima dell’invio."
},
  "pt-BR": {
  "title": "Contatar o suporte",
  "loading": "Carregando seus dados de suporte…",
  "retry": "Tentar novamente",
  "email": "Enviar e-mail para",
  "copyEmail": "Copiar endereço do suporte",
  "copied": "Copiado",
  "emailCopied": "Endereço do suporte copiado.",
  "accepted": "Solicitação de suporte aceita",
  "keepReference": "Guarde esta referência para acompanhamento:",
  "copyReference": "Copiar referência",
  "newRequest": "Nova solicitação de suporte",
  "subtitle": "Uma solicitação normal ao suporte do Hey Hermes — não um chat com IA.",
  "account": "Conta Hey",
  "sessionSource": "Dados da sua sessão conectada. Não podem ser alterados aqui.",
  "verifiedEmail": "E-mail de resposta verificado",
  "alternateEmail": "E-mail alternativo de resposta opcional",
  "alternateHint": "Deixe em branco para receber a resposta no e-mail verificado",
  "replyChannel": "Canal de resposta",
  "replyEmail": "E-mail de resposta",
  "invalidEmail": "Insira um e-mail de resposta válido.",
  "requiredEmail": "É necessário um e-mail de resposta.",
  "problem": "O que aconteceu?",
  "problemLabel": "Descrição do problema",
  "problemHint": "Obrigatório. Não inclua senhas, tokens, histórico de chat nem arquivos privados",
  "boundary": "O Hey Hermes adiciona automaticamente a versão do app, plataforma, idioma e horário. Não anexa chats, prompts, credenciais, registros, arquivos do espaço de trabalho nem dados do VPS. Não cole senhas nem tokens. Enviar este formulário não concede passe de suporte nem acesso a dados privados.",
  "reference": "Referência do suporte:",
  "sending": "Enviando…",
  "retryRequest": "Tentar a solicitação novamente",
  "sendRequest": "Enviar solicitação",
  "copy": "Copiar",
  "offline": "Parece que você está offline. Reconecte-se e tente novamente ou use o e-mail do suporte abaixo.",
  "rateLimited": "Muitas tentativas de solicitação. Aguarde e tente novamente ou use o e-mail do suporte abaixo.",
  "sessionExpired": "Sua sessão terminou. Entre novamente ou use o e-mail do suporte abaixo.",
  "deliveryFailed": "Seu caso foi registrado, mas a entrega por e-mail falhou. Use o e-mail do suporte abaixo e inclua a referência.",
  "deliveryPending": "Seu caso foi registrado e a entrega ainda está sendo verificada. Guarde a referência e tente novamente em breve.",
  "invalidInput": "Remova credenciais ou conteúdo não compatível e tente novamente.",
  "invalidResponse": "O serviço de suporte retornou uma resposta inválida. Nada é mostrado como enviado. Tente novamente ou use o e-mail abaixo.",
  "unavailable": "O formulário de suporte está indisponível. Nada é mostrado como enviado. Tente novamente ou use o e-mail abaixo.",
  "problemTooLong": "Mantenha a descrição com menos de 4.000 caracteres.",
  "problemSensitive": "Remova senhas, tokens ou chaves privadas antes de enviar.",
  "problemRequired": "Descreva o problema antes de enviar."
},
  "ja": {
  "title": "サポートに問い合わせる",
  "loading": "サポート情報を読み込み中…",
  "retry": "再試行",
  "email": "メール送信先",
  "copyEmail": "サポートのメールアドレスをコピー",
  "copied": "コピー済み",
  "emailCopied": "サポートのメールアドレスをコピーしました。",
  "accepted": "サポートへの問い合わせを受け付けました",
  "keepReference": "今後の問い合わせ用にこの参照番号を保管してください：",
  "copyReference": "参照番号をコピー",
  "newRequest": "新しい問い合わせ",
  "subtitle": "Hey Hermesの通常のサポート窓口です。AIチャットではありません。",
  "account": "Heyアカウント",
  "sessionSource": "ログイン中のセッションから取得しています。ここでは変更できません。",
  "verifiedEmail": "確認済みの返信先メールアドレス",
  "alternateEmail": "別の返信先メールアドレス（任意）",
  "alternateHint": "空欄の場合は確認済みのメールアドレスに返信します",
  "replyChannel": "返信方法",
  "replyEmail": "返信先メールアドレス",
  "invalidEmail": "有効な返信先メールアドレスを入力してください。",
  "requiredEmail": "返信先メールアドレスが必要です。",
  "problem": "何が起きましたか？",
  "problemLabel": "問題の説明",
  "problemHint": "必須。パスワード、トークン、チャット履歴、個人ファイルを含めないでください",
  "boundary": "Hey Hermesはアプリのバージョン、プラットフォーム、言語、時刻を自動的に追加します。チャット、プロンプト、認証情報、ログ、ワークスペースのファイル、VPSデータは添付しません。パスワードやトークンを貼り付けないでください。このフォームを送信してもサポートパスや個人データへのアクセス権は付与されません。",
  "reference": "サポート参照番号：",
  "sending": "送信中…",
  "retryRequest": "問い合わせを再送信",
  "sendRequest": "問い合わせを送信",
  "copy": "コピー",
  "offline": "オフラインのようです。再接続して再試行するか、下記のサポートメールをご利用ください。",
  "rateLimited": "問い合わせの試行回数が多すぎます。しばらく待って再試行するか、下記のサポートメールをご利用ください。",
  "sessionExpired": "ログインの有効期限が切れました。再度ログインするか、下記のサポートメールをご利用ください。",
  "deliveryFailed": "案件は記録されましたが、メール配信に失敗しました。下記のサポートメールに参照番号を添えてご連絡ください。",
  "deliveryPending": "案件は記録され、配信を確認中です。参照番号を保管し、しばらくしてから再試行してください。",
  "invalidInput": "認証情報や非対応の内容を削除して再試行してください。",
  "invalidResponse": "サポートサービスから無効な応答が返されました。送信済みとは表示していません。再試行するか、下記のメールをご利用ください。",
  "unavailable": "現在サポートフォームを利用できません。送信済みとは表示していません。再試行するか、下記のメールをご利用ください。",
  "problemTooLong": "説明は4,000文字未満にしてください。",
  "problemSensitive": "送信前にパスワード、トークン、秘密鍵を削除してください。",
  "problemRequired": "送信前に問題を説明してください。"
},
  "ko": {
  "title": "지원팀에 문의",
  "loading": "지원 정보를 불러오는 중…",
  "retry": "다시 시도",
  "email": "이메일 보내기",
  "copyEmail": "지원 이메일 주소 복사",
  "copied": "복사됨",
  "emailCopied": "지원 이메일 주소를 복사했습니다.",
  "accepted": "지원 요청이 접수되었습니다",
  "keepReference": "후속 문의를 위해 이 참조 번호를 보관하세요:",
  "copyReference": "참조 번호 복사",
  "newRequest": "새 지원 요청",
  "subtitle": "Hey Hermes의 일반 지원 요청입니다. AI 채팅이 아닙니다.",
  "account": "Hey 계정",
  "sessionSource": "로그인한 세션에서 가져온 정보입니다. 여기서는 변경할 수 없습니다.",
  "verifiedEmail": "인증된 답변 이메일",
  "alternateEmail": "다른 답변 이메일 (선택)",
  "alternateHint": "비워 두면 인증된 이메일로 답변을 받습니다",
  "replyChannel": "답변 채널",
  "replyEmail": "답변 이메일",
  "invalidEmail": "유효한 답변 이메일을 입력하세요.",
  "requiredEmail": "답변 이메일이 필요합니다.",
  "problem": "무슨 일이 있었나요?",
  "problemLabel": "문제 설명",
  "problemHint": "필수 항목입니다. 비밀번호, 토큰, 채팅 기록 또는 비공개 파일을 포함하지 마세요",
  "boundary": "Hey Hermes는 앱 버전, 플랫폼, 언어와 시간을 자동으로 추가합니다. 채팅, 프롬프트, 인증 정보, 로그, 워크스페이스 파일이나 VPS 데이터는 첨부하지 않습니다. 비밀번호나 토큰을 붙여 넣지 마세요. 이 양식을 제출해도 지원 패스나 비공개 데이터 접근 권한은 부여되지 않습니다.",
  "reference": "지원 참조 번호:",
  "sending": "보내는 중…",
  "retryRequest": "지원 요청 다시 보내기",
  "sendRequest": "지원 요청 보내기",
  "copy": "복사",
  "offline": "오프라인 상태인 것 같습니다. 다시 연결하여 시도하거나 아래 지원 이메일을 이용하세요.",
  "rateLimited": "지원 요청을 너무 많이 시도했습니다. 잠시 기다렸다가 다시 시도하거나 아래 지원 이메일을 이용하세요.",
  "sessionExpired": "로그인 세션이 종료되었습니다. 다시 로그인하거나 아래 지원 이메일을 이용하세요.",
  "deliveryFailed": "문의가 기록되었으나 이메일 전송에 실패했습니다. 아래 지원 이메일로 참조 번호를 포함해 문의하세요.",
  "deliveryPending": "문의가 기록되었으며 전송 여부를 확인 중입니다. 참조 번호를 보관하고 잠시 후 다시 시도하세요.",
  "invalidInput": "인증 정보나 지원되지 않는 내용을 제거한 후 다시 시도하세요.",
  "invalidResponse": "지원 서비스가 잘못된 응답을 반환했습니다. 전송 완료로 표시하지 않습니다. 다시 시도하거나 아래 이메일을 이용하세요.",
  "unavailable": "현재 지원 양식을 사용할 수 없습니다. 전송 완료로 표시하지 않습니다. 다시 시도하거나 아래 이메일을 이용하세요.",
  "problemTooLong": "설명은 4,000자 미만으로 작성하세요.",
  "problemSensitive": "보내기 전에 비밀번호, 토큰 또는 개인 키를 제거하세요.",
  "problemRequired": "보내기 전에 문제를 설명하세요."
},
};

export function supportRequestCopy(locale: AppLocale = defaultAppLocale) {
  return copy[locale] ?? copy[defaultAppLocale];
}
