import type { AppLocale } from "./types";

const en = {
  "title": "Temporary support access",
  "footer": "A normal support request grants no access. Support access expires automatically and can be withdrawn under Account > Security.",
  "expandDetail": "A normal support request grants no access. Expand only when support asks you to allow a time-limited health check.",
  "allow": "Allow temporary support access",
  "rights": "Support access lasts minutes and carries three read-only rights: diagnostics, redacted logs, and service status.",
  "scope": "It can inspect this exact workspace’s service, runtime and dashboard health and recent redacted errors. It cannot read chats, files, credentials, provider accounts, or take actions. The one-time code is not sent with your support request; copy and share it separately only when support asks.",
  "reason": "Reason for support access",
  "minutes": "Minutes (1–240)",
  "create": "Create one-time support code",
  "readonly": "Read-only and temporary",
  "code": "One-time support code",
  "copyNotice": "This code is not sent automatically. Copy it now; the full value is shown only here.",
  "copyAction": "Copy support code",
  "copiedAction": "Support code copied",
  "copied": "Copied",
  "manage": "What is open, and the way to close it, is under Account > Security.",
  "noAccess": "No support access is open. What you grant appears under Account > Security, where you can also withdraw it.",
  "openCount": "{count} open",
  "noneOpen": "none open",
  "webIntro": "A support request on its own gives no access.",
  "webScope": "It can read service, runtime and dashboard health and recent redacted errors — never chats, files, credentials or provider accounts — and it can take no action.",
  "webCreate": "Create support access",
  "webCode": "Copy this code now. It is shown once, and it is not sent with your support request:",
  "legal": "Legal and support",
  "privacyTitle": "What is protected",
  "privacyConnections": "Saved connection details are encrypted and hidden after saving.",
  "privacySupport": "Support can enter only with a temporary code you create.",
  "privacyIsolation": "Each account is kept in its own private space.",
  "privacyProcessing": "Messages and files are processed by Hey Hermes inside this private workspace.",
  "contactSupport": "Contact support"
};
const catalog: Record<AppLocale, typeof en> = { en,
"de": {
  "title": "Zeitlich begrenzter Supportzugriff",
  "footer": "Eine normale Supportanfrage gewährt keinen Zugriff. Supportzugriff läuft automatisch ab und lässt sich unter Account > Sicherheit widerrufen.",
  "expandDetail": "Eine normale Supportanfrage gewährt keinen Zugriff. Öffne diesen Bereich nur, wenn der Support um eine zeitlich begrenzte Zustandsprüfung bittet.",
  "allow": "Zeitlich begrenzten Supportzugriff erlauben",
  "rights": "Supportzugriff dauert Minuten und umfasst drei reine Leserechte: Diagnose, bereinigte Protokolle und Dienststatus.",
  "scope": "Er kann den Dienst-, Laufzeit- und Dashboardzustand dieses Workspaces sowie aktuelle bereinigte Fehler prüfen. Er kann weder Chats, Dateien, Zugangsdaten oder Provider-Accounts lesen noch Aktionen ausführen. Der Einmalcode wird nicht mit deiner Supportanfrage gesendet; kopiere und teile ihn separat nur auf Bitte des Supports.",
  "reason": "Grund für den Supportzugriff",
  "minutes": "Minuten (1–240)",
  "create": "Einmaligen Supportcode erstellen",
  "readonly": "Nur Lesen, zeitlich begrenzt",
  "code": "Einmaliger Supportcode",
  "copyNotice": "Dieser Code wird nicht automatisch gesendet. Kopiere ihn jetzt; der vollständige Wert wird nur hier angezeigt.",
  "copyAction": "Supportcode kopieren",
  "copiedAction": "Supportcode kopiert",
  "copied": "Kopiert",
  "manage": "Offene Zugriffe und deren Widerruf findest du unter Account > Sicherheit.",
  "noAccess": "Kein Supportzugriff offen. Deine Freigabe erscheint unter Account > Sicherheit und lässt sich dort widerrufen.",
  "openCount": "{count} offen",
  "noneOpen": "keine offen",
  "webIntro": "Eine Supportanfrage allein gewährt keinen Zugriff.",
  "webScope": "Er kann Dienst-, Laufzeit- und Dashboardzustand sowie aktuelle bereinigte Fehler lesen — niemals Chats, Dateien, Zugangsdaten oder Provider-Accounts — und keine Aktionen ausführen.",
  "webCreate": "Supportzugriff erstellen",
  "webCode": "Kopiere diesen Code jetzt. Er wird einmal angezeigt und nicht mit deiner Supportanfrage gesendet:",
  "legal": "Rechtliches und Support",
  "privacyTitle": "Was geschützt ist",
  "privacyConnections": "Gespeicherte Verbindungsdaten sind verschlüsselt und nach dem Speichern verborgen.",
  "privacySupport": "Support erhält nur mit einem von dir erstellten zeitlich begrenzten Code Zugang.",
  "privacyIsolation": "Jeder Account hat seinen eigenen privaten Bereich.",
  "privacyProcessing": "Nachrichten und Dateien werden von Hey Hermes innerhalb dieses privaten Workspaces verarbeitet.",
  "contactSupport": "Support kontaktieren"
},
"fr": {
  "title": "Accès temporaire au support",
  "footer": "Une demande normale au support ne donne aucun accès. L’accès expire automatiquement et peut être révoqué dans Compte > Sécurité.",
  "expandDetail": "Une demande normale au support ne donne aucun accès. Développez uniquement si le support demande une vérification temporaire de l’état.",
  "allow": "Autoriser un accès temporaire au support",
  "rights": "L’accès dure quelques minutes et comporte trois droits de lecture : diagnostic, journaux expurgés et état du service.",
  "scope": "Il permet d’inspecter l’état des services, de l’exécution et du tableau de bord de cet espace précis, ainsi que les erreurs récentes expurgées. Il ne permet ni de lire les chats, fichiers, identifiants ou comptes fournisseurs, ni d’agir. Le code à usage unique n’est pas envoyé avec votre demande ; copiez-le et partagez-le séparément uniquement à la demande du support.",
  "reason": "Motif de l’accès au support",
  "minutes": "Minutes (1–240)",
  "create": "Créer un code de support à usage unique",
  "readonly": "Lecture seule et temporaire",
  "code": "Code de support à usage unique",
  "copyNotice": "Ce code n’est pas envoyé automatiquement. Copiez-le maintenant ; sa valeur complète n’apparaît qu’ici.",
  "copyAction": "Copier le code de support",
  "copiedAction": "Code de support copié",
  "copied": "Copié",
  "manage": "Les accès ouverts et leur révocation se trouvent dans Compte > Sécurité.",
  "noAccess": "Aucun accès au support n’est ouvert. Vos autorisations apparaissent dans Compte > Sécurité, où vous pouvez les révoquer.",
  "openCount": "{count} ouverts",
  "noneOpen": "aucun ouvert",
  "webIntro": "Une demande au support seule ne donne aucun accès.",
  "webScope": "Il peut lire l’état des services, de l’exécution et du tableau de bord ainsi que les erreurs récentes expurgées — jamais les chats, fichiers, identifiants ou comptes fournisseurs — et ne peut effectuer aucune action.",
  "webCreate": "Créer un accès au support",
  "webCode": "Copiez ce code maintenant. Il n’apparaît qu’une fois et n’est pas envoyé avec votre demande au support :",
  "legal": "Informations légales et support",
  "privacyTitle": "Ce qui est protégé",
  "privacyConnections": "Les données de connexion enregistrées sont chiffrées et masquées après enregistrement.",
  "privacySupport": "Le support ne peut accéder qu’avec un code temporaire que vous créez.",
  "privacyIsolation": "Chaque compte dispose de son propre espace privé.",
  "privacyProcessing": "Les messages et fichiers sont traités par Hey Hermes dans cet espace privé.",
  "contactSupport": "Contacter le support"
},
"es": {
  "title": "Acceso temporal de soporte",
  "footer": "Una solicitud normal de soporte no concede acceso. El acceso caduca automáticamente y se puede revocar en Cuenta > Seguridad.",
  "expandDetail": "Una solicitud normal de soporte no concede acceso. Amplía esta sección solo cuando soporte solicite una comprobación de estado por tiempo limitado.",
  "allow": "Permitir acceso temporal de soporte",
  "rights": "El acceso dura minutos y ofrece tres permisos de solo lectura: diagnósticos, registros censurados y estado del servicio.",
  "scope": "Permite revisar el estado del servicio, la ejecución y el panel de este espacio concreto, además de errores recientes censurados. No permite leer chats, archivos, credenciales o cuentas de proveedores ni realizar acciones. El código de un solo uso no se envía con tu solicitud; cópialo y compártelo por separado solo cuando soporte lo pida.",
  "reason": "Motivo del acceso de soporte",
  "minutes": "Minutos (1–240)",
  "create": "Crear código de soporte de un solo uso",
  "readonly": "Solo lectura y temporal",
  "code": "Código de soporte de un solo uso",
  "copyNotice": "Este código no se envía automáticamente. Cópialo ahora; el valor completo solo se muestra aquí.",
  "copyAction": "Copiar código de soporte",
  "copiedAction": "Código de soporte copiado",
  "copied": "Copiado",
  "manage": "Los accesos abiertos y su revocación están en Cuenta > Seguridad.",
  "noAccess": "No hay acceso de soporte abierto. Lo que autorices aparece en Cuenta > Seguridad, donde puedes revocarlo.",
  "openCount": "{count} abiertos",
  "noneOpen": "ninguno abierto",
  "webIntro": "Una solicitud de soporte por sí sola no concede acceso.",
  "webScope": "Permite leer el estado del servicio, la ejecución y el panel y los errores recientes censurados — nunca chats, archivos, credenciales o cuentas de proveedores — y no permite realizar acciones.",
  "webCreate": "Crear acceso de soporte",
  "webCode": "Copia este código ahora. Se muestra una vez y no se envía con tu solicitud de soporte:",
  "legal": "Información legal y soporte",
  "privacyTitle": "Qué está protegido",
  "privacyConnections": "Los datos de conexión guardados están cifrados y ocultos tras guardarlos.",
  "privacySupport": "Soporte solo puede acceder con un código temporal que tú creas.",
  "privacyIsolation": "Cada cuenta tiene su propio espacio privado.",
  "privacyProcessing": "Hey Hermes procesa los mensajes y archivos dentro de este espacio privado.",
  "contactSupport": "Contactar con soporte"
},
"it": {
  "title": "Accesso temporaneo al supporto",
  "footer": "Una normale richiesta di supporto non concede accesso. L’accesso scade automaticamente e può essere revocato in Account > Sicurezza.",
  "expandDetail": "Una normale richiesta di supporto non concede accesso. Espandi solo se il supporto chiede una verifica dello stato per un periodo limitato.",
  "allow": "Consenti accesso temporaneo al supporto",
  "rights": "L’accesso dura minuti e include tre permessi di sola lettura: diagnostica, registri oscurati e stato del servizio.",
  "scope": "Può controllare lo stato dei servizi, dell’esecuzione e della dashboard di questo preciso spazio, oltre agli errori recenti oscurati. Non può leggere chat, file, credenziali o account dei fornitori, né eseguire azioni. Il codice monouso non viene inviato con la richiesta; copialo e condividilo separatamente solo quando lo chiede il supporto.",
  "reason": "Motivo dell’accesso al supporto",
  "minutes": "Minuti (1–240)",
  "create": "Crea codice di supporto monouso",
  "readonly": "Sola lettura e temporaneo",
  "code": "Codice di supporto monouso",
  "copyNotice": "Questo codice non viene inviato automaticamente. Copialo ora; il valore completo appare solo qui.",
  "copyAction": "Copia codice di supporto",
  "copiedAction": "Codice di supporto copiato",
  "copied": "Copiato",
  "manage": "Gli accessi aperti e la loro revoca si trovano in Account > Sicurezza.",
  "noAccess": "Nessun accesso al supporto aperto. Le autorizzazioni compaiono in Account > Sicurezza, dove puoi revocarle.",
  "openCount": "{count} aperti",
  "noneOpen": "nessuno aperto",
  "webIntro": "Una richiesta di supporto da sola non concede accesso.",
  "webScope": "Può leggere lo stato dei servizi, dell’esecuzione e della dashboard e gli errori recenti oscurati — mai chat, file, credenziali o account dei fornitori — e non può eseguire azioni.",
  "webCreate": "Crea accesso al supporto",
  "webCode": "Copia questo codice ora. Appare una volta e non viene inviato con la richiesta di supporto:",
  "legal": "Informazioni legali e supporto",
  "privacyTitle": "Cosa è protetto",
  "privacyConnections": "I dati di connessione salvati sono crittografati e nascosti dopo il salvataggio.",
  "privacySupport": "Il supporto può accedere solo con un codice temporaneo creato da te.",
  "privacyIsolation": "Ogni account ha il proprio spazio privato.",
  "privacyProcessing": "Hey Hermes elabora messaggi e file all’interno di questo spazio privato.",
  "contactSupport": "Contatta il supporto"
},
"pt-BR": {
  "title": "Acesso temporário de suporte",
  "footer": "Uma solicitação normal de suporte não concede acesso. O acesso expira automaticamente e pode ser revogado em Conta > Segurança.",
  "expandDetail": "Uma solicitação normal de suporte não concede acesso. Expanda apenas quando o suporte pedir uma verificação de estado por tempo limitado.",
  "allow": "Permitir acesso temporário de suporte",
  "rights": "O acesso dura minutos e inclui três permissões de leitura: diagnóstico, registros com dados ocultados e estado do serviço.",
  "scope": "Permite verificar o estado dos serviços, da execução e do painel deste espaço específico, além de erros recentes com dados ocultados. Não pode ler chats, arquivos, credenciais ou contas de provedores nem executar ações. O código de uso único não é enviado com sua solicitação; copie e compartilhe separadamente apenas quando o suporte pedir.",
  "reason": "Motivo do acesso de suporte",
  "minutes": "Minutos (1–240)",
  "create": "Criar código de suporte de uso único",
  "readonly": "Somente leitura e temporário",
  "code": "Código de suporte de uso único",
  "copyNotice": "Este código não é enviado automaticamente. Copie agora; o valor completo aparece somente aqui.",
  "copyAction": "Copiar código de suporte",
  "copiedAction": "Código de suporte copiado",
  "copied": "Copiado",
  "manage": "Os acessos abertos e sua revogação ficam em Conta > Segurança.",
  "noAccess": "Nenhum acesso de suporte aberto. Suas permissões aparecem em Conta > Segurança, onde você pode revogá-las.",
  "openCount": "{count} abertos",
  "noneOpen": "nenhum aberto",
  "webIntro": "Uma solicitação de suporte por si só não concede acesso.",
  "webScope": "Pode ler o estado dos serviços, da execução e do painel e erros recentes com dados ocultados — nunca chats, arquivos, credenciais ou contas de provedores — e não pode executar ações.",
  "webCreate": "Criar acesso de suporte",
  "webCode": "Copie este código agora. Ele aparece uma vez e não é enviado com sua solicitação de suporte:",
  "legal": "Informações legais e suporte",
  "privacyTitle": "O que está protegido",
  "privacyConnections": "Os dados de conexão salvos são criptografados e ocultos após salvar.",
  "privacySupport": "O suporte só pode entrar com um código temporário que você cria.",
  "privacyIsolation": "Cada conta tem seu próprio espaço privado.",
  "privacyProcessing": "Mensagens e arquivos são processados pelo Hey Hermes dentro deste espaço privado.",
  "contactSupport": "Contatar suporte"
},
"ja": {
  "title": "一時的なサポートアクセス",
  "footer": "通常のサポート依頼ではアクセスは許可されません。アクセスは自動で期限切れになり、アカウント > セキュリティで取り消せます。",
  "expandDetail": "通常のサポート依頼ではアクセスは許可されません。サポートから時間制限付きの状態確認を依頼された場合のみ展開してください。",
  "allow": "一時的なサポートアクセスを許可",
  "rights": "アクセスは分単位で、診断、機密情報を除いたログ、サービス状態の3つの読み取り権限を含みます。",
  "scope": "このワークスペースのサービス、実行環境、ダッシュボードの状態と、機密情報を除いた最近のエラーを確認できます。チャット、ファイル、認証情報、プロバイダーのアカウントを読み取ったり、操作したりすることはできません。ワンタイムコードはサポート依頼には添付されません。サポートから求められた場合のみコピーして別途共有してください。",
  "reason": "サポートアクセスの理由",
  "minutes": "分（1～240）",
  "create": "ワンタイムサポートコードを作成",
  "readonly": "読み取り専用・一時的",
  "code": "ワンタイムサポートコード",
  "copyNotice": "このコードは自動送信されません。完全な値はここにしか表示されないため、今コピーしてください。",
  "copyAction": "サポートコードをコピー",
  "copiedAction": "サポートコードをコピーしました",
  "copied": "コピー済み",
  "manage": "有効なアクセスと取り消し方法はアカウント > セキュリティにあります。",
  "noAccess": "有効なサポートアクセスはありません。許可したアクセスはアカウント > セキュリティに表示され、そこで取り消せます。",
  "openCount": "有効：{count}件",
  "noneOpen": "有効なアクセスなし",
  "webIntro": "サポート依頼だけではアクセスは許可されません。",
  "webScope": "サービス、実行環境、ダッシュボードの状態と、機密情報を除いた最近のエラーを読み取れます。チャット、ファイル、認証情報、プロバイダーのアカウントの閲覧や操作はできません。",
  "webCreate": "サポートアクセスを作成",
  "webCode": "今このコードをコピーしてください。一度だけ表示され、サポート依頼には添付されません：",
  "legal": "法的情報とサポート",
  "privacyTitle": "保護されるもの",
  "privacyConnections": "保存した接続情報は暗号化され、保存後は非表示になります。",
  "privacySupport": "サポートはあなたが作成した一時コードでのみアクセスできます。",
  "privacyIsolation": "各アカウントは専用のプライベート空間に分離されます。",
  "privacyProcessing": "メッセージとファイルは、このプライベートなワークスペース内でHey Hermesが処理します。",
  "contactSupport": "サポートに連絡"
},
"ko": {
  "title": "임시 지원 접근",
  "footer": "일반 지원 요청은 접근 권한을 부여하지 않습니다. 지원 접근은 자동 만료되며 계정 > 보안에서 철회할 수 있습니다.",
  "expandDetail": "일반 지원 요청은 접근 권한을 부여하지 않습니다. 지원팀이 제한된 시간 동안 상태 확인을 요청한 경우에만 펼치세요.",
  "allow": "임시 지원 접근 허용",
  "rights": "지원 접근은 분 단위로 유지되며 진단, 민감 정보가 가려진 로그, 서비스 상태의 세 가지 읽기 권한을 포함합니다.",
  "scope": "이 워크스페이스의 서비스, 실행 환경, 대시보드 상태와 민감 정보가 가려진 최근 오류를 확인할 수 있습니다. 채팅, 파일, 인증 정보 또는 제공업체 계정을 읽거나 작업을 수행할 수 없습니다. 일회용 코드는 지원 요청에 포함되지 않습니다. 지원팀이 요청한 경우에만 복사하여 별도로 공유하세요.",
  "reason": "지원 접근 사유",
  "minutes": "분(1~240)",
  "create": "일회용 지원 코드 만들기",
  "readonly": "읽기 전용 및 임시",
  "code": "일회용 지원 코드",
  "copyNotice": "이 코드는 자동으로 전송되지 않습니다. 전체 값은 여기에만 표시되므로 지금 복사하세요.",
  "copyAction": "지원 코드 복사",
  "copiedAction": "지원 코드를 복사했습니다",
  "copied": "복사됨",
  "manage": "열린 접근과 철회 방법은 계정 > 보안에 있습니다.",
  "noAccess": "열린 지원 접근이 없습니다. 허용한 접근은 계정 > 보안에 표시되며 그곳에서 철회할 수 있습니다.",
  "openCount": "열림: {count}개",
  "noneOpen": "열린 접근 없음",
  "webIntro": "지원 요청만으로는 접근 권한이 부여되지 않습니다.",
  "webScope": "서비스, 실행 환경, 대시보드 상태와 민감 정보가 가려진 최근 오류만 읽을 수 있습니다. 채팅, 파일, 인증 정보 또는 제공업체 계정을 읽거나 작업을 수행할 수 없습니다.",
  "webCreate": "지원 접근 만들기",
  "webCode": "지금 이 코드를 복사하세요. 한 번만 표시되며 지원 요청에 포함되지 않습니다:",
  "legal": "법적 정보 및 지원",
  "privacyTitle": "보호되는 항목",
  "privacyConnections": "저장된 연결 정보는 암호화되며 저장 후 숨겨집니다.",
  "privacySupport": "지원팀은 사용자가 만든 임시 코드로만 접근할 수 있습니다.",
  "privacyIsolation": "각 계정은 별도의 비공개 공간에 보관됩니다.",
  "privacyProcessing": "메시지와 파일은 이 비공개 워크스페이스 안에서 Hey Hermes가 처리합니다.",
  "contactSupport": "지원팀에 문의"
}
};
export function supportAccessCopy(locale: AppLocale) { return catalog[locale]; }

const oneOpen: Partial<Record<AppLocale, string>> = { fr: "{count} ouvert", es: "{count} abierto", it: "{count} aperto", "pt-BR": "{count} aberto" };
export function supportAccessOpenCount(locale: AppLocale, count: number): string {
  const copy = supportAccessCopy(locale);
  const template = new Intl.PluralRules(locale).select(count) === "one" ? oneOpen[locale] ?? copy.openCount : copy.openCount;
  return template.replace("{count}", count.toLocaleString(locale));
}
