import type { AppLocale } from "../core/index";

const en = {
  "title": "Secure credential entry",
  "explanation": "These values go directly to encrypted workspace storage. They are never added to chat or shown to Hermes.",
  "telegramToken": "Telegram bot token",
  "whatsappPhoneId": "WhatsApp phone number ID",
  "phoneIdPlaceholder": "Meta phone number ID",
  "whatsappToken": "WhatsApp access token",
  "placeholder": "Paste once, then save securely",
  "pairingTitle": "Pairing code from the bot",
  "pairingBody": "Write to your bot on Telegram. It answers with a code. Enter that code here and the bot will talk to you. A typo does not use the code up, so correct it and send the same code again rather than asking the bot for another one. Wrong codes add up, and enough of them stop Hermes from accepting codes for an hour.",
  "pairingPlaceholder": "Eight letters and digits",
  "approving": "Approving…",
  "approve": "Approve this code",
  "saving": "Saving…",
  "save": "Save securely",
  "askHermes": "Ask Hermes"
};

const catalog: Record<AppLocale, typeof en> = {
  en,
  "de": {
  "title": "Zugangsdaten sicher eingeben",
  "explanation": "Diese Werte werden direkt im Workspace verschlüsselt gespeichert. Sie erscheinen weder im Chat noch werden sie Hermes angezeigt.",
  "telegramToken": "Telegram-Bot-Token",
  "whatsappPhoneId": "WhatsApp-Telefonnummer-ID",
  "phoneIdPlaceholder": "Meta-Telefonnummer-ID",
  "whatsappToken": "WhatsApp-Zugriffstoken",
  "placeholder": "Einmal einfügen, dann sicher speichern",
  "pairingTitle": "Kopplungscode vom Bot",
  "pairingBody": "Schreibe deinem Bot auf Telegram. Er antwortet mit einem Code. Gib ihn hier ein, damit der Bot mit dir spricht. Ein Tippfehler verbraucht den Code nicht: Korrigiere ihn und sende denselben Code erneut, statt einen neuen anzufordern. Falsche Codes werden gezählt; zu viele führen dazu, dass Hermes eine Stunde lang keine Codes annimmt.",
  "pairingPlaceholder": "Acht Buchstaben und Ziffern",
  "approving": "Wird bestätigt…",
  "approve": "Diesen Code bestätigen",
  "saving": "Wird gespeichert…",
  "save": "Sicher speichern",
  "askHermes": "Hermes fragen"
},
  "fr": {
  "title": "Saisie sécurisée des identifiants",
  "explanation": "Ces valeurs sont directement stockées sous forme chiffrée dans l’espace de travail. Elles ne sont jamais ajoutées au chat ni montrées à Hermes.",
  "telegramToken": "Jeton du bot Telegram",
  "whatsappPhoneId": "Identifiant du numéro WhatsApp",
  "phoneIdPlaceholder": "Identifiant du numéro Meta",
  "whatsappToken": "Jeton d’accès WhatsApp",
  "placeholder": "Collez une fois, puis enregistrez en toute sécurité",
  "pairingTitle": "Code d’association du bot",
  "pairingBody": "Écrivez à votre bot sur Telegram. Il répond avec un code. Saisissez-le ici pour que le bot vous parle. Une faute de frappe ne consomme pas le code : corrigez-la et renvoyez le même code au lieu d’en demander un autre. Les codes erronés s’accumulent et, s’ils sont trop nombreux, Hermes refuse les codes pendant une heure.",
  "pairingPlaceholder": "Huit lettres et chiffres",
  "approving": "Validation…",
  "approve": "Valider ce code",
  "saving": "Enregistrement…",
  "save": "Enregistrer en toute sécurité",
  "askHermes": "Demander à Hermes"
},
  "es": {
  "title": "Entrada segura de credenciales",
  "explanation": "Estos valores se guardan directamente cifrados en el espacio de trabajo. Nunca se añaden al chat ni se muestran a Hermes.",
  "telegramToken": "Token del bot de Telegram",
  "whatsappPhoneId": "ID del número de WhatsApp",
  "phoneIdPlaceholder": "ID del número de Meta",
  "whatsappToken": "Token de acceso de WhatsApp",
  "placeholder": "Pega una vez y guarda de forma segura",
  "pairingTitle": "Código de vinculación del bot",
  "pairingBody": "Escribe a tu bot en Telegram. Responderá con un código. Introdúcelo aquí para que el bot hable contigo. Un error de escritura no consume el código: corrígelo y envía el mismo código en vez de pedir otro. Los códigos incorrectos se acumulan y, si son demasiados, Hermes deja de aceptar códigos durante una hora.",
  "pairingPlaceholder": "Ocho letras y dígitos",
  "approving": "Aprobando…",
  "approve": "Aprobar este código",
  "saving": "Guardando…",
  "save": "Guardar de forma segura",
  "askHermes": "Preguntar a Hermes"
},
  "it": {
  "title": "Inserimento sicuro delle credenziali",
  "explanation": "Questi valori vengono archiviati direttamente in forma crittografata nello spazio di lavoro. Non vengono mai aggiunti alla chat né mostrati a Hermes.",
  "telegramToken": "Token del bot Telegram",
  "whatsappPhoneId": "ID del numero WhatsApp",
  "phoneIdPlaceholder": "ID del numero Meta",
  "whatsappToken": "Token di accesso WhatsApp",
  "placeholder": "Incolla una volta, poi salva in sicurezza",
  "pairingTitle": "Codice di associazione del bot",
  "pairingBody": "Scrivi al tuo bot su Telegram. Risponde con un codice. Inseriscilo qui e il bot parlerà con te. Un errore di battitura non consuma il codice: correggilo e invia lo stesso codice invece di chiederne un altro. I codici errati si accumulano e, se sono troppi, Hermes smette di accettarli per un’ora.",
  "pairingPlaceholder": "Otto lettere e cifre",
  "approving": "Approvazione…",
  "approve": "Approva questo codice",
  "saving": "Salvataggio…",
  "save": "Salva in sicurezza",
  "askHermes": "Chiedi a Hermes"
},
  "pt-BR": {
  "title": "Entrada segura de credenciais",
  "explanation": "Estes valores são armazenados diretamente de forma criptografada no espaço de trabalho. Nunca são adicionados ao chat nem mostrados ao Hermes.",
  "telegramToken": "Token do bot do Telegram",
  "whatsappPhoneId": "ID do número do WhatsApp",
  "phoneIdPlaceholder": "ID do número da Meta",
  "whatsappToken": "Token de acesso do WhatsApp",
  "placeholder": "Cole uma vez e salve com segurança",
  "pairingTitle": "Código de pareamento do bot",
  "pairingBody": "Escreva para seu bot no Telegram. Ele responderá com um código. Insira-o aqui para que o bot converse com você. Um erro de digitação não consome o código: corrija e envie o mesmo código em vez de pedir outro. Os códigos incorretos se acumulam e, se forem muitos, o Hermes deixa de aceitar códigos por uma hora.",
  "pairingPlaceholder": "Oito letras e dígitos",
  "approving": "Aprovando…",
  "approve": "Aprovar este código",
  "saving": "Salvando…",
  "save": "Salvar com segurança",
  "askHermes": "Perguntar ao Hermes"
},
  "ja": {
  "title": "認証情報の安全な入力",
  "explanation": "これらの値はワークスペースに直接暗号化して保存されます。チャットに追加されたり、Hermesに表示されたりすることはありません。",
  "telegramToken": "Telegramボットのトークン",
  "whatsappPhoneId": "WhatsAppの電話番号ID",
  "phoneIdPlaceholder": "Metaの電話番号ID",
  "whatsappToken": "WhatsAppのアクセストークン",
  "placeholder": "一度貼り付けて安全に保存",
  "pairingTitle": "ボットから届いたペアリングコード",
  "pairingBody": "Telegramでボットにメッセージを送ると、コードが返信されます。ここに入力するとボットと会話できます。入力ミスでコードが消費されることはないので、新しいコードを求めず、修正して同じコードを再送してください。誤ったコードの回数は蓄積され、多すぎるとHermesは1時間コードを受け付けなくなります。",
  "pairingPlaceholder": "英数字8文字",
  "approving": "承認中…",
  "approve": "このコードを承認",
  "saving": "保存中…",
  "save": "安全に保存",
  "askHermes": "Hermesに聞く"
},
  "ko": {
  "title": "안전한 인증 정보 입력",
  "explanation": "이 값들은 워크스페이스에 직접 암호화되어 저장됩니다. 채팅에 추가되거나 Hermes에 표시되지 않습니다.",
  "telegramToken": "Telegram 봇 토큰",
  "whatsappPhoneId": "WhatsApp 전화번호 ID",
  "phoneIdPlaceholder": "Meta 전화번호 ID",
  "whatsappToken": "WhatsApp 접근 토큰",
  "placeholder": "한 번 붙여 넣은 후 안전하게 저장하세요",
  "pairingTitle": "봇에서 받은 연결 코드",
  "pairingBody": "Telegram에서 봇에게 메시지를 보내면 코드를 답장합니다. 여기에 입력하면 봇과 대화할 수 있습니다. 오타가 나도 코드는 소모되지 않으므로 새 코드를 요청하지 말고 수정한 뒤 같은 코드를 다시 보내세요. 잘못된 코드는 누적되며 너무 많으면 Hermes가 한 시간 동안 코드를 받지 않습니다.",
  "pairingPlaceholder": "영문자와 숫자 8자리",
  "approving": "승인 중…",
  "approve": "이 코드 승인",
  "saving": "저장 중…",
  "save": "안전하게 저장",
  "askHermes": "Hermes에게 묻기"
},
};

export function secureConnectionCredentialCopy(locale: AppLocale = "en") {
  return catalog[locale] ?? catalog.en;
}
